### ISSUE TITLE
Decide if and how to indicate on the search results that a record has been viewed

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#101]
This is an additional feature, but should be born in mind in making some decisions (e.g. layout, use of colour) in the MVP interface, if it is decided that it is wanted (then change milestone to appropriate phase).

For discussion: users may find it helpful to see/hear in some way whether a record has already been viewed or not . On FreeREG this is done by changing the row number to add "(viewed)". This is not (yet) implemented on FreeCEN, but has been asked for a lot.  
![FreeCEN Viewed row.JPG](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/790099c1-4175-4e48-b340-71bf7ae460b8)

**Comment by richpomfret** [comment]
Discussion also over on System Wide relating to this.

**Comment by PatReynolds** [comment]
See https://app.zenhub.com/workspaces/system-wide-code-changes-5ccc857f10a32d7d637c8f48/issues/freeukgen/systemwide/41 for implementation decision.

**Comment by richpomfret** [comment]
Done - shall close once implementation story has been added.
