### ISSUE TITLE
How do we handle citations?

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#109]
On one hand, we can simply take the multimodal code over for this. However, we need to consider how we handle OLD citations from FreeBMD1 - these are/were 'permanent' and FreeBMD2 will need to take this into account. Do we find a way to redirect to equivalent records on BMD2? Will the structure of citations on BMD2 differ much or at all from BMD1?

**Comment by PatReynolds** [comment]
A suggestion:
Initally, the FreeBMD2 permanent URL will be used (https://freebmd2.freebmd.org.uk/….)
At ‘switch’ of urls, the URL will become (https://www.freebmd.org.uk/….)
At ‘switch’, the FreeBMD1 urls will need some form of re-routing, at first from https://www.freebmd.org.uk/cgi/information.pl?cite=LTEgJzcsqcxaj7uoIdEu%2BA&scan=1 to https:/freebmd1.freebmd.org.uk/cgi/information.pl?cite=LTEgJzcsqcxaj7uoIdEu%2BA&scan=1 later to ???

**Comment by PatReynolds** [comment]
First draft of model citations: https://docs.google.com/document/d/1Ab_Kws579BqkLW_GJZCSZZZC6VqiY0BNy-qGN3SgwdM/edit?usp=sharing 

please ask if you need access (should be available with a free uk genealogy email address).

**Comment by PatReynolds** [comment]
Decision: make it the test site "permanent" url at this point, but switch when we make FreeBMD2 more public.

**Comment by PatReynolds** [comment]
For Beta site, users will find the saved url takes them back to FreeBMD1.  At full launch, this will not occur.

**Comment by PatReynolds** [comment]
Developers need to confirm that this will work.

**Comment by Captainkirkdawson** [comment]
IMO

1. We extend the citation options to include the BMD citation format.
2. Phase 1 testing of the app will be against the current test database Hence there will be no permanency to any citations generated and WE SHOULD clearly indicate that to the testing community.
3. We need to understand how BMD1 achieves permanency to a specific record given that they rebuild the database monthly
4. We achieve permanency by making any updates in situ to the specific record.  There are a very limited set of conditions when this CANNOT be achieved (The record moves from one county to another or the sex of the person is changed). We do NOT rebuild the database.
5. Citations generated by BMD2 must be resolved by BMD2.
6. Phase2 testing against a live BMD1 database must be done when we have answered point 3.
7. This SAME answer applies to the saved search option where we have to access the records generated by a search that are saved with a search query.
Summary conclusion. I do not yet understand how BMD2 will play with a monthly database build hence how we will work it with citations is pure speculation

**Comment by archerbarrie** [comment]
Regarding point 3, the citation is a hash of most fields of the record so when the database is rebuilt the hash is the same. If the record is changed then it is a new entity and a citatation to a previous entity will not find it.

**Comment by archerbarrie** [comment]
> 
> 
> A suggestion:
> Initally, the FreeBMD2 permanent URL will be used ([https://freebmd2.freebmd.org.uk/…](https://freebmd2.freebmd.org.uk/%E2%80%A6).)
> At ‘switch’ of urls, the URL will become ([https://www.freebmd.org.uk/…](https://www.freebmd.org.uk/%E2%80%A6).)
> At ‘switch’, the FreeBMD1 urls will need some form of re-routing, at first from https://www.freebmd.org.uk/cgi/information.pl?cite=LTEgJzcsqcxaj7uoIdEu%2BA&scan=1 to https:/freebmd1.freebmd.org.uk/cgi/information.pl?cite=LTEgJzcsqcxaj7uoIdEu%2BA&scan=1 later to ???

Logically the only way to achieve freebmd -> freebmd1 is by recognising from the parameters which system generated the citation. Since this cannot be done for FreeBMD1 (since the citations already exist), there needs to be some way of identifying FreeBMD2 citations.

**Comment by archerbarrie** [comment]
I am surprised that no-one has suggested, or explained why it would not work, to have citations the same on FreeBMD2 as they are on FreeBMD1. The format of FreeREG citations is very similar to FreeBMD so it seems an obvious approach. Well, it does to me anyway!

**Comment by PatReynolds** [comment]
The problem is whether the url should be freebmd2.freebmd.org.uk or www.freebmd.org.uk.  The decision is the latter - while initially it will take researchers to FreeBMD1, rather than FreeBMD2, in the longer term it will be correct.

**Comment by archerbarrie** [comment]
> Since the reference is to the database, not to the website, there is no need to show which site it was originally found on.

OK, good, that means that there is no need to re-route citations generated by FreeBMD1 to FreeBMD1 (as in "At ‘switch’, the FreeBMD1 urls will need some form of re-routing" {7th Aug}), they can be handled by FreeBMD2.

**Comment by Captainkirkdawson** [comment]
@archerbarrie Thank you for the explanation of the way in which BMD handles permanency. Could you give us a link to the actual hash that is used?

**Comment by archerbarrie** [comment]
I think it best to just give you the code. Given a record number, hashBestGuessRecord (in module lib/BMD/Record.pm) returns the hash of that record. The table BestGuessHash table is used to get the record number for any given hash.
```
sub hashBestGuess ($$$$$$$$) {
    setlocale(LC_CTYPE, "en_GB.ISO8859-1");	#so accented characters correctly lc->uc
    my $sname=uc shift;
    my $cname=uc shift;
    my $district=uc shift;
    my $volume=uc shift;
    my $page=uc shift;
    my $year=shift;
    my $quarter=shift;
    my $type=shift;

    return md5_base64("$sname/$cname/$district/$volume/$page/$year/$quarter/$type");
}

sub hashBestGuessRecord ($$) {
    my $dbh = shift;
    my $recNo = shift;

    my $sql = qq(SELECT Surname,Givenname,DistrictName,Volume,
			Page,QuarterNumber,RecordTypeID
		 FROM BestGuess as b, Districts as d
		 WHERE b.DistrictNumber=d.DistrictNumber AND
		       b.RecordNumber=$recNo);
    my $sth = DB::Exec($dbh,$sql) || return undef;
    my ($surname,$firstname,$district,$vol,$page,$qn,$type) = 
		$sth->fetchrow_array();
    return undef unless $type;
    my ($year,$quarter) = fromQN($qn);
    my $hash=BMD::Record::hashBestGuess($surname,$firstname,$district,$vol,
					$page,$year,$quarter,$type);
    return $hash;
}

```

**Comment by PatReynolds** [comment]
@Barrie, when you say on No. 17 that the format of FreeBMD1 citations is similar to FreeREG, do you mean 

https://www.freebmd.org.uk/cgi/information.pl?cite=WQQMeFAhfTjKxcbddFaYCg&scan=1 is similar to
https://www.freereg.org.uk/search_records/5818a072e93790eca38070be
and
{{Cite web|url=https://www.freebmd.org.uk/cgi/information.pl?cite=WQQMeFAhfTjKxcbddFaYCg&scan=1|title=Index entry|accessdate=9 December 2019|work=FreeBMD|publisher=ONS}} is similar to
{{Cite web|url=https://www.freereg.org.uk/search_records/5818a072e93790eca38070be|title=FreeREG - "Parish Register" database|accessdate= 9 Dec 2019|work=FreeREG|publisher=Free UK Genealogy}}

FreeREG/CEN have a much wider range of citations than FreeBMD - which has only Wikipedia (https://www.freebmd.org.uk/cgi/information.pl?cite=WQQMeFAhfTjKxcbddFaYCg&scan=1 is not a citation - nor a permanant url, perhaps quasi-permanent url is a better name for it.

**Comment by PatReynolds** [comment]
I'm a bit confused by your answers, @Kirk - can we go through in the meeting today, please?

**Comment by archerbarrie** [comment]
@PatReynolds  when I said the format of citations is similar what I was really referring to was the linking mechanism. FreeREG uses a hash of the record, and so does FreeBMD. I don't know why you say https://www.freebmd.org.uk/cgi/information.pl?cite=WQQMeFAhfTjKxcbddFaYCg&scan=1 is not a permanent URL. It's as much a permanent URL as FreeREG is, as far as I am aware. Mind you I have commented on many occasions that the term "permanent URL" has not been defined/explained, so perhaps if you did that I would understand.

**Comment by PatReynolds** [comment]
A permanent (aka persistant) URL is a URL which will, forever (or at least decades), link to a specific database entry.   To do this, it has to be independent of the content of the database entry it refers to.

**Comment by PatReynolds** [comment]
Note to self re writing the citations: the reference is to the scan, not to the transcription.  The quasi-PURL (i.e. generated html address which takes to the detailed record page on FreeBMD1 currently, and will take to the detailed record page on FreeBMD2 in due course).

**Comment by PatReynolds** [comment]
For now - serve a quasi-permanent URL will be to FreeBMD1, but before switch we will need to come up with a solution that will work.

**Comment by PatReynolds** [comment]
@PatReynolds to write stories

**Comment by richpomfret** [comment]
Closing. Stories written.
