### ISSUE TITLE
Write technical spec/implementation strategy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#11]
requires #4
requires #19

**Comment by richpomfret** [comment]
Had a discussion with Scott over this - we will begin on it next week when he returns.

**Comment by smrr723** [comment]
I couldn't find the existing template in Google Drive so I've just created a new one with a basic draft here for something to start us off - https://docs.google.com/document/d/1C8W_cqKeAjiLQWzRCKtgRsPlC-bKpigUsTTD-onCxDU/edit?usp=sharing

**Comment by DeniseColbert** [comment]
@richpomfret are we using Scott's draft for this, or do you have a document?

**Comment by smrr723** [comment]
I've updated the original document to reflect the change of direction (i.e. jumping straight into a Rails app), and also added more details to each phase.  

Comments welcome @Vino-S @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
Interesting and very thorough and relatively complete if we had decided to implement BMD2 as a full application in RoR. When looked at I have a sense that delivery time would be 2-3 years with a team of 2-3 people.

However as is often the case I had a somewhat different view of  the scope of our initial development and hence a plan that focused on delivering a product of a much reduced scope.

In my mind the scope of the initial RoR app is restricted to delivering a front end involving solely a search and display application that interfaced with the existing FreeBMD1 mysql database. 

The database would continue to be managed and updated by the FreeBMD1 application. The RoR application would be restricted to accessing only those tables required to support the search and display functions. It would use the core layout and css front end code used by REG and CEN and the FreeBMD2 display approved by the trustees some 4 years ago. Hence the plan should be written to deliver that.

It is clear that others have different views of what we are to do especially when I look at the BMD2 waffle and I may be out in left field but that is my reaction.

**Comment by smrr723** [comment]
I think we are on the same wavelength, though wording might be different.

When you say full RoR application - that is the end goal of the project, but the first iteration should be just what I have called the "MVP", i.e. search and display.  I have also included the addition of a CMS to display the 150 or so pages of text - but the CMS need not be included in the first version of the app if we feel that is too much.

I feel the term "Rails Front End" is also causing some confusion and should be ditched.  My understanding is you cannot have a Rails front end (i.e. views) without a Rails backend to go with it - and you also need a Rails backend to be able to access the mysql database.  It will be a much lighter weight backend than FreeREG/CEN, but still a backend.

**Comment by Captainkirkdawson** [comment]
As always the interpretation of language is a killer. Its even worse when different languages are involved. ( I remember in my working days spending almost 2 years with an intergovernmental panel dealing with the "free availability of data". In some languages it gets interpreted as you can have access but at a cost and in others it means access with no cost). To me back-end is the stuff that is done to manage and create the database with front end being the stuff done to extract and display information from the database.

**Comment by richpomfret** [comment]
@Captainkirkdawson it will be a full RoR app in time - but as you say, that will be staggered and the main focus will be on the core search for quite some time. We SHOULD keep in mind the future functionality and expansion beyond being purely research driven (hence Scott mapping it out), but keeping a firm eye on the search will allow us to experiment a bit more. The fruit of which will, perhaps, carry across into FC/FR. Probably a good idea to define/document the nomenclature too.

**Comment by richpomfret** [comment]
@Vino-S has now taken over this document and is also creating an expanded document to take into account the first few phases of development.

**Comment by Vino-S** [comment]
Link to doc:
https://docs.google.com/document/d/15b_Q5s6Rdk4R8AFKsOwRUejaj1W1p0FmiqKAZhdC0ao/edit#heading=h.f22ddtvy3lfw

**Comment by PatReynolds** [comment]
@richpomfret  to review, and check with @Captainkirkdawson and Barry (?in slack)  before deciding on  option to be developed.

**Comment by Captainkirkdawson** [comment]
Not sure which document is now the active one! The first on which several of us made comments. And this new link that has a few extra point added into the first section. My comment on the latter parts have not been addressed. 
I continue to remain deeply concerned over an approach that appears to propose changes to the existing FreeBMD MySQL tables and the addition of new ones.  (This may be a language semantics issue) I believe that we should NOT make any attempt to change the FreeBMD database structure or tables at this stage. We should focus on implementing a search form UI in RoR that interfaces with the existing database and present the search results in RoR using new displays. ie .We are focused on the user experience with the database we have today NOT changing the way it is structured. Any storage of queries and results should be done within mongodb collections.

The multi modal MyopicVicar is already set up to incorporate a FreeBMD search form within the currently approved layout. It is already set up to store search queries and results. The part that needs to be added is to interface the RoR code with active record and the existing mysql tables rather than through mongoid. 

Once we have that working we should then look into taking the existing FreeBMD database and converting that into a mongodb database as a standalone monthly basis with the database being recreated in mysql as now together with online system management tools. The third phase should be the rewrite of the database creation into RoR. The last phase would be the migration of the update to more frequent updating.

**Comment by Captainkirkdawson** [comment]
I am increasingly concerned that we seem to be drifting into FreeBMD2 code development with no clear agreement on the implementation plan and the basic parameters within which it will be done. Without such a plan we could drift into an open ended project development.

**Comment by Captainkirkdawson** [comment]
@richpomfret  could you confirm which documents we be working with 1) the initial document written by Scott https://docs.google.com/document/d/1C8W_cqKeAjiLQWzRCKtgRsPlC-bKpigUsTTD-onCxDU/edit#heading=h.6x5hfz7lp393 or 2) the more recent technical options written by Vino https://docs.google.com/document/d/15b_Q5s6Rdk4R8AFKsOwRUejaj1W1p0FmiqKAZhdC0ao/edit
My preference is for a single document.

**Comment by Captainkirkdawson** [comment]
I have added minor changes to Phase 1 and 2 and added a final task of phase 2  #7 which is:

Document the decisions made with regard to the actions of phase 1 and 2 regarding the MVP and the development framework for commencement of phase 3.

**Comment by richpomfret** [comment]
Thanks @Captainkirkdawson. Much appreciated - we should be using one single document. Fleshing out specific details (as Vino has done with the Search form) can be done in the latter part of the Tech Spec document. Although we still have comments to close in her document, I'd rather she updates it and then we can move it across to the Tech Spec for a final review/approval.

**Comment by richpomfret** [comment]
@Vino-S can you update your document in response to the queries/comments raised by Barrie/Kirk/Pat (and co) and reply to comments if applicable? Once we move past the MVP (using the multi-modal codebase) we can then look to iterate to include or experiment with some of the more sophisticated changes suggested by our UXers (functionality we do not yet have on FR/FC search).

**Comment by Captainkirkdawson** [comment]
@richpomfret I have provided a draft document for task 7 of phase 2 to freeukgen management. If it reflects current thinking then it should be disseminated to the full project team.

**Comment by richpomfret** [comment]
@Captainkirkdawson replied to the email and yes that helps a lot (as per what we had been discussing but hadn't put onto paper).

**Comment by richpomfret** [comment]
@richpomfret to review where we are and to resolve issues.

**Comment by Captainkirkdawson** [comment]
It would appear that with the actions taken by @PatReynolds on the document providing guidance on the MVP for BMD2 is now clean of comments and can be considered for adoption as part of  Implementation Strategy.

**Comment by richpomfret** [comment]
@Captainkirkdawson document now added into the Tech SPec. I think we can close this and create a new task for 'updating evolving technical solution' (a fancy name for updating the tech spec!).
