### ISSUE TITLE
Design "mobile" search page 

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#111]
Design a wireframe for mobile search page

**Comment by neslihanu** [comment]
Aviel and I`ve created a wireframe for mobile version of search page.
a link and a png file for the prototype are shown below:

https://www.figma.com/proto/VjJhKU9ayU62rwczFyaUX0mt/FreeBMD-search-form-prototype?node-id=451%3A0&scaling=scale-down

![Home Page Mobile.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/319a7407-5818-4802-82b8-a9fc6579bf26)

**Comment by richpomfret** [comment]
Ready for feedback/review.

**Comment by PatReynolds** [comment]
@neslihanu Is there potential to reduce the space taken up by the red banner and footer material?  E.g. reduce size of logos?

**Comment by neslihanu** [comment]
@PatReynolds  I`ll have a look into it. What would be the text in the red banner ? Has it finalised ? It would be good to see it.

**Comment by neslihanu** [comment]
@PatReynolds 

1) I`ve reduced the text sizes on the red banner and footer paragraph. In general, font size needs to be 16 pixels for mobile websites. Anything smaller than that could compromise readability for visually impaired readers.

2) I`ve reduced the size of logos. We can say that they are also "buttons" where the user may click on them and be navigated to the other Free UK Genealogy websites. So, we should consider Finger-Friendly Design. This means that 40 pixels is the minimum.

Please have a look at the updated version.

Here is the link for demo;

https://www.figma.com/proto/VjJhKU9ayU62rwczFyaUX0mt/FreeBMD-search-form-prototype?node-id=451%3A0&scaling=scale-down

Here is the updated wireframe;

![Home Page Mobile.v2.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/cbb20f67-5201-4195-b712-3f8c3a22ab18)

**Comment by PatReynolds** [comment]
This looks good.  Thank you, @neslihanu. 
Footer text should be as on the PC version of FreeBMD2

**Comment by richpomfret** [comment]
Discussed providing a link to the 'Data@..' text rather than include it here - perhaps providing smaller icons for the other FUG project sites also.

**Comment by richpomfret** [comment]
@PatReynolds  to created new page for copyright info.

**Comment by AlOneill** [comment]
@PatReynolds @richpomfret Am not warming to the chopped up look of the nav bar. Has anyone considered giving what is left of the bar itself a white background (instead of the magenta)?

**Comment by PatReynolds** [comment]
Goog point, @AlOneill .  What do you think, @neslihanu ?

**Comment by AlOneill** [comment]
@neslihanu @PatReynolds (I meant to add) or, keep the bar magenta and make the hamburger and "Menu" white?

**Comment by PatReynolds** [comment]
Personally, I like magenta better than white

**Comment by neslihanu** [comment]
@PatReynolds @AlOneill 
Aviel worked on this part, unfortunately we didn't have time to discuss and review this design together before his leave. So, I don't know what was his idea behind this menu design and also I didn't want to change it before you review. 
I prefer a white hamburger menu icon on magenta background. I think when we put menu text + hamburger menu icon, users may click on the word “menu” than the hamburger menu icon.

**Comment by Captainkirkdawson** [comment]
We also need to define what is to be displayed from clicking the menu. Currently the apps display a vertical list of the actions contained in the Nav Bar. This is really part of # as it applies to all pages not just search results

**Comment by neslihanu** [comment]
@PatReynolds what would be the footer text ? I've checked the desktop version of the wireframes on Figma, both are the same. Can you please share it with me ?

**Comment by PatReynolds** [comment]
Something different now needed for the red bar (text here is superceded by the text in the lowest, dark grey, bar.  I will make a separate story for that.

Text in dark grey bar on mobile needs to be changed to the same text as normal version (which is missing a space between the charity number and the next sentence ("1167484.We" needs to be "1167484. We" (I will add that typo to the main footer story).

**Comment by neslihanu** [comment]
Please checked the below design for updates:


![Home Page Mobile.v4.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/50ccfc76-d0b0-4ed9-a6ee-a48f1748bace)

**Comment by neslihanu** [comment]
https://www.figma.com/proto/VjJhKU9ayU62rwczFyaUX0mt/FreeBMD-search-form-prototype?node-id=451%3A0&scaling=scale-down

**Comment by PatReynolds** [comment]
Design signed off: please implement @Vino-S

**Comment by Daniel-silve1ra** [comment]
Closing this ticket because it has been superseded by #232 https://github.com/FreeUKGen/FreeBMD2/issues/232
