### ISSUE TITLE
Search by Surname only

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#115]
Backend task to hook up surname search.

**Comment by Vino-S** [comment]
@PatReynolds and @richpomfret 
I had fixed the 1841 error we were getting while doing a search. Please have a look and also let me know if you face any new errors.

**Comment by PatReynolds** [comment]
Tried searching Alcock from March 1837 (FreeBMD1 would have barred this, quite please that it hasn't!) to  March (some year in the 1840s) and it said there were none.  So I tried cutting down to Yorkshire, but trying a longer time period.  Now 'too many' so I started cutting down years - back to the level of the original 'none' search' and still 'too many'.  Soc closed that window, and tried a new search (Reynolds, December quarter 1961, and got a couple of hundred results, including the one I knew should be there).

**Comment by Captainkirkdawson** [comment]
Surname search: 
1) enter a name only without selecting dates and record type gives no results. It should have used a default of all record types and dates of 1837 and the maximum
2) enter a name without selecting dates but with a record type gives no results. It should have used a default  dates of 1837 and the maximum
3) enter a name only with dates and no record type gives results. In this case it used all record types without it being selected ie it used a default record type. Results correctly bounded
4) enter a name with dates and record type of birth gives results.  Results correctly bounded BUT it incorrectly reports the search parameter of record type was ALL
![incorrect search parameter report.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/4030cd32-4891-42fe-a9d2-8b911ca6655d)
5) revise search does not carry back record type selection. Date range and surname OK
6) revise search does not carry back districts for county selected
7) adding a forename to the surname works as 1-6 above
8) Districts are not presented alphabetically when county selected
9) Results are not in date order
10) Need record type not 1 or 2  or 3 in results
11) Need quarter name not 1 or 2  or 3 in results
12)Selecting by district works. But it does not report a district as having been selected
13) place should be replaced by county on search page
![county.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/75c4f6e6-9a46-416b-a46d-8ab2a6e06b74)
14) place should be replaced by district  in search page
![district.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5e1f1fd4-3008-428f-a1b2-0b8569795e23)
15) County and district info buttons use forename info
16) all other info buttons except forename are empty
PS Regardless of the foregoing a great first implementation @Vino-S

**Comment by Vino-S** [comment]
Thanks Kirk.
Fixed 1st and 2nd.
Sorted Districts alphabetically
Not yet worked on Search Results page. 
Info icons needs fixing. Missed that

**Comment by richpomfret** [comment]
@Vino-S did you manage to complete the issues Kirk flagged? If so, please do comment and add to 'review' or 'test'.

**Comment by Vino-S** [comment]
The issues in search results page needs fixing: incorrect search parameters

**Comment by PatReynolds** [comment]
Error: https://test2.freebmd.org.uk/search_queries/5e148196e937901cca8b8e81?locale=en
when searching Alcock from March 1837 to March 1840, Nottinghamshire and Lincolnshire (realise now it says 'one' and I was assuming it would be multiple places, as in FreeCEN/REG.

Works fine with just one place selected.

Tried Alcock, birth, March 1840 to June 1963, mothers maiden name COLE, error "Mysql2::Error: Unknown column 'BestGuessMarriages.Volume' in 'on clause': SELECT `BestGuess`.* FROM `BestGuess` inner join BestGuessMarriages as b on b.volume=BestGuessMarriages.Volume and b.page=BestGuessMarriages.page and b.RecordTypeID!= BestGuessMarriages.RecordTypeID and b.QuarterNumber=BestGuessMarriages.QuarterNumber WHERE `BestGuess`.`Surname` = 'Alcock' AND `BestGuess`.`RecordTypeID` = 1 AND (`BestGuess`.`QuarterNumber` BETWEEN 5 AND 506) LIMIT 500"

Changed end quarter to June 1940  but got error Mysql2::Error: Unknown column 'BestGuessMarriages.Volume' in 'on clause': SELECT `BestGuess`.* FROM `BestGuess` inner join BestGuessMarriages as b on b.volume=BestGuessMarriages.Volume and b.page=BestGuessMarriages.page and b.RecordTypeID!= BestGuessMarriages.RecordTypeID and b.QuarterNumber=BestGuessMarriages.QuarterNumber WHERE `BestGuess`.`Surname` = 'Alcock' AND `BestGuess`.`RecordTypeID` = 1 AND (`BestGuess`.`QuarterNumber` BETWEEN 5 AND 414) LIMIT 500

**Comment by Vino-S** [comment]
fixed the error

**Comment by PatReynolds** [comment]
Working fine now, thank you.

![image](https://user-images.githubusercontent.com/6338822/72142484-b3035700-338c-11ea-966c-1364762ccc16.png)

![image](https://user-images.githubusercontent.com/6338822/72142606-f65dc580-338c-11ea-84a1-7fe1e5f8950b.png)
