### ISSUE TITLE
Search of birth and marriage records by Spouse/Mother’s surname

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#117]
Backend work to hook up search of birth and marriage records by Spouse/Mother's surname.

**Comment by Captainkirkdawson** [comment]
Adding spouse surname to search crashed the system see # 186
![cranness spousal surname.JPG](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/19597d30-a84e-4eac-89bd-10fec6afe676)
Should have returned a nil result

**Comment by Captainkirkdawson** [comment]
Search by including a mothers forename is ignored

**Comment by PatReynolds** [comment]
Forename opens, but does not permit entry (works on revise search).

**Comment by PatReynolds** [comment]
Failed to find Harry Dent marrying Agnes (https://www.freebmd.org.uk/cgi/information.pl?cite=Dxa2tboU7nDAAyIjTRVSEw&scan=1 found on FreeBMD1).

**Comment by Vino-S** [comment]
Hi Pat, 
FreeBMD1 live website database is different from test website, so it could be possible that records exists in production db but not in test database

**Comment by PatReynolds** [comment]
Now have found a marriage by spouse first name, so can confirm that works.

**Comment by Vino-S** [comment]
Thank you
