### ISSUE TITLE
Search only by Counties/Districts

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#119]
Backend task for adding in search only by Counties/Districts/ place.

**Comment by richpomfret** [comment]
Ready for testing on TEST2

**Comment by DeniseColbert** [comment]
County search 1917 - 1921, just births, no names returned a 'Too many results' message, as expected. Adding in a district returned a 'No results found' message which would not be expected:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/b5d21e5f-c84e-4915-94e5-9389e1995c88)

**Comment by DeniseColbert** [comment]
Actually, I think the search isn't working as I'm getting no results on any searches.

**Comment by PatReynolds** [comment]
I searched Ampthill, Bedfordshire, September 1839 and it worked as expected.

Births Peterborough September 1979 on FreeBMD1 is 843 entries, zero on FreeBMD2... however, I was searching Peterborough _in Lincolnshire_.  Peterborough in Northamptonshire finds 4.  Peterborough in Huntingdonshire finds none.  

While the set up includes Peterborough in its three counties, Newark is only in Nottinghamshire (should also be in Lincolnshire).

**Comment by Captainkirkdawson** [comment]
Not sure if this was to test a search without names but with county and district. It works as expected if one does but you can only select about 1 years worth of data
