### ISSUE TITLE
Search Death records by Date of Birth/Age at death

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#120]
Backend task for Search Death records by Date of Birth/Age at death.

**Comment by richpomfret** [comment]
@Vino-S how are things going on this one?

**Comment by PatReynolds** [comment]
Search Ralph Alcock, min death age 70 in top box, 100 in bottom gives error: that min age should not exceed max, so put 100 in to and 70 in bottom and got this odd result:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/cfb41d00-8f66-4eda-9688-d40605982d2d)![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/9b45b934-74eb-47a7-98c6-4901202f9cc8)

i

**Comment by PatReynolds** [comment]
Tried dob search for a death.

Errror:

**Extracted source (around line #1227):
1225
1226
1227
1228
1229
1230
              

  def date_array date
    date.split('-')
  end

  def dob_exact_match**

**Comment by Vino-S** [comment]
Hi @PatReynolds , Below is the screenshot for Ralph Alcock  Age Range search. Are these the expected results? The results are ordered by Date
![image](https://user-images.githubusercontent.com/26073943/72100599-cd9ce800-331a-11ea-9293-9c669017a153.png)

**Comment by PatReynolds** [comment]
Thanks Vino, that's the expected result. Also tried a search myself and the search page now works as expected, too.
