### ISSUE TITLE
DT Create Help page for About the GRO

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#128]
Needed for link in red band.

**Comment by PatReynolds** [comment]
@PatReynolds to draft text, including an invitation to order certificates from the GRO.  Nb this is now the bottom PINK band

**Comment by PhilipClarke712** [comment]
Hello Pat, 

This comment of yours dropped into my email box a few hours ago, so I decided to comment.

Looking at the main Help page and the subsiduary pages hanging off it (and the same could be said for the About pages) there seems to a fair amount of close duplication of information (note: there is a distinction to be made between close duplication and the provision of additional information via a hyperlink); and that will need to be addressed fairly soon. So I though it might be useful now to discuss the scope of the new page.

Possibly, the most significant differences between FreeBMD and FreeCEN  /  FreeREG is that events are arranged by Registration District (bound into Volumes), the  (GRO) Page number and Date (Quarter / year) and not by County (event, date, etc). The county-search that is done on FreeBMD(1 & 2) is done by (in a black-box manner") by reverse mapping District / Volume No. onto County. So, there are various pages such as Districts in Counties and Districts-Volumes-Pages to try and explain this. There is another difference: FreeBMD and FreeCEN use centralised data (GRO / Registrar General  / ONS) , whereas FreeREG is local data created at the Parish level.

This is a draft page on test3 covering: Civil Registration Authorities (which has a paragraph on the GRO). and there are more specialised pages on Ordering Certificates and Understanding the GRO Index Page (plus the "Registration District" pages mentioned above).

It seem to me that there are several ways forward: one is to create a new page (as per this Issue) and to use it as a entry point for hyperlinking to these other pages that already exist in FreeBMD(1) and are also on test3 in Draft form. So, I would be interested in what you see as the main scope of this page .

Philip

**Comment by PhilipClarke712** [comment]
This page is now being written, a early draft somewhat incomplete (an understatement) is on test3.

**Comment by PhilipClarke712** [comment]
This is now, perhaps, half-written and I decided to move the draft to the Transcriptions Tab where it fits in with all those other draft pages I mentioned above. Many of these draft pages are called up from both Help pages and Transcriptions pages, so where it/they sits is probably not too important. However, the effect of researching the GRO is producing "ripples" which I may well add to  those draft pages I mentioned above, as well as the draft Transcriptions page which I am also working on. 

County Boroughs and County Councils were created as late as 1888, so the _area_ of a Superintendent Registrar was the _area_ of the Poor Law Union (which did not respect county boundaries), but the GRO outlived the system of the workhouses (they often became hospitals and remained in use till almost now) and so RDs became more and more aligned with local council areas (which also changed over the last 135 years). But, workhouses becoming hospitals will be outside the scope of this page.

**Comment by PatReynolds** [comment]
Hi @PhilipClarke712 that's a great set of pages!  

On the 'Ordering Certifictes' page, I think the bottom section needs to be at the top - it's the "must have" information on this page.

For discussion:

How to order a transcription needs a direct  link from various pages in-page, I think the "Entry Information" page is most important.

Include the essential 'how to order certificates' section in the Help page with a link to the lower section of the 'ordering certificates' page?

Link from the Entry Information Page (location ? Between "Scans" and "Corrections"? or between "Next Record" and "Results"? Or Somewhere else?

It is noted elsewhere that this link is "In the footer" - definitely a good place for it to be, additionally.

**Comment by PhilipClarke712** [comment]
@PatReynolds,

Thanks for your comments. I've moved the "Ordering section(s)" to the top, renamed the previous first section to "Why get a Certificate?" and adjusted the side navigation panel accordingly; and left it at that.

Note: I need to rework some of the hyperlinks - but I'll do that anyway!

I think having done this change: the page needs reworking: I have a subscription to two of the commercial sites; and (if Covid-19 lockdowns were not in place) as an alternative I could go to my local library and use them for free (with a time limit: 55 minutes?). Birmingham for instance has put its parochial marriage records on one of those sites (up to about the 1910s) and the Welsh government makes them available free on a web site. So, should we not mention this (and other marriage records) rather than just sending people off to pay their £11/£12 to the GRO for marriage records, some of which might be commercial available (and the access fees already paid for by "someone" - me or my library) or free in the case of Wales?

**Comment by DeniseColbert** [comment]
Decided that enough is on the website about the GRO so closing
