### ISSUE TITLE
Understand how FreeBMD1 is searched

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#13]
needed by #12

**Comment by DeniseColbert** [comment]
In addition to analytical evidence (have asked Barrie about this on Slack), could design a survey?

**Comment by DeniseColbert** [comment]
https://docs.google.com/forms/d/1EwLq-kL0ayd2tc0VHjsMU7kBwFZ46GsDKExx85tG60g/edit

**Comment by richpomfret** [comment]
Now live.

**Comment by richpomfret** [comment]
Let's add this to the FreeBMD homepage too.

**Comment by richpomfret** [comment]
@PatReynolds  we will need to create a mock-up for the change we would like on the homepage and the one line copy that will go alongside the link. Task has been added to TRAC (#656).

**Comment by richpomfret** [comment]
Currently on hold until it has been reviewed/revised following feedback.

**Comment by richpomfret** [comment]
Review what data we currently have and whether it is useful or not.

**Comment by richpomfret** [comment]
New volunteer to potentially help out with this.

**Comment by PatReynolds** [comment]
@richpomfret to find the files for Sobia to work on

**Comment by DeniseColbert** [comment]
Sobia is now unable to begin until June. @avielbassalian-freeukgen has begun analysis for field combinations / frequency of use. More can be extracted.

**Comment by richpomfret** [comment]
Added @avielbassalian-freeukgen as he has managed to extract some bits from the JSON file provided by Barrie.

**Comment by richpomfret** [comment]
INterviews as next steps here (this will become a parent /epic).

**Comment by richpomfret** [comment]
I will introduce you (Aviel) to Barrie re: new JSON file.

**Comment by richpomfret** [comment]
Do we need a new survey or use the previous survey to add onto the old FreeBMD1 site? @neslihanu and @avielbassalian-freeukgen to take a look.

**Comment by richpomfret** [comment]
This could be a good way of collecting info on the search results page and how best to show information.
