### ISSUE TITLE
Create/Design  "Entry correction" page 

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#130]
Create/Design  "Entry correction" page  for FreeBMD2.

Please check below link;
https://www.freebmd.org.uk/cgi/corrections.pl?r=148453575&d=bmd_1564415191

**Comment by KatyMawhood** [comment]
@PatReynolds What's the status on this?

**Comment by KatyMawhood** [comment]
Same as [#131 ](url) – @PatReynolds The link (above) is no longer working. Do you have an example of this page? Am I right in thinking it should be linked to each detail?

**Comment by richpomfret** [comment]
@DeniseColbert to review and see if we still need this (or if it can be part of the report a data problem accordion). Speak to corrections on BMD1 and see what they think.

**Comment by PatReynolds** [comment]
@PatReynolds to send's Allan's response to @DeniseColbert

**Comment by DeniseColbert** [comment]
The 'Report an Error' page covers this. Closing
