### ISSUE TITLE
Create a page for donations:  https://www.freebmd.org.uk/donations.shtml

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#136]

**Comment by PatReynolds** [comment]
@neslihanu - the donations button needs to link to https://www.freeukgenealogy.org.uk/help-us-keep-history-free/

**Comment by PatReynolds** [comment]
Button now links to correct page on www.freeukgenealogy.org.uk.

Creating individual project pages is a future  release for all projects.  See systemwide #68
