### ISSUE TITLE
DT Create a page: https://www.freebmd.org.uk/Certificates.html 

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#137]

**Comment by KatyMawhood** [comment]
@PatReynolds What's the status on this?

**Comment by PhilipClarke712** [comment]
I added a page currently called "Ordering Certificates" and 1st-stage-html-mark-up to the shared folder Documents (in Progress) in early May. It is awaiting resolution of how the BMD2 pages should "look" like.

**Comment by ComfE-2662** [comment]
@PatReynolds What needs to be done here?

**Comment by PhilipClarke712** [comment]
I put the page through Refinery on test3 sometime ago. So, it might have a few "rough edges" and un-made hyperlinks to other pages that are also draft-pages, but I am going through all of those files and cleaning them up, where needed. This issue could be closed be either accepting what is there, or by reviewing the page and deciding whether it can be closed, or not.

**Comment by PatReynolds** [comment]
Could you review the page, please @ComfE-2662

**Comment by PatReynolds** [comment]
Checked and fine to go ahead, so closing.
