### ISSUE TITLE
Add existing user IDs to FreeBMD2 (mongodb) so that they are not taken by new transcribers

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#147]

**Comment by Captainkirkdawson** [comment]
Need to add BMD1 syndicates first

**Comment by Vino-S** [comment]
ready to be tested on test2

**Comment by richpomfret** [comment]
@DeniseColbert to take a look.

**Comment by DeniseColbert** [comment]
Tested and working:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/9eb15b0e-1509-4cd1-b834-9d638b26bd5e)

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
