### ISSUE TITLE
Highlight that FreeBMD2 is a Beta Testing site

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#148]
No link to feedback form on the home/search page (that is at bottom of Search Results) but users should be aware that this is only a Beta site - stuff they hate may well get changed, if feedback is given to that effect.

**Comment by richpomfret** [comment]
@neslihanu any ideas for how we might do this? We have discussed adding in a 'beta' to the logo, but probably need a bit more than this alone.

**Comment by neslihanu** [comment]
I've checked the best practices, I would recommend below points;

1. Mention "Beta" on the logo
2. A pop up info box
3. A temporary info text on the Web page

**Comment by richpomfret** [comment]
We will be using a 'beta' url - however, let's also mention beta in the logo.

**Comment by richpomfret** [comment]
@DeniseColbert to mock-up bmd1 style 'stamp' for 'beta' on the site logo.

**Comment by richpomfret** [comment]
@AlOneill to provide accessible red for this.

**Comment by AlOneill** [comment]
@DeniseColbert Our accessible red is `#DB0000`

**Comment by DeniseColbert** [comment]
Image: https://drive.google.com/file/d/12FA3NAo20ka2weduHD9jH5sUgtrOr-PA/view?usp=sharing

![BETA (2)](https://user-images.githubusercontent.com/19173257/129771404-56826f96-a53c-473e-9b2d-ecf170e4c131.png)

**Comment by PatReynolds** [comment]
Thanks, @DeniseColbert that looks wonderful!!!

**Comment by PatReynolds** [comment]
@Vino-S please place above the FreeBMD logo - to the left of the advert slot.

**Comment by richpomfret** [comment]
Tested during the meeting - looks good - IF it is a quick change, could we move it along a bit to the right so top-left corner is in-line with the F in the logo. @Denise to add in mock-up.

**Comment by DeniseColbert** [comment]
![sandbox](https://user-images.githubusercontent.com/19173257/136823994-f463dff2-e548-4162-b00a-31dd18924795.png)

I think perhaps it's better to have the bottom-left corner is in line with the F of the logo

**Comment by richpomfret** [comment]
@Vino-S to update.

**Comment by DeniseColbert** [comment]
The image seems to have vanished from beta @Vino-S

**Comment by Vino-S** [comment]
Implemented and ready to test in test3

**Comment by richpomfret** [comment]
Looks good. Although now appears to be a slight grey line visible to the right of the logo and under where the advert goes. To investigate.

**Comment by PatReynolds** [comment]
Tested by Denise - story complete.
