### ISSUE TITLE
Ask FB1 researchers for wishlist of improvements

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#15]
a) ask in newsletter, etc.
b) ask on FreeBMD1

**Comment by DeniseColbert** [comment]
Send to mailing list first, then refine based on responses

**Comment by DeniseColbert** [comment]
https://docs.google.com/forms/d/1EwLq-kL0ayd2tc0VHjsMU7kBwFZ46GsDKExx85tG60g/edit

**Comment by richpomfret** [comment]
Send first to the coords list, then the main mailing list.

**Comment by richpomfret** [comment]
Pat has sent the email. @DeniseColbert to revise (post suggestion) and sending it through to the coords ahead of wider distribution.

**Comment by DeniseColbert** [comment]
Made the suggested changes, have asterisked method of communicating backend/transcriber enhancements.
