### ISSUE TITLE
TEST3 not accessible

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#153]
'We're very sorry, but something went wrong'.

https://test3.freebmd.org.uk/

Not currently accessible.

**Comment by richpomfret** [comment]
Apparently it hasn't been set-up yet. @lemon-ukgen can you assist?

**Comment by Captainkirkdawson** [comment]
Issue is with us not lemon; we have not placed any code in the production folder for freebmd2; hence there is nothing to run. What do we want to put there and why and how urgent

**Comment by Captainkirkdawson** [comment]
@PatReynolds @richpomfret @DeniseColbert @AlOneill 
Have activated BMD2 test3. Have activated registration into technical syndicate. Have cleaned out the freereg users from the userids. Have cleaned out the refinery pages of FreeREG pages. Only current members are myself, vino, pat and richard.
I suggest that all members of the current and future documentation team who need to work on refinery register and work on BMD test3

**Comment by PatReynolds** [comment]
Hi @Captainkirkdawson thanks for this.  Having first work on documentation done on test3 makes sense.  I just tried going into test3.freebmd.org.uk Got an error (screen says it was logged).

**Comment by Captainkirkdawson** [comment]
@PatReynolds I broke the first law of programming. I did not test a late day code change. Fixed a spelling error. test3 is running now

**Comment by PatReynolds** [comment]
Just tested sign up, and works fine.  One thing: do we need to de-mandate the Transcribers Agreement, as some volunteers may not want to do that (or perhaps more simply, say we'll reset this to not-subscribed manually)?

**Comment by AlOneill** [comment]
@Captainkirkdawson Oh no — not my day. Was told registration was successful and got email but on changing password got told that "Reset password token is invalid".

BTW, two observations: success message is magenta, so looks like a link (suggest teal or green — both in our CSS); message appears way down the page and would be easy to miss.

**Comment by Captainkirkdawson** [comment]
@AlOneill sorry that was my mistake; I changed your role on seeing your registration. Doing that invalidated the token. Have sent you another

WRT rest of message I am at a loss as to what, where and when these comments apply

**Comment by AlOneill** [comment]
@Captainkirkdawson TY. Have now set password successfully.

My comments apply to the refreshed Transcriber Registration page that appears on submission of form.

**Comment by Captainkirkdawson** [comment]
@AlOneill could that be raised please in the registration story whichever that should be 110 144 or 145. In this story all I have done is to make a production test version for people to use and to make sure that it works (clearly I failed initially). I will do nothing with it on this story and it does not affect this story.

**Comment by AlOneill** [comment]
Fair point — thought I would mention before I forgot: not a screen one sees often!

Raised issues in #144

**Comment by DeniseColbert** [comment]
Success; however, no Refinery button:

![image](https://user-images.githubusercontent.com/19173257/74156178-bd27a800-4c0d-11ea-80c0-b292bb5a2ead.png)

**Comment by Captainkirkdawson** [comment]
That is because all registration is as transcriber. I have to change your role and have done so.
