### ISSUE TITLE
Reduce the scrolling required in 'Date range' year drop-down boxes.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#156]
Perhaps 'Date range to' year box mirrors year entered in 'Date range from' year box? Or something else.

**Comment by AlOneill** [comment]
Note that it is possible to get to the year by typing in the year fields — a user does not have to scroll.

**Comment by DeniseColbert** [comment]
@Vino-S will look into changing to free text field (with validation) and compare to suggestion in description above.

**Comment by DeniseColbert** [comment]
How can we let people know that they can type in these fields?

**Comment by DeniseColbert** [comment]
Addressing the issue in description: make "To" field the same as "From" field and have quarter default to final quarter of the year.

**Comment by KristinaGadzhieva** [comment]
@DeniseColbert could you please have a look and test on test3?

**Comment by KristinaGadzhieva** [comment]
@Vino-S ready to be deployed
