### ISSUE TITLE
Github icon in footer points to https://github.com/FreeUKGen

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#162]
Currently the Github icon links to https://github.com/FreeUKGen/MyopicVicar/ but it should either point to https://github.com/FreeUKGen or https://github.com/FreeUKGen/FreeBMD2

**Comment by DeniseColbert** [comment]
Reopening as not fixed

**Comment by PatReynolds** [comment]
@Vino-S please point it to https://github.com/FreeUKGen/FreeBMD2

**Comment by PatReynolds** [comment]
Now to be resolved as part of story #155, or after that is completed.

**Comment by Vino-S** [comment]
Ready to bested on test2

**Comment by richpomfret** [comment]
Tested - working as expected.

**Comment by Vino-S** [comment]
Deployed to test3. So Closing it
