### ISSUE TITLE
Information (i) icons require text

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#163]
All icons need text adding. Example of icons in question:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/cdf215c5-8755-41d1-b7bb-5af7fde35f29)

**Comment by PatReynolds** [comment]
Note from meetig 13/1/2020 - should include hyperlink to search help page (use tags).

**Comment by PatReynolds** [comment]
As tool tips removed, suggest closing.

**Comment by PatReynolds** [comment]
Agr3eed - we should close, so closing.
