### ISSUE TITLE
Logo vanishes when changing browser size

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#166]
At a specific size the logo vanishes - need to ensure everything stacks effectively when changing resolution/size.

**Comment by richpomfret** [comment]
Does that mean this has been fixed or resolved somehow? Do please include a
comment where possible prior to closing (especially for those of us who
couldn't attend the meeting).

**Comment by PatReynolds** [comment]
Ah, yes, that' would have been helpful: closed on FreeBMD2 as story is on Systemwide.
