### ISSUE TITLE
Add timer/spinner to Search page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#184]

**Comment by Vino-S** [comment]
ready for testing

**Comment by PatReynolds** [comment]
Tested and working fine, thank you.

**Comment by richpomfret** [comment]
@Vino-S do we have TEST3 up to date yet and if so, is this change on there?

**Comment by Vino-S** [comment]
updated to test3

**Comment by Vino-S** [comment]
Deployed to test3. So Closing it
