### ISSUE TITLE
Add sample marriage records to test records for FreeBMD2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#187]

**Comment by Vino-S** [comment]
Current Database that we use in our test system for BMD has no records in BestGuessMarriage table. The table is used for Marriage search.
I prefer switching to other available databases instead of sampling in a order to do a complete testing.

**Comment by Captainkirkdawson** [comment]
Agree entirely @Vino-S

**Comment by PatReynolds** [comment]
Hi @Vino-S is there a new story for the other available databases/ taking this forwards?  If one's needed, please create it.  Then please close this issue.

**Comment by Vino-S** [comment]
database changed. So closing it
