### ISSUE TITLE
Make links between the info buttons and help using "more help" and `id`s

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#189]
Some help is too long to fit into an info - see for example Vino's explanation on spouses' names on #185.

A link to this kind of information is needed.  

Original question "New page or same page implimentation?" suggests "new page" has been adopted (help page or a subpage of help).

How should the user get to this additional help?
a hyperlink 'opens in new page' from the bubble?
a hyperlink (does not open in new page) from the bubble? A 'more help' button under the field (or somewhere)?  Will more help open in a new page?  Or  not?  Or will the current page have an expansion slot (sorry, don't know the correct term) where the additional information will appear?
Other solutions are probably available.

**Comment by KristinaGadzhieva** [comment]
Not relevant for MVP scope now. Info buttons have been removed.
