### ISSUE TITLE
Statistics in the footer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#190]
For decision: do we add ....
X searches were performed on Y records (Z births, A marriages and B deaths)
C records (D births, E marriages and F deaths) were added in the latest update.

Do we want to add in 'latest year being transcribed' for these? Anything else?

Suggest link to a refinery page called statistics which has links as in https://www.freebmd.org.uk/iindex.shtml

Text on copyright on story #66

**Comment by PatReynolds** [comment]
Can be discussed in light of Systemwide#98 
Edit 22/4/2020 - review systemwide not impinging on FreeBMD2 development.

**Comment by PatReynolds** [comment]
Page noted above for links is now #Records tab - so not needed in footer - or does footer say 'for more information use the Records button above'?

**Comment by richpomfret** [comment]
To discuss implementation of this link across projects (on systemwide).

**Comment by richpomfret** [comment]
Discussed and agreed to proceed.

**Comment by richpomfret** [comment]
@richpomfret to check over on systemwide and assess whether this is ready to be implemented here or not..

**Comment by richpomfret** [comment]
We are close to being ready for implementation - @jayto581 is rebuilding his dev environment at the moment and will then make a few updates prior to implementation.

**Comment by richpomfret** [comment]
Awaiting pull request to be merged prior to testing.

**Comment by Vino-S** [comment]
Ready for testing in test2

**Comment by richpomfret** [comment]
@richpomfret to take a look and test.
