### ISSUE TITLE
About this Query Page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#192]

**Comment by PatReynolds** [comment]
About this query page says filtering applied to death:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/aa59825d-8c34-4af7-97f4-bf508e288293)

No death records were found, only birth and marriage)

that filter was on a previous  (death only) search.  revising the search to death only. at this oint, no date of birth had been saved, and the search found one death (which had been filtered out on the original geath query and the sunsequent all searcges.

Is this expected?

**Comment by Vino-S** [comment]
ready to test

**Comment by PatReynolds** [comment]
About this Query now says "Birth Date range or Age: Start Year is 1891. End Year is 1928." on a search run on all record types.  Perhaps use 'Date range of Age' for all search queries?
"

**Comment by richpomfret** [comment]
@Vino-S is it clear what change is needed here?

**Comment by Vino-S** [comment]
Apologies @PatReynolds  @richpomfret , I am unable to replicate the issue in my local.  Can I have an example search criteria please, so that I could dig deeper. Thank You

**Comment by PatReynolds** [comment]
@Vino-S please change the Chapman code to County Name and the district number to the district name - otherwise functioning as expected.

**Comment by Vino-S** [comment]
Ready for testing

**Comment by richpomfret** [comment]
@PatReynolds to test it out.

**Comment by PatReynolds** [comment]
Yes, this is now working as expected, thank you.

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
