### ISSUE TITLE
Do Researchers need access to Newsletter sign-up information?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#195]
If so, sign up to groups.io needs to be added to the About page.

**Comment by DeniseColbert** [comment]
FreeBMD newsletters? No- researchers don't need access. 
We should be inviting them to sign up to the FreeUKGEN newsletters though. See Systemwide #14

**Comment by PatReynolds** [comment]
On systemwide, so closing
