### ISSUE TITLE
wildcard search

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#198]

**Comment by Vino-S** [comment]
Implemented wildcard search in surname, firstname and spouse/mother surname. needs testing

Working on implementing wildcard search in spouse firstname

**Comment by richpomfret** [comment]
@PatReynolds to take a look.

**Comment by PatReynolds** [comment]
*Joshua in first name fails as "two characters must precede wildcard".
However, +Joshua works.

Surname searches work as expected, thank you.

**Comment by Vino-S** [comment]
Fixed and ready for testing

**Comment by PatReynolds** [comment]
A search for *eph SMITH, Daventry, March 1840 to Dec 1842 fails to find any records, but Joseph SMITH finds four.
I'n not sure if this is what is expected (it is the same as on FreeBMD1).

**Comment by Vino-S** [comment]
@PatReynolds 
an asterick as first character in a First Name(s) will do a search on second Given Name. So we can say that here an asterick is simply a flag to do a search on second given name.
your search as an example:
 First Name(s): *eph SMITH

 Here it will look for all the entries where second is `eph SMITH`. However we might not have any in out database. So you have no results. 

However `*Smith` will give all the results where second given name is Smith. 
Example **_john smith, joseph smith, william smith_**

**Comment by PatReynolds** [comment]
Thanks, @Vino-S 
Search for * Clark DENT in Brixworth (all types, all dates) finds nothing in FreeBMD2, several in freebmd1 (with no restriction on district)
![image](https://user-images.githubusercontent.com/6338822/77163763-b579df80-6aa6-11ea-852f-6a6d1c4569bf.png)
NB finds second names _starting 'Clark', not just 'Clark'.

For discussion: do we want FreeBMD2 to match FreeBMD1 in functionality (i.e. no specific district is needed)?
Is the workding place/district in the help clear? (would 'District' be better)?

**Comment by Vino-S** [comment]
You are right @PatReynolds , my code did an exact match on second name. Made the changes in  code. Now should be working as in BMd1

**Comment by Vino-S** [comment]
I had also removed the district/place restriction for Second GivenName search as I thought second GivenName search should be similar to FirstName search.

Wildcard implementation in detail:
Similar to BMD1
1.  `*` :  matches any number of characters. Must be preceded by  two letters.
         Exception:  An ***** can be used as first character in FirstName but not as wildcard instead as a flag to specify search is based on Second GivenName. 
                             Example: *****doe will find **_John Doe and Jane Doe but not John Jane Doe_**
                              if `**`(double astericks) precedes FirstName it will searches a name name anywhere from the 
          second GivenName.
                              Example: `**doe `will find **_John Doe, Jane Doe and John Jane Doe_**
2. # : If a field is preceded  by `#` the search is done on the characters exactly as they follow the `#`( wildcard function is overlooked). Example: `#?` on LastName will return all results where LastName is `?`

3. ? : Matches exactly one character. Example: `Vin?` will find **_Vino, Vini but not Vinodhini_**

Wildcards facility is available in all names except Spouse GivenName
All restrictions for Wildcard Search from MultiModal code still applies.

**Comment by Captainkirkdawson** [comment]
Well done @Vino-S 
In my mind while it works few researchers would ever understand the nuances of the various option.

**Comment by PatReynolds** [comment]
Developer work completed, and help drafted (to be part of the Search Help section), so this can be closed.
