### ISSUE TITLE
Date is showing in detailed results as a number and year, e.g. 2 1840 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#202]
We could use A/M/J 1840, or June 1840

**Comment by Vino-S** [comment]
Implemented. can be closed

**Comment by DeniseColbert** [comment]
Taylor to test on Test2

**Comment by taylorjgolden** [comment]
> 
> 
> Taylor to test on Test2

Date shows up as DECEMBER 1862 for the record I chose, as desired

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
