### ISSUE TITLE
Recruit new UX/design volunteer

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#208]
I have made comments/suggested changes on the role description (the previous version is there as 'version 1', to reflect the changes in the type of work now needed (i.e. more user testing, fewer/no mock ups). @DeniseColbert and @richpomfret to review.

**Comment by PatReynolds** [comment]
Reopen advert on Work in Startups.

Anywhere else? Reach - @DeniseColbert to search and suggest.

**Comment by DeniseColbert** [comment]
Emailed Pat & Rich 12/2/20 with details of a volunteer.
