### ISSUE TITLE
DT Create a 'Your Reviews' page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#210]
- [x] Create page with reviews and form
- [x] Signed-off and made live, added to About page

See systemwide #134 "Implement **Your Reviews** across all three projects

**Comment by PatReynolds** [comment]
Page created - but needs checking against standards for html  and new reviews adding

**Comment by PatReynolds** [comment]
I have added a few new messages to the draft page.

I still need to search for ones mentioning "afford"

**Comment by PatReynolds** [comment]
@PatReynolds to look at Facebook

**Comment by PatReynolds** [comment]
Facebook "reviews" added.

**Comment by PatReynolds** [comment]
@ComfE-2662 could you ask the team to review?

**Comment by richpomfret** [comment]
Now on @DeniseColbert and @taylorjgolden.

**Comment by DeniseColbert** [comment]
@taylorjgolden could you take a look at the page on Refinery just to get a feel for how it looks now and how we might go forward with the form.

**Comment by PatReynolds** [comment]
"If you would like to tell our hard working volunteers what you really like about FreeBMD, fyou can show your appreciation here ... if you have found something that needs improving, please let us know [link]"

**Comment by DeniseColbert** [comment]
[This page](https://test3.freebmd.org.uk/cms/archive/draft-your-reviews-earlier-version) is populated with FreeREG reviews- could we delete this page in favour of titivating [this one](https://test3.freebmd.org.uk/cms/archive/reviews)?

**Comment by DeniseColbert** [comment]
Have updated and added the form. @AlOneill could you work your magic and make it in line with the FreeREG page, please?

**Comment by AlOneill** [comment]
@DeniseColbert I've added DRAFT to the page name and moved it into About: you can view it here:
https://test3.freebmd.org.uk/cms/about/draft-your-reviews

I'll be working on it offline for a while, so the usual caveats apply.

**Comment by AlOneill** [comment]
@DeniseColbert Draft page now has block-quote markup, styled as per the equivalent page on REG.

Please review content and presentation. Will provide a link from 'About' once content has 'final' sign-off from you or @Pat.

**Comment by DeniseColbert** [comment]
@AlOneill to change blockquote colours to magenta and @DeniseColbert to add length to form, then it can be signed off.

**Comment by AlOneill** [comment]
Block-quote accent colour updated to magenta.

**Comment by DeniseColbert** [comment]
Length added to form. Ready to be linked to from About. Thanks @AlOneill

**Comment by AlOneill** [comment]
Link added to 'Your reviews' from 'About'.
Pages are sync-ready.

**Comment by AlOneill** [comment]
Has **not been synced** yet to beta

**Comment by DeniseColbert** [comment]
@Vino-S

**Comment by DeniseColbert** [comment]
Content should be on beta - Denise to test

**Comment by DeniseColbert** [comment]
Page is there, all good so closing
