### ISSUE TITLE
Submit a report takes you to https://test2.freebmd.org.uk/cms/refinery/pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#212]
Report a problem, form is filled in, pressing 'submit' takes you to refinery.

Does the report get sent?

Needs to do what happens in the other projects

**Comment by DeniseColbert** [comment]
Denise to test on test 3

**Comment by DeniseColbert** [comment]
Submit feedback behaved as expected and the reoprt is in Feedbacks in Test3. I think we can close this.
