### ISSUE TITLE
Enable search death by date of birth with partial date (possibly?)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#213]
Researcher  may not have exact/correct dates of birth (e.g. pre-registration taken from baptism rather than registration of birth) or just be lazy and can remember the year but don't want to go and look up the precise date.  Search only seems to work if you put a complete date in (same for both single date of birth, and for a birth range) and on FreeBMD1, you ONLY put a year in (and a quarter for range). 

FreeBMD1 is slightly harder to use in range (you would need to know how to convert a conventional date to a quarter), but overall easier in terms of keystrokes.

**Comment by richpomfret** [comment]
Let's emulate current BMD1 functionality for MVP and anything else comes post-MVP.

**Comment by PatReynolds** [comment]
@PatReynolds  to amend help to reflect functionality (i.e. just year is fine in the date).

**Comment by PatReynolds** [comment]
Help page does not currently mention how to use the (new) search page.  Suggest returning to backlog until after first draft of Help for FreeBMD2.

**Comment by PatReynolds** [comment]
Added to pages needing moving spreadsheet

**Comment by ComfE-2662** [comment]
I think I'll need a link to find what you are referring to

**Comment by PatReynolds** [comment]
I think #225 replaces this - so moving to Needs Review with a view to closing.
