### ISSUE TITLE
Implement Entry Information (was Decide title for "Detailed Results" page)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#216]
Barrie notes: "Detailed results page" but my point was that the name was appropriate for those projects but not for FreeBMD. One could have a debate about balancing consistency against meaningfulness, but that is a debate that is lacking.W Barrie suggests "Information".  Currently FreeBMD1 has "Entry Information".

**Comment by KatyMawhood** [comment]
@PatReynolds What's the current status on this?

**Comment by PatReynolds** [comment]
No decision yet.  'Detailed Results' may not be right for FreeBMD - UX to test if this builds expeection of more details being following the link / disappointment when it is more properly 'More information about this entry'.

**Comment by richpomfret** [comment]
Original BMD says 'Info' and then 'click for more information' and then title is 'entry information'. Agreed to go with that as MVP.

**Comment by PatReynolds** [comment]
@Vino-S to implement @PatReynolds  to check that all references are changed in documentaiton

**Comment by PatReynolds** [comment]
The help page needs a thorough re-write which will pick this up, so have added to 'Help page for MVP' epic.

**Comment by richpomfret** [comment]
Closing as now a duplicate.
