### ISSUE TITLE
Implement mobile search page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#219]

**Comment by DeniseColbert** [comment]
Vino is tinkering with a floating search button to accommodate ad at bottom of screen. She will implement the clear form function on hover so we can feed back.

**Comment by richpomfret** [comment]
To review in next meeting - currently on TEST3 if anyone wishes to review ahead of then.

**Comment by richpomfret** [comment]
@Vino-S to update/'fix' the hamburger option menu and implement as per FR/FC.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richpomfret** [comment]
@richpomfret to take a look.

**Comment by richpomfret** [comment]
@DeniseColbert had issue with menu not functioning correctly when testing (test3) on her Samsung device.

**Comment by richpomfret** [comment]
Issue also replicated on LG handset.
![Capture+_2021-10-25-16-52-01](https://user-images.githubusercontent.com/22348254/138729339-621414a7-e30e-4a98-bf89-2188902a0cd2.png)

**Comment by richpomfret** [comment]
@Vino-S note the small 'beta' logo also. Had a slightly different issue on ipad where the hamburger icon appeared but the options then appeared to the right and top options not visible/appears buggy if functional.

**Comment by DeniseColbert** [comment]
@richpomfret could you re-test please?

**Comment by richpomfret** [comment]
All now working as expected. :)
