### ISSUE TITLE
Implement mobile search results page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#220]

**Comment by PatReynolds** [comment]
Works well on Pixel XL and MotoG4, on chrome and duckduckgo

**Comment by DeniseColbert** [comment]
@richpomfret could you test on iPhone please?

**Comment by richpomfret** [comment]
Tested on ipad air 4 and unexpected results when sorting by year across multiple pages. Initially sorts by year with oldest first, but on page 2 it then sorts by year with newest first. 

I would expect the sort to remain consistent across multiple pages.

**Comment by richpomfret** [comment]
Working fine now for the most part in terms of mobile search - issue above with Sort is not mobile specific, so will close this story now and create separate stories for anything mobile specific.
