### ISSUE TITLE
Enable "Message of the Day"

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#224]
- [x]  Define which pages are to have Message of the Day
-  [ ] implement message of the day and message for members
- [ ] document usage for those who need access, and grant them necessary permissions

**Comment by PatReynolds** [comment]
Put link in any page that needs a Message of the Day to a refinery page.

**Comment by PatReynolds** [comment]
I suggest:
a) Homepage, below banner, above title, only to take space when needed. (Refinery Information page, as on FreeREG)
b) member's landing page (https://www.freebmd.org.uk/manage_resources/new?locale=en  (Refinery Information for members page, as on FreeREG).

**Comment by PatReynolds** [comment]
@Vino-S  to implement the message on home page,
@PatReynolds to create the message for members in refinery

**Comment by Vino-S** [comment]
@Vino-S to update the story once code move to vervet

**Comment by Vino-S** [comment]
Can be tested on test2

**Comment by PatReynolds** [comment]
Thank you, @Vino-S  working as expected.  Marked as Ready for Deployment.

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
