### ISSUE TITLE
Search date of birth (in death searches) by different method

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#225]
Suggestion is to search just by year, typed in by user, as in freeBMD1

**Comment by Vino-S** [comment]
In the current implementation we can still type in the date

**Comment by richpomfret** [comment]
@Vino-S  does this mean we can do both?

**Comment by richpomfret** [comment]
@PatReynolds to test and close if appropriate.

**Comment by PatReynolds** [comment]
The search seems to give a good margin of error (e.g. if I say someone died 14 Jan 1901, it looks for a year or so either side).  In which case ... why are we asking for month and day?  It is very difficult and time consuming - and sometimes one is only checking and knows it is March quarter 1901. 
Or do we want a 'precise' option (choose exact date) a 'approximate' option (how a single date is currently searched) and a 'range' option (1//1/first year to 31/12/lastyear)?

**Comment by PatReynolds** [comment]
Personally, think we should go with year only, and approximate as at present for MVP, and await feedback on how good/bad this is for users.

**Comment by PatReynolds** [comment]
@Vino-S to try to implement whole year only searches.

**Comment by Vino-S** [comment]
minor changes needed in code so still in progress

**Comment by Vino-S** [comment]
ready to be tested in test2

**Comment by PatReynolds** [comment]
@PatReynolds to test

**Comment by richpomfret** [comment]
@PatReynolds to take a look.

**Comment by PatReynolds** [comment]
Dropdown on age at death / date of birth is not working.   @Vino-S could you take a look?

**Comment by PatReynolds** [comment]
Working as expected, thank you.

**Comment by Vino-S** [comment]
Deployed to test3. So Closing it
