### ISSUE TITLE
Wireframes for search experience

### ISSUE THREAD

**Issue by Daniel-silve1ra** [FreeUKGen/FreeBMD2#232]
### **Wireframes for search experience**
For this ticket to be considered done this checklist must be complete

**Wireframe for search parameters page**

- [x] 1st wireframes done
- [x] Design critiqued by UXers
- [x] Design iterated based on critique
- [x] Design critiqued by team/stakeholders

**Wireframe for results page**

- [x] 1st wireframes done
- [x] Design critiqued by UXers
- [x] Design iterated based on critique
- [x] Design critiqued by team/stakeholders

**Wireframe for detailed results page**

- [x] 1st wireframes done
- [x] Design critiqued by UXers
- [x] Design iterated based on critique
- [x] Design critiqued by team/stakeholders

**Final review and iterations for the search and detailed results pages**

- [x] Comments submitted by Denise and Rich
- [x] Iterations agree 
- [x] Iterations made
- [ ] Iterations reviewed and signed-off

**Comment by Daniel-silve1ra** [comment]
**Video recording of the team design critique**
https://drive.google.com/file/d/1v62tMrk7n6PgJTcFc3wFk3Rx8s8U6tbB/view?usp=sharing

**The wireframes**
https://www.figma.com/file/jtUoOTq6CYnDOuwMWGaZe3/FreeUKBMD2-%C2%B7-Design-critique-of-search-experience-wireframes?node-id=477%3A3772

**Feedback trello board**
https://trello.com/b/SXNgEE7A/design-huddle-search-experience-1

As you'll see from the discussion in the final part of the video, we needed a bit more time to reflect on the designs and it was decided that we'd all continue to place our feedback on the Trello board between now and the next Scrum meeting, where we'll discuss the points raised.

**Comment by Daniel-silve1ra** [comment]
**Feedback from Denise and Rich**
https://docs.google.com/document/d/1YkKU9fFvJJjZK7wo33Odmxz4lKNsJhPkad9kIfEG-iE/edit?usp=sharing

**Comment by Daniel-silve1ra** [comment]
Katy and I have designed the search results and detailed results page. What we've done is based as much as possible on the patterns used by FreeCen, https://test3.freebmd.org.uk/ and https://test2.freebmd.org.uk/. We've done this so that hopefully we can build upon code which we already have and go to production quicker. For example, the table of results in our designs uses the FreeCen table design dimensions, layout etc.

You can view the designs in Figma https://www.figma.com/proto/taWyCA226beA2JoDX0UF4u/Option-2-low-to-high-fidelity?node-id=133%3A257&viewport=577%2C212%2C0.1540028154850006&scaling=scale-down-width

You can make comments on it here https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-low-to-high-fidelity?node-id=3%3A5

![Search results](https://user-images.githubusercontent.com/60981661/83359236-edd44e80-a370-11ea-89cc-d17b095dbe50.png)
![Detailed results](https://user-images.githubusercontent.com/60981661/83359238-f036a880-a370-11ea-8460-7c8c581d90f4.png)
![tools dropdown](https://user-images.githubusercontent.com/60981661/83359240-f0cf3f00-a370-11ea-977f-3b4b052cffc4.png)

**Comment by richpomfret** [comment]
@richpomfret to review/feedback.

**Comment by Daniel-silve1ra** [comment]
> @richpomfret to review/feedback.

here is the link for the wireframes which need reviewing. There is a speech bubble icon in the horizontal tool bar of the interface which you can use to make comments. If you let me know when you've done that I can then look at making iterations. You will need to login to figma to do this

https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-low-to-high-fidelity?node-id=3%3A5

**Comment by PatReynolds** [comment]
Underlying design is great

I agree with note 2.

Could the dro-down tools menu have a dark or mid grey outline to show where it ends and the page behind begins?

Could the link to correction be after the text and say 'I have viewed the scan and wish to submit a correction'?

I think that Postem needs some text before it and again, text with link to follow.

Suggested text: Do you know more about the people or event in this record that you are willing to share with other researchers?  We call these helpful additions to the database 'postems'.  For example,  you you know a more precise place or other details from a certificate or from a search of FreeREG, or more about the family from a search on FreeCEN, or have found other records about them in another country's registration system. Contribute what you know! 

Hyperlinks on FreeREG and FreeCEN and Contribute what you know 

There also needs to be a link somewhere to any postems to this record.  Maybe the lable/link is "User submitted information" Maybe we should just talk about 'user submitted information and drop the term Postem?

**Comment by Daniel-silve1ra** [comment]
I've finished making iterations to the search result designs and completed the pre-production dev specification to guide Vino. 

It is worth noting that these designs still need to be signed-off before production. However, I may not be able to attend the next meeting and I didn't want to delay this any further for the project - which is why I have done the specification already. 

When it comes to using Figma for developer handoff it is always better to view the file as an editor. As we are using the free version of Figma this is limited to Katy and me.

But I've made a generic password for Vino so she can view it as an editor and be able to copy and paste the code I've drafted. - you can't copy and paste stuff from it unless you're signed in as an editor. I don't know whether more than one person can open Figma all at the same time using my username so lets start by only having Vino use it.

@Vinodhini Subbu 
The username for the Figma account is: daniel.silveira@freeukgenealogy.org.uk
The password is: Ilovebmd2

[The dev spec is here](https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-design-to-dev?node-id=225%3A836) - mostly for Vino but feel free to have a look if you're interested.

[The final design iteration without the spec is here](https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-design-to-dev?node-id=231%3A0)  - for everyone to review and eventually be signed-off for development. I have made a couple of iterations based on all your feedback. It is worth noting that instead of having a 'back to results' button I suggest that users will use the 'revise search' button to do this and there is no need to overcrowd the interface - let me know if that is cool @Denise Colbert 

There is a lot of detail and ideally, I'd have a call with Vino to go through it. 

@Vinodhini Subbu once the designs are signed-off can we arrange a phone call to discuss the specification I put together.

I'm excited to hear your feedback and get this in front of users soon 😀

All the best,

Daniel

**Comment by Daniel-silve1ra** [comment]
Hey Pat,

Thanks for the feedback.

I've tried to incorporate the things you've said apart from the stuff about
postem as I'm not sure I understand 100%. But I think if I understand it
correctly that it is more of a content decision rather than a UX one.

Thanks again,

Daniel

**Comment by Daniel-silve1ra** [comment]
Hi all,

About my last email. I was doing some thinking and tinkering and I've found what I think is a really strong reason for not going with those designs. 

**The table**
The main reason for this is the results table. As you can see from the design shown [[here](https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-design-to-dev?node-id=225%3A836)], it has several table headers for: 

'View', 'Event date', 'Event type', 'district' and 'county'. 

On a desktop-sized screen this works fine but to make the table usable on smaller devices would be very difficult. The reason for this is similar to the problems found on Free Cen, Free Reg, and BMD results pages when you view it on mobile. The problem being that to view all the contents of the table the user would have to scroll horizontally. From a user experience point of view this is a massive 'No-No'. This is because research shows that users will miss data that is hidden unless they scroll horizontally and is poor for accessibility. [See this study for more information on this.](https://www.nngroup.com/articles/horizontal-attention-leans-left/) 

[Example of this on freecen](https://www.nngroup.com/articles/horizontal-attention-leans-left/)

To combat this issue I have simplified the designs further by focusing on getting it right on mobile-first. I actually think it has turned out better than previously. It still uses the same base code for the table results but now results are shown across only three columns. -

' View', 'Individual' and 'Event type'.
 
The 'individual' columns now show the first and last name, date, and county. Doing it this way was the only way I could think of getting an accessible table and not require users to scroll horizontally on smaller devices.

_Here is how my previous example would look like on mobile device:_

![image](https://user-images.githubusercontent.com/60981661/89743616-bda9da00-da9c-11ea-99e7-1ad5e98cedc1.png)

As you can see it defeats the purpose of giving users the data they are searching for i.e., you can't see it on certain devices unless you know that you need to scroll horizontally and know how to that. 

_Here is how it now looks with new changes_
![image](https://user-images.githubusercontent.com/60981661/89743626-cbf7f600-da9c-11ea-9d2a-62f52e780420.png)

As you can see, no data is hidden from the users' view. If the user wants more details they can go to the detailed results page which after all is the purpose of the 'detailed' results pages :) 

**The buttons**
On my previous design, there were a lot of buttons on the page. This can actually be worse for user experience by forcing the user to have to think too much rather than just giving them what they need- which is the results. I can also imagine this being a pain for screen reader users. 

The main change is on the detailed results page where the main buttons are now only the back button and tools button. The previous and next result buttons are now below the table which will allow for a more seamless transition as users click-through results and makes more semantic sense at least for me - we will have to test this with users though.

Also, I think the 'about this query' button is only suitable at the point at which the user is inputting the search parameters which is why I've taken it off the designs.

**Next steps**
Please can you have a look through the latest iteration of the designs? I've mocked them up on different screen sizes. This means that the 'dev spec' I linked to in my last email isn't totally accurate anymore and doesn't account for the proposed changes in this email. 

If I get sign-off for the latest designs it should be relatively quick for me to update the dev spec for vino though. 

[You can view the latest designs here 
](https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-design-to-dev?node-id=231%3A0)

[The design for you to compare with is here 
](https://www.figma.com/file/taWyCA226beA2JoDX0UF4u/Option-2-design-to-dev?node-id=225%3A836)

I hope that all makes sense.

If you have any question feel free to get in touch,

Cheers,

Daniel

**Comment by PatReynolds** [comment]
@Daniel-silve1ra Vino says a 'sort by location' and 'sort by location' button is possible.  She can also impliement as a single drop-down choice - please could you design for the solution you think is better?
Can you also show how non-contiguous results are going to be marked (?a symbol)

**Comment by richpomfret** [comment]
Otherwise I think we are happy to go with the design/sign it off - ignore my previous email about adding more columns in the desktop version. ;)

**Comment by PatReynolds** [comment]
Just noticed that the non-contiguous data is no longer indicated (see issue #191. 

This might be achieved by a shading of the row of  non-contiguous entries, by a symbol in the 'Individual' data or by other means.

**Comment by Daniel-silve1ra** [comment]
Hi Pat,

Thanks for the comments. I'm not very clued up on what non-contiguous
entries are? Would you mind giving me a brief description of what it is?

**Comment by PatReynolds** [comment]
Hi @Daniel-silve1ra It's complicated.  I have re-opened story #191 which is where a lot of the information and discussion about non-contiguous data was captured.

It boils down to: how do we show, on the results page, that two entries were next to one another in the original index?  In FreeBMD1 this is done by changing the lightness/darkness of the strip when entries were non-contiguous (not next to one another in the index)..  I think the last solution was to make the box boundery of the record type lighter or darker if the entries were non-contiguous.  

Doing this has flagged for me that another feature - the ability to see the entries on the same page as the entry one is interested in - was not yet captured.  I have created a story for that (#269).

Also italicising districts that are suspect (e.g. probably typos in the index or transcription of the district volume or page number (now story #270  and boluding those which have been double keyed (now opened as story #271).

**Comment by PatReynolds** [comment]
Non-contiguous data to be shown after MVP.

Sorting by firstname, last name, etc. to be afterMVP.

So signed off.
