### ISSUE TITLE
Review consistency of the search experience pages

### ISSUE THREAD

**Issue by Daniel-silve1ra** [FreeUKGen/FreeBMD2#237]
**Review consistency.**

- [ ] Padding is consistent across screens and devices.
- [ ] Font sizes are consistent across screens and devices.
- [ ] Text, buttons, and data elements use accessible colors.
- [ ] Check all designs and notes for spelling errors.

**Comment by KristinaGadzhieva** [comment]
@richardofsussex Currently the size of the quarter field is slightly different from other fields.  Richard please have a look whether this can be fixed and whether we have any other visual inconsistencies.

**Comment by richardofsussex** [comment]
The quarter field has padding = 14px in all four directions. In contrast, the other fields have padding = 10px. Examining the CSS for these input elements, the quarter field has class = "text-input", while the others have class = "input". If I change the class of one quarter to "input", it lines up with the other fields:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7892815582f05ae6c438d4b7287684e431508c71/image.png)

This is the corresponding change in the source code:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--747738f5e8d00d0052b1fa8040cab514f0fb36ac/image.png)

**Comment by richardofsussex** [comment]
This isn't a complete solution, since the background colour of the altered quarter field is not white. However, it shows the area where a fix needs to be applied.

**Comment by DeniseColbert** [comment]
@richardofsussex to address this blue/white background issue and also County and Districts fields

Also look at the colour (?) of the labels of the fields on the search form for consistency.

Also centre "Search our Birth/Marriage/Death Records"

Investigate contracting Birth/Marriage/Death in the title to BMD on smaller screens

**Comment by KristinaGadzhieva** [comment]
I also suggest to change font in the menu bar to uppercase so that it looks consistent with FreeCen and FreeReg

**Comment by KristinaGadzhieva** [comment]
Also discuss whether 'Main search options' should be renamed to 'Search fields'. There are no additional search fields or filters on the search page anymore, the word 'main' seems irrelevant. 
<img width="1628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7d04a798c3bcffda6882d0def8500263007a955/Screenshot_1.jpg" alt="Screenshot_1.jpg" />

**Comment by DeniseColbert** [comment]
Agreed, 'Search fields' seems the best title, but this is just one change of many required by this story

**Comment by richardofsussex** [comment]
Returning to the original issue, further investigation and comparison with FreeReg reveals that it is the text inputs on that line, not the quarter field, which are non-standard. The padding for all input elements is calculated based on the base font size and the base line height; for FreeBmd2 this padding comes out as 14pt. However there is an instruction in freebmd_content_scss.erb which overrides this, and forces the padding for `<input>` elements to be 10pt. (`<input>` is the actual tag on the resulting web page; in the Ruby source it is **`<%= text_field_tag`**. The quarter field is declared in the source as **<%= select_tag**, and becomes `<select>` in the resulting web page.)

To achieve visual consistency for these elements, we need either to extend the 10pt-padding strategy to _all_ input elements for FreeBmd2, or remove the enforced 10pt padding for `<input>` elements. It would be helpful, when deciding what to do, to understand when and why the 10pt padding was introduced for `<input>`.

Another aspect of this original issue and my attempted fix is the background colour of input elements. FreeBmd2 differs from the other projects in having a coloured background to the search form; Reg and Cen both have a white background. However, if we enforce a white background colour for all input elements in our system-wide CSS rules, this will work for either strategy.

**Comment by richardofsussex** [comment]
By adding 10pt padding for `<select>`, I can get the boxes to line up:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/15da9518-93ad-41ea-a9e9-f49675b4bee7)

The question is whether we want a different layout strategy for BMD2, compared with the other two projects (and, if so, why). (Thank you @Vino-S for helping me update the compiled CSS file - another useful piece of learning.)

**Comment by richardofsussex** [comment]
Header is now centred:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/8259484e-5179-46ca-93d5-09dcb63a755c)
and contracts when screen less than "desktop" size:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/bf50fbde-5e60-41a0-b2a2-0bcdea2e86bd)

**Comment by richardofsussex** [comment]
As regards the background colour for form elements, the CSS for the `text-input` class already includes `background-color: #fff;`. This suggests that we should _not_ change the class of `<input>` elements, and should instead aim to ensure that `<input>` and `<select>` elements have the same padding. I have currently done this by applying the same rules to `<input>` and `<select>`.

**Comment by richardofsussex** [comment]
@DeniseColbert and @KristinaGadzhieva - these changes are now in test3 for you to have a look at.

**Comment by KristinaGadzhieva** [comment]
It looks much better now! Thanks a lot Richard!

**Comment by KristinaGadzhieva** [comment]
To summarize the required changes mentioned above: 
- [x] Background colour for Quarter&Year fields
- [x] Background colour for Counties and Districts fields
- [x] Size of text input elements
- [x] Font colour of the labels of the fields (Quarter & Year text colour is different from First name, Surname and other fileds). To decide which one is better and make it consistent everywhere. 
- [x] Centre "Search our Birth/Marriage/Death Records"
- [x] Contracting Birth/Marriage/Death in the title to BMD on smaller screens.
- [x] Rename to 'Search fields'

**Comment by richardofsussex** [comment]
I have added the "text-input" class explicitly to the Counties and Districts `<select>` elements. This fixes the background colour issue.

As far as I can see using the web developer Inspector tool [in Firefox], all the field labels are the same: rgb(68,68,68), "Source Sans Pro", 18px, bold. The one heading which was different was the "Search fields" label for the whole search form, which wasn't bold. I have fixed this by assigning it class "label".

**Comment by richardofsussex** [comment]
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/ee8ee7da-c31c-4dfb-9f27-c6858b8fb008)

**Comment by richardofsussex** [comment]
Need to check why we get <legend> not <label> on test3 as well as on beta. I get <label> from my branch (which is derived from the BMD2 development branch).

**Comment by KristinaGadzhieva** [comment]
@DeniseColbert @richardofsussex Thank you, Richard. I also think we should decide which font style (or colour) is better: bold (as Quarter & Year) or the same as other labels. Bold font is good because it looks brighter against a blue background, but it is different from FreeCen and FreeReg.

**Comment by richardofsussex** [comment]
The standard approach (as used in FreeCen and FreeReg) is to have a `<label class="ttip" for="XXX">`, while the bolder headings now found in FreeBmd have `<legend class="label">`. Can @Vino-S please comment on why `<legend>` has been introduced? Is it associated with the neighbouring `<fieldset>` element?

I would prefer that we use consistent markup for these 'label' elements. Once we have agreed on the markup strategy, we can look at the CSS styling. My interpretation of the Inspector display is that the only difference between these two approaches is the font colour (rgb(68,68,68) for the `<label>` and rgb(34,34,34) for the `<legend>`).

**Comment by Vino-S** [comment]
Yes, @richardofsussex , `<legend>` tag is used with the `<fieldset>` element.
We implemented this solution for accessibility. Reference (story[#490](https://app.zenhub.com/workspaces/freebmd2-5cc6dc330898a02e123026e2/issues/gh/freeukgen/freebmd2/490))

**Comment by richardofsussex** [comment]
OK, so `<legend>` is meaningful, and required. Examining the CSS cascade, I see that the font colour for `<legend>` 'falls through' from the default HTML settings, while that for `<input>` is intentionally set. So I have decided to set the font colour for `<legend>` to be `#444`, i.e. the same as for `<input>`. This is the result:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/5f57bdb6-9f76-48ca-8f93-876c1128332b)

which I think is acceptable.
