### ISSUE TITLE
Competitive analysis of search experience pages

### ISSUE THREAD

**Issue by Daniel-silve1ra** [FreeUKGen/FreeBMD2#241]
**Competitive analysis**

- [x] Conduct analysis
- [x] List MVP requirements we want to adapt for our designs

**Comment by Daniel-silve1ra** [comment]
- https://docs.google.com/spreadsheets/d/1oQMCZimkb4DlTFk-H5tYhaEeDB63H6jPqDTWXhfu_PQ/edit?usp=sharing 

- https://docs.google.com/spreadsheets/d/1TQuTuGixBCHLZuww8C7YYFutEKl7YeS0SHxgXOsU9gk/edit?usp=sharing

**Comment by richpomfret** [comment]
@PatReynolds and @richpomfret to take a look.

**Comment by PatReynolds** [comment]
Not sure what I'm to look at @KatyMawhood @Daniel-silve1ra  - could you let me know what you want feedback on, please?

**Comment by richpomfret** [comment]
Closing.
