### ISSUE TITLE
Add auto ads to FreeBMD2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#244]
I would like us to test auto ads on FreeBMD2 - I am assuming they won't be suiltable for us, as it may result in adverts in places where we really don't want them - but since this is a test site, it doesn't matter if they do (or if users don't like them) as we can go to traditional, placed adverts

The documentation from MonetizeMore is here: https://drive.google.com/open?id=1BIoLeGpYMFpuMv240oUbfUXPB9RPX_k6 - John at MM says "Please implement this code attached to this email between <head></head>. 
Let us know once the script is implemented."

I'll move the other advert stories to 'on ice' pending the outcome of this story.

**Comment by Vino-S** [comment]
ready for testing test2

**Comment by richpomfret** [comment]
@richpomfret to take a look.

**Comment by PatReynolds** [comment]
@PatReynolds to test in Rich's absense

**Comment by PatReynolds** [comment]
tried, but adsense not recognising test3 - perhaps because of the password protection?  I have asked the community for support 18/11/2020

**Comment by PatReynolds** [comment]
Not able to implement, perhaps because it is passworded. Google suggests implementing web crawler authentication: https://support.google.com/adsense/answer/161351?hl=en

**Comment by PatReynolds** [comment]
@Vino-S to take a look

**Comment by PatReynolds** [comment]
Asked John for code 26 Jan 2021

**Comment by PatReynolds** [comment]
John emailed to @PatReynolds and @Vino-S 26 Jan 2021

**Comment by PatReynolds** [comment]
Adverts displaying as expected, except pop-up advert at bottom of page is not staying closed.

Create report for the url in Adsense today - no data yet collected/showing.

**Comment by PatReynolds** [comment]
@PatReynolds to test again.

**Comment by PatReynolds** [comment]
Code sent to Vino 5th Sep 2022 - needs to go on each page.

**Comment by DeniseColbert** [comment]
@PatReynoldsFUG were there any next steps Pat?

**Comment by DeniseColbert** [comment]
Closing as superseded by Publift
