### ISSUE TITLE
Add Transciber information in search detail page

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#245]

**Comment by richpomfret** [comment]
Shall we test this? It looks like it was moved from testing back into 'progress' but no reason given (here at least). It may not be working, @Vino-S to take a look when she has time.

**Comment by PatReynolds** [comment]
Needs to be added.

**Comment by Vino-S** [comment]
ready for testing in test2

**Comment by richpomfret** [comment]
@DeniseColbert to take a look.

**Comment by DeniseColbert** [comment]
Appears to be working fine

**Comment by Vino-S** [comment]
Deployed to test3. So Closing it
