### ISSUE TITLE
Search button issue

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#246]
When I clicked Search, the button looked like this:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/520754ff-3ad1-4ac6-b7b0-2e7b8f6c1bb1)

Seems different to the way the button changes upon click in FreeREG & CEN

Also, if we want the word 'Search' to remain, it should show the whole word.

**Comment by Vino-S** [comment]
Ah Yes Denise. I am working on implementing spinner for search button. It will be fixed once I finish it

**Comment by DeniseColbert** [comment]
Thanks, Vino. Closing.
