### ISSUE TITLE
173632883 Data Problem (vino)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeBMD2#252]
Issue reported by **vino** at 2020-07-02 15:21:23 UTC
Time: 2020-07-02T15:20:16+00:00
Session ID: 9137c96be5b0dcc44d1cd4589cd293c2
Problem Page URL: [https://test3.freebmd.org.uk/best_guess/5efdfb12e93790116a6be884/237597994/william-walker-callum-death?locale=en](https://test3.freebmd.org.uk/best_guess/5efdfb12e93790116a6be884/237597994/william-walker-callum-death?locale=en)
Previous Page URL: [https://test3.freebmd.org.uk/contacts/237597994/report_error?locale=en&query=5efdfb12e93790116a6be884](https://test3.freebmd.org.uk/contacts/237597994/report_error?locale=en&query=5efdfb12e93790116a6be884)
Reported Issue:
test
https://test3.freebmd.org.uk/uploads/contact/screenshot/5efdfb73e93790116a6be886/Screenshot_2020-05-21_at_20.58.50.png

**Comment by richpomfret** [comment]
Test. Closing.
