### ISSUE TITLE
What happens when browser is set to larger font size?

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#255]
I have my browser set to show larger text and the FreeBMD2 search form doesn't look very good:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/7ba16d2c-2b1c-4d9b-bbc7-bc1f276a6927)

Compared to FreeREG:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/698e93ad-3a1b-402d-8b39-792d000513b4)

I know FreeREG doesn't try to cram a lot of fields in like FreeBMD2, but still, can we accommodate for this?

**Comment by DeniseColbert** [comment]
EDIT: wrong FreeREG snip uploaded- now replaced.

**Comment by PatReynolds** [comment]
@PatReynolds to test.

@Vino-S to adjust number of fields across the grid as a larger font is used.

**Comment by Vino-S** [comment]
Hi @DeniseColbert , Made few changes.
Could do a test in test2 and let me know if it is better

**Comment by PatReynolds** [comment]
Looking good at 175% on a desktop:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/1a7c671a-8493-4737-bf70-ad6afcd9b93c)

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4055c89a-04f6-4531-89a9-6a0ecb792400)

Narrower screen, a couple of problems:
main content bar is not responsive:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/0796194c-6eab-4b19-814d-2981083c8be4)
Scans and Postems and Transcribers not behaving as expected (I would have expected the title "Scans" then the scans, then Postems and Transcribers.



![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/7cdba29f-5a8e-4d5b-9ba6-17889800f790)

**Comment by DeniseColbert** [comment]
Original issue persists:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/fbdf132e-0651-42df-a8a9-327b20b6a857)

Possibly you fixed responsiveness to zoom function @Vino-S ? This appears to be what Pat is referring to in her comments above. However, my screen isn't zoomed at all; I have my browser settings showing larger font.

**Comment by richpomfret** [comment]
@Vino-S to implement fix as per @DeniseColbert comment above.

**Comment by Vino-S** [comment]
Hi @DeniseColbert,
I had made some changes for Year field in 'Date Range From' and 'Date range to' of the search form. Please have a look and let me know if it is better than the previous implementation.
Ready for testing in test2

**Comment by richpomfret** [comment]
@DeniseColbert please take a look when you can.

**Comment by DeniseColbert** [comment]
Still looks the same:

![image](https://user-images.githubusercontent.com/19173257/109535869-f51db980-7ab4-11eb-8364-cb5346f4a0f2.png)

**Comment by DeniseColbert** [comment]
I wonder if we can tell the browser to ignore the text inside the fields when increasing font size? @Vino-S will look into this

**Comment by DeniseColbert** [comment]
@AlOneill in scrum, we discussed removing the placeholder text in the First name/Surname fields. Is there a reason (perhaps for accessibility) we need this text inside the fields?

**Comment by AlOneill** [comment]
@DeniseColbert 
In short, no.

The (HTML) Label is much more important than the placeholder text because placeholder text is visible (and audible) only when the field is empty: it disappears for all users when the field is filled in. 

A label that is properly (programmatically) linked to the field is essential; the placeholder text is by-the-by and should never be used to replace a properly marked-up label.

**Comment by AlOneill** [comment]
@DeniseColbert 
I forgot to say that it is strictly one label for one field, which is why the labels for dates are invalid: one label for two fields (quarter and year, two separate fields) is broken, is an error and will confuse a screen reader user.

The label "Record type" with `for="record_type"` is not linked to any field and so is orphaned — also an error.

**We must get these details correct** or the search form will remain inaccessible to screen reader users.

**Comment by richardofsussex** [comment]
@DeniseColbert and @Vino-S please pick up on @AlOneill comments and amend markup accordingly.

**Comment by DeniseColbert** [comment]
- [x] Remove placeholder text 
- [x] Address "The label "Record type" with for="record_type" is not linked to any field and so is orphaned — also an error"

@Vino-S to do/fix

rror."

**Comment by AlOneill** [comment]
@Vino-S @DeniseColbert 
The "orphaned label" issue has been fixed and that has been noted as part of another issue (reducing space around record types) — nothing more to do there.

**Comment by DeniseColbert** [comment]
Done; closing

**Comment by DeniseColbert** [comment]
Thanks all
