### ISSUE TITLE
Implement search results page 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#256]
Based on designs in #83

**Comment by DeniseColbert** [comment]
I noticed we don't have a story for this and it's in progress so created this. @Vino-S if it's ready for review, please move it there :)

**Comment by Vino-S** [comment]
Initial implementation completed: test2

**Comment by Vino-S** [comment]
Moving it to in Progress: Making Changes suggested by Daniel

**Comment by Vino-S** [comment]
implemented on demand display of search criteria

**Comment by richpomfret** [comment]
@Daniel-silve1ra can you take a look and feedback for Vino? The rest of us can take a look too.

**Comment by Vino-S** [comment]
Added styles to tools button

**Comment by Daniel-silve1ra** [comment]
Hi @Vino-S ,

Great progress on the page styling of the results page so far. We are getting closer to the original design. Thanks for your hard work on this  

There are still a few things which aren't quite matching the original design, though. I've made a google doc which outlines what these are. In the doc I've written some pre-prod code. I've tested most of the code through Chrome dev tools so I feel confident they should work and should facilitate things on your end. 

Please feel free to put an appointment in my calendar if you have any questions about it or need me to clarify anything.  

[**The doc** ](https://docs.google.com/document/d/1PSuF8yuZNiOnGB9u_zp8Nk6V3gM2K82kQPc49Z_Wot0/edit?usp=sharing)

I'll be reviewing the detailed results page and get that to you by the end of the weekend.

Again, thanks for your help on this.
Daniel

**Comment by Vino-S** [comment]
Updated some of the changes suggested by Daniel in test2. 
Not Sure about the functionality of **Jump To**. Any example will be helpful

**Comment by richpomfret** [comment]
@Daniel-silve1ra can you provide an example for @Vino-S?

**Comment by richpomfret** [comment]
@Daniel-silve1ra @Vino-S  is this story still required or can we close?

**Comment by Daniel-silve1ra** [comment]
Will get to this this week

**Comment by richpomfret** [comment]
@Daniel-silve1ra any update or opportunity to look at this?

**Comment by richpomfret** [comment]
In the absence of any further noted feedback or work, we shall close this.
