### ISSUE TITLE
I need access to Refinery

### ISSUE THREAD

**Issue by ComfE-2662** [FreeUKGen/FreeBMD2#266]
In order to help the documentation team with mark up and html, I need to have access to Refinery
When I log into the transcriber page this is all I can see. 

 ![Capture.PNG](https://images.zenhubusercontent.com/5ecd15a9812f89eaa03d991e/8b642e57-a6f6-4bf1-9485-ce75a77c4337)

**Comment by richpomfret** [comment]
@Vino-S to assist.

**Comment by Vino-S** [comment]
Hi @ComfE-2662 ,  I had given you access to Refinery Pages in test3. Can you test an let me know please

**Comment by ComfE-2662** [comment]
Hi Vino, 
No it still doesn't work. I'm signing in on test 3 and I get the same message

**Comment by ComfE-2662** [comment]
@Vino-S  
I was wondering if you ere able to give me access to refinery?

**Comment by Vino-S** [comment]
Hi @ComfE-2662 ,

Can you try again please. Your userid should have access to Refinery in test3

**Comment by richpomfret** [comment]
Closing as @ComfE-2662 now has access.
