### ISSUE TITLE
Allow user to view all entries on a page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#269]
Current FreeBMD has this feature: click on the page number in the results, takes you to a page with all the entries on that page of the original index.

This is helpful for finding partners in a marriage, and also for spotting twins, and others who have died in the same disaster.

currently this is in the results page, but could be presented as data in the detailed results page.

**Comment by PatReynolds** [comment]
for examle https://www.freebmd.org.uk/cgi/search.pl?start=1840&end=1840&sq=1&eq=1&type=Deaths&vol=18&pgno=153&db=bmd_1595843552&jsexec=1&mono=0&v=MTU5ODQ1OTQ4NTpiNDZjM2ZiYmFmMTBhMjdjZjI2ZWU0OTIzNmZkODY0M2VlNzc2MjEx&searchdef=db%3Dbmd_1595843552%26surname%3DAlcock%26end%3D1840%26type%3DDeaths%26sq%3D1%26start%3D1840%26eq%3D4&action=Find

**Comment by richpomfret** [comment]
Implemented, will close.
