### ISSUE TITLE
Add a "submit a review" button to "Your reviews" page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#277]
Will need to route to support@ if someone ticks a box saying 'please could someone help me with this issue' or similar.
Will need consultation with support team on best way to capture the right data.
Need a disclosure of name consent (yes/no) if review chosen for publication.

**Comment by PatReynolds** [comment]
@PatReynolds to check FreeBMD1, and re-prioritise

**Comment by PatReynolds** [comment]
@ArcherBarrie  I could not see a submission form or other way of submitting a bouquet on FreeBMD1 - have I missed it?

**Comment by archerbarrie** [comment]
@PatReynolds Not really ... we don't have a specific way of doing that but https://www.freebmd.org.uk/iindex.shtml gives a couple of other options.

**Comment by PatReynolds** [comment]
Submission form to be embedded on the page.

**Comment by DeniseColbert** [comment]
Covered in Reviews story- closing
