### ISSUE TITLE
Decide how to handle references for images in citations

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#280]
It is best practice to actually look at an original image rather than assuming that the FreeBMD transcription is correct.

It is best practice in genealogical citations to reference the original image, not the finding aid. 

Can we achieve best practice - i.e. generate citations that include the image looked at (e.g. UKD-01/1841D1-0128.tif or 1837B3-B-0017.jpg, etc.
See also systemwide #154

Will this require tickboxing the image(s) looked at?  Would it be sufficient simply to list all the images which are associated with the record (in the citation, not the url)?

**Comment by PatReynolds** [comment]
I think it will be fine to simply list all the images in the citation, and the researcher can edit if they want to specify the one looked at.

**Comment by richpomfret** [comment]
Decision made and new story created/updated so now closing.
