### ISSUE TITLE
Decide on placement of citation generator

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#281]
Currently citation generator is in the buttons at the top of the screen.

Given the bet practive of reviewing the images (see #280) should citation generation be an action placed under the images?

**Comment by richpomfret** [comment]
Currently in drop-down menu within 'tools' button. Are we happy with this? Is it apparent/visible enough? Discussed side-list of citation types which appear when a user selects 'citations' within the tools button.
