### ISSUE TITLE
Implement entry information page

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#284]

**Comment by PatReynolds** [comment]
Tested on test2:

Needs page Title (Entry Information).

**Comment by Vino-S** [comment]
Added title on test2

**Comment by PatReynolds** [comment]
@Daniel-silve1ra   to review - functionality and aesthetics

**Comment by PatReynolds** [comment]
@jayto581 could you also take at this page, please?  Thanks, Pat

**Comment by jayto581** [comment]
Here is a mock-up of the new footer for FreeBMD with the new link added.
![image](https://user-images.githubusercontent.com/64029992/102104745-8a85a780-3dfc-11eb-9f15-364b7434f910.png)

**Comment by PhilipClarke712** [comment]
Hi Jayto581,

 

I like it. 

 

But I have two questions: (1) is this going to get up dated nominally every 28 days in-line with the (FreeBMD) update cycle; (2) if so, could it have a line giving the date of the last data-base update – which at the moment was Thursday 19th Nov. 2020 and the next one is likely to be round about this Thursday (17th) December 2020?

**Comment by jayto581** [comment]
Hi PhilipClarke712,

The footer statistics will be updated regularly in the future. However, for the time being, the footer statistic section will be static.
                  Cheers,

**Comment by richpomfret** [comment]
Looks like this is now complete. Ready for deployment (close when deployed).

**Comment by Vino-S** [comment]
Code deployed to test3. So closing it
