### ISSUE TITLE
Add information on Accessibility to the site

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#288]
- [x] Create Accessibility Page (based on FreeCEN/FreeREG
- [x] Add accessibility statement to About page
- [x] Update link to blog

**Comment by PatReynolds** [comment]
Accessibility Statement now ready for proofing / inclusion in About, including updated link (needs testing).

**Comment by AlOneill** [comment]
Had a quick look and there are a couple of issues with this page: non-semantic use of the `q` element and links to other sites that do not open in a new tab. (No doubt these will need fixing on CEN and REG too.)

I'll fix the issues and delete the miss-pasted version of the page at the foot of the listing.

Final task will be to add a working link from the About page.

**Comment by AlOneill** [comment]
"Accessibility statement" fixed and working link added from "About".

Miss-pasted version of Accessibility statement deleted.

**Comment by AlOneill** [comment]
Corresponding CEN (a child of DRAFT About) and REG pages fixed on their respective t3 sites.

**Comment by richpomfret** [comment]
To test on test3. @PatReynolds to check it looks fine.
