### ISSUE TITLE
Check all headers in refinery pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#294]

**Comment by PhilipClarke712** [comment]
I'm not quite sure what this story is intended to cover. Test2 has an **About** tab on that top red bar (Transcriptions; About: Volunteer, ... etc) and I'm seem to remember that Test3 had one, but today it does not have one. The **Transcriptions** tab is still a link to FreeBMD's page: https://www.freebmd.org.uk/progress.shtml . 

Now we do have a draft **Transcriptions** page on Test3 which is still work-in-progress and I give no advice on whether an incomplete page should be put there (but there is a precedence - the Help page). Putting it there might produce a response along the lines "this aught to be in it, but it is not", or its inverse response.
If this is not relevant to the story, then that is my error.

**Comment by PatReynolds** [comment]
It means checking that each page contains a main page heading marked as (h1) and a leading paragraph, and indexes if needed.  The leading paragraph may be irrelevant to some pages.

The 'about' tab disappears when one is logged in (this was to save space on the bar when it was becoming crampted - it is being re-instated).

**Comment by AlOneill** [comment]
The 'main page heading' `h1` is automatic: it is the file name for the page, down-cased with punctuation removed and spaces replaced with hyphens. In other words, no check is needed for its existence. The page author should **not** add another one!

'Indexes' (sub-menus) and `<p class="lead">` are created by the page author.

**Comment by PatReynolds** [comment]
No on the proofing checklist, so  not needed as a separate action.
