### ISSUE TITLE
View Records of a page

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#297]
View Records in page from the Entry Information page

**Comment by richpomfret** [comment]
Would you like us to test this on TEST2 @Vino-S?

**Comment by Vino-S** [comment]
Yes. Ready for testing on test2

**Comment by PatReynolds** [comment]
Thank you, Vino.  This is working as expected.

On FreeBMD1, hovering over the page number produces the information "Page - click to see other entries on this page" - could this be added?

I think the page header - eg "Records of 385 page" needs expanding - perhaps "Records on District Volume Page" not just Page?

Also to note: on FreeBMD1, this information is available from the search results page, not the entry information page, and thus contains the age at death.  I will note that as a separate story.

**Comment by Vino-S** [comment]
Thank you @PatReynolds ,
_On FreeBMD1, hovering over the page number produces the information "Page - click to see other entries on this page" - could this be added?_

Yes, Pat. Will make the changes

_I think the page header - eg "Records of 385 Page" needs expanding - perhaps "Records on District Volume Page" not just Page?_
I will make the changes and also include the RecordType too

_Also to note: on FreeBMD1, this information is available from the search results page, not the entry information page, and thus contains the age at death. I will note that as a separate story._

The FreeBMD2 search results page does not show Volume and Page, unlike FreeBMD1. so we cannot implement this feature on the search results page. 
The display of **Records in a Page**  is similar to search results page so it does not show any information of Age at Death/ Mother's name/Spouse name. This information can only be viewed in the Entry Information Page.

**Comment by Vino-S** [comment]
Following changes are ready for testing in test2:
1. Improvised the page header
2.Added hover text 'click to view other entries on this page'

**Comment by richpomfret** [comment]
@PatReynolds to test those changes.

**Comment by PatReynolds** [comment]
Link back to Entry Information Page

**Comment by PatReynolds** [comment]
I wonder if saying" Selecting the page number shows all the entries on this page. Link opens in a new tab" rather than simply "(Link opens in new tab.)"

Display means it is easy to navigate back to the entry information page the user came from.  But they won't then be able to get back to their search.  Let's discuss in the scrum.

**Comment by Vino-S** [comment]
View Records of a page opens in a new tab(which is not the convention we follow). My reason was to keep it(Records of page) separate from Search Results. 
Let me know, we can make the changes if needed.

**Comment by richpomfret** [comment]
@PatReynolds can you confirm if anything else is needed here? Otherwise we can close as fixed.

**Comment by PatReynolds** [comment]
Thanks, @Vino, all good!
