### ISSUE TITLE
Create beta.freebmd.org.uk

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#298]
Deployment will be to this site, for Beta testing

**Comment by JimKillock** [comment]
Looking forward to seeing this!

**Comment by PatReynolds** [comment]
Not sure why I'm on this - Rich is this just you?

**Comment by PatReynolds** [comment]
@richpomfret can this be ready for use by Monday 21st please.

Is it possible for this to be on a faster server?  I may be too used to the new fast FreeCEN and FreeREG!! but I guess we are going to get complaints about time to search - will need to alert testers to this if it isn't possible to resolve before testing.

**Comment by richpomfret** [comment]
Sorry Pat, this won't be ready for then. We will need to use Test3 for initial testing and then have the beta site ready for wider testing.

**Comment by richpomfret** [comment]
Now in-progress following email thread with @lemon-ukgen and @Vino-S. We discussed whether we use test3 for beta testing, but now looking at getting production site set-up with full DB with beta url.

**Comment by lemon-ukgen** [comment]
https://beta.freebmd.org.uk/ is up in a new `rails2` jail on `night.freebmd.org.uk` (same auth as test2/3)

There will be likely some glitches to resolve but the basic frontend seems ok.

I don't have access to the backend to check, eg, Refinery is happy. I have started registration as a Technical volunteer to check.

**Comment by richpomfret** [comment]
Thank you @lemon-ukgen. We will need to consider how we update refinery or update/deploy new changes from Test3.

**Comment by PatReynolds** [comment]
@Vino-S to explore slow loading - e.g. scan page, loading scans.

**Comment by richpomfret** [comment]
@DeniseColbert to make story about any site performance issues or bugs in terms of slow loading. This story now to be closed as we have the beta site up and running.
