### ISSUE TITLE
Increase "global" search with wildcards in names upto existing FreeBMD standard

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#299]
I might wish to do a wildcard search such as: births, whole of a specified year or quarter, unspecified county, unspecified district, surname PAR*, unspecified forenames.  Note: a some point I may hit the 3,000 limit; so, if and when that happens, I tighten up the search parameters to decrease the number of hits a rerun the search.

On both test3 & test 2 I get a Prohibited message: **1 error prohibited this search from being processed:  Wildcard can only be used with a specific place/district.** I switched the year for 1998 to 1889 to check it was due to the data-set, but that did not affect the prohibition. I then switched the surname search to PA?K and hit the same prohibition.

If I do the same search for births in 1989 FreeBMD(1), I hit the 3,000 limit; but if I make the surname PARK* (or PART*) I get the complete listing.

I might have scottish ancestry so I might decide to look for McPherson: and I can do it on test 2 / 3; I can also do MacPherson on test 2 /3. I would like to be able to do M?Pherson or M*Pherson, which should find both the Mc and Mac variants. I can't do it on test 2 / 3, but I can on FreeBMD.

I then tried looking for FRED* PARK (i.e. forename & surname respectively), unspecified county, unspecified district, which should find both FRED and FREDERICK, but I can't do it on test 2 /3 .

**Comment by PatReynolds** [comment]
No need to restrict to county/district on FreeBMD2 as the limit relates to Mongo processes.

**Comment by Vino-S** [comment]
Ready for test in test3

**Comment by richpomfret** [comment]
@PhilipClarke712 would it be possible for you to take a look and test this?

**Comment by PhilipClarke712** [comment]
Hi @richpomfret 

Yes, I can do that, but what system(s), just test3, or should I also look at test2?

**Comment by PhilipClarke712** [comment]
Hi @Vino-S , @richpomfret 

1. I'm pleased to say that I got what I specifically asked for, but I'd like a bit more, please if it is not too onerous?

I quickly found that I could search for Fred* & Park*  [forename & surname], births, between 1930 and 1935 and it gave me 134 hits that were very reasonable.

I also tried Fred? Park? and got the same results: Note on FreeBMD(1) * is a wild card search for any number of characters include nil characters. whereas **?** means just one character (see "Details of the parameters of a search" section in https://www.freebmd.org.uk/search-help.shtml ), but I did not specifically refer to it at the start.

2. I searched for just M[asterix]pherson [surname] using the same search criteria and got 333 hits. I then tried the same search , but with   Mother's surname Mcpherson and got  6 hits; if I changed the mother's surname to M*pherson I got 9 hits. So I'm happy with Mac/Mc surnames.
3.  I wanted to look more that the distinction between a * and a ? character search: there are very few "Dave" [forenames] in my selection. If I searched for "Dave" [forenames] Exact match, no surname, births, 1930 to 1935 I got just  4 hits. If I remove Exact Match I get 25 hits: Dave, Davena, Davene, etc, which is very reasonable set of hits. Note: Philip does not work there are more than 3000.
4. I would quite like the ability to have a single wild card character search (?), but if I wanted to separate Dave and David, I could in theory use Dave* (25 hits) and Davi* (more than 3000) - but not in this case without a surname. Adding the surname Jones gave 1217 hits for the forename Davi*, reduced to 138 with David [Exact Forename]. However, "Dav_" , if implemented as per FreeBMD(1), should quickly find "Dave", etc, that are not "David", etc.

Note: I use [Asterix] once because there is another Asterix in the same line and the system treats it as a request for italic font. I hope this makes sense.

**Comment by Vino-S** [comment]
Hi @PhilipClarke712 ,
Fixed single wild card character search (?) on test3.

**Comment by PhilipClarke712** [comment]
Hi @Vino-S ,
I think I must be a bit devious:

I searched for r* dav?y [forenames] Vick [surname] and got one hit: a birth for Reginald Davey Vick, MARCH 1880, Dursley
and compared it against r* dav*y  [forenames] Vick [surname] and got two hits; 
a birth of Reginald Davey Vick, MARCH 1880, Dursley 
and a marriage of Robert Davy VICK, JUNE 1873, Tewkesbury 

So, on the basis of just those, I would say that **single wild card character search (?)** on test3 works.

I found two more problems, but I only putting one here and will raise a new issue for the other one (searching by multiple Registraration Disticts in different Counts) as it might not been a "quick fix".

**Searching on both the first and middle given names by preceding the** [middle] **name with a plus (+), thus "+jane"  does not find any "hits"** on test3.

Some of my ancestors named their first or second born child after a grandmother's surname, using it as a middle name, and that sometimes passes down the generations, so I have:
[first name] Grosvenor [middle name], Bloore [surname]
[first name] Ridley [middle name], Hayes [surname]
[first name] Davy / Davey [middle name], Vick [surname]
and they are sufficently rare to do a global search, All events (BMD), places and dates.

both searches (for all three surnames), e.g.:+Grovenor, Bloore and * [space]Grosvenor, Bloore (etc) work on FreeBMD.
both searches (for all three surnames) e.g. :+Grovenor, Bloore and * [space]Grosvenor, Bloore (etc) give **Nil hits** on test3.
I know what I looking for: so R* [space]Davy, Vick works on test3 as does W* [space]Grosvernor, Bloore and J*[space] Ridley, Hayes so I know the records are on test3.

Note: I'm only asking for +[middle name] & [surname] searches to be implemented; * [middle name] & [surname] would be a bonus.

**Comment by Vino-S** [comment]
Initial implementation complete in test3

**Comment by AlOneill** [comment]
@Vino-S 
Could you please describe exactly what should work now — it is not clear to me what I should be testing for.

**Comment by PhilipClarke712** [comment]
@AlOneill ,

If Vino has fixed what I was asking for, then you should get one or more results from a global search using the wild card (plus) + and hopefully (Asterix) *  in front of a forename on the three examples I gave above: that is

firstname = +grosvenor  & surname = bloore (possibly also firstname = *grosvenor  surname = bloore )
firstname  = +ridley  & surname =hayes   (possibly also firstname = *ridley  surname = hayes )
firstname = +davy & surname = vick  firstname  = +davey & surname = vick

**Comment by AlOneill** [comment]
@PhilipClarke712 
None of your examples produce any results. Perhaps because it is not the full database on t3 or perhaps because of exactly what has been implemented. Hence my question to Vino.

**Comment by Vino-S** [comment]
Apologies for the delay.

Partial searches at the bottom of the search form have two select fields: Name and an option to select the type of partial search

1.First Name:
	Usage Requirement: First Name cannot be blank or must contain only alphabets
	Options: **Contains, Ends With and Any**
	Option Description: 
	a)**Contains**

	This will get all the names that contains first_name searched by the researcher.
	For example: If a researcher had searched for "vino" with First Name: Contains option it will find:

		vino subbu, veena vino, vinoveena, vino veena subbu

 b) **Ends With:**

 This will find all the ForeNames that ends with first_name searched by the user
 For example: If a researcher had searched for First Name "vino" and choose the First Name: Ends With option it will find:

		vino subbu, veena vino

	c) **Any**
	This will find all the Given Names that have any of the first_name searched by the user
	For example: If a researcher had searched for First Name "vino veena" and choose the First Name: Any option it will find:

		vino subbu, veena vino, vino veena subbu, veena smith

2. **Middle Name:**
	Usage Requirement: First Name cannot be blank or must contain only alphabets
	Options: Starts with, Contains, Ends With and Exact match
	Option Description:

	1. **Starts with:** This option will get results where Middle Name starts with first_name searched by the user
	2. **Contains:** This option will get results where Middle Name contains first_name searched by the user
	3. **Ends With:** This option will get results where Middle Name ends with first_name searched by the user
	4. **Exact match:** This option will get results where Middle Name is exactly as typed by the researcher

3. **Last Name:**
	Usage Requirement: Surname cannot be blank or must contain only alphabets
	Options: **Starts with, Contains, and Ends With**
	Option Description:

	1. **Starts with:** This option will get results where the Last Name starts with Surname searched by the user
	2. **Contains**: This option will get results where the Last Name contains Surname searched by the user
	3. **Ends With:** This option will get results where the Last Name ends with Surname searched by the user

4. **Mothers Name:** 
Usage Requirement: Mothers Name cannot be blank or must contain only alphabets
	Options: **Starts with, Contains, and Ends With**
	Options Description: Works Similar to the Last Name

5. Other:
	Options: **In First Name or Middle Name and In Middle Name or Surname**
	Option Description:
	1. **In First Name or Middle Name**: This will find where the searched first_name is present in either First Name or Middle Name
	Usage Requirement: First Name cannot be blank
	Example: Search on First Name: Vino
	Results: vino subbu,  veena vino subbu

	2. **In Middle Name or Surname:** This will find where the searched Surname is present in either Middle Name or Last Name
	Usage Requirement: Surname cannot be blank
	Example: Search on Surname: Vino
	Results:  subbu vino,  veena vino subbu

**Comment by AlOneill** [comment]
Thanks @Vino-S , I think!
It will take me a while to understand your post. Brain feels overloaded for now and is failing to translate your description.

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 

I see the problem.

 I was asking for something that does not conform with the definitions above.

The records are on the database being used by test3, but I'm trying to specify: no first name (a blank first name),  a middle name that ends with specified search string and a surname. FreeBMD1 can do it, so I was hoping that BMD2 would do it some time.

If I try and define the (plus)(+) wild card

**Comment by Vino-S** [comment]
Hi @PhilipClarke712 
The original wildcard implementation has been re-designed. 
Your search query should still work, in the new implementation:

Search example 1:
firstname=**grosvenor**
surname=**bloore**
Choose the Name field: **Other**(below is the image)
Select one of the following: **In First Name or Middle Name**(below is the image)
![image](https://user-images.githubusercontent.com/26073943/126361445-73d977a7-e11b-4f7b-9f71-67b4cbcd8816.png)

The above query will work similar to _firstname = +grosvenor & surname = bloore_

Search example 2:
firstname=**grosvenor**
surname=**bloore**
Choose the Name field: **Middle Name**
Select one of the following: **Ends with**
The above query will work similarly to _firstname = *grosvenor surname = bloore_

**Comment by AlOneill** [comment]
And it also works with
firstname=**grosvenor**
surname=**bloore**
Choose the Name field: **First Name**
Select one of the following: **Contains** or **Ends with**

So many options …

**Comment by PhilipClarke712** [comment]
Hi Vino-S,

That has solved the problem - provided the researcher knows what to do, and I got it wrong at first (I overlooked the boxes at the bottom). 

Thanks very much

If I leave out the (plus)(+) I do get one Grosvenor Bloore on test3, but if I use the +grosvenor I get no results.

Following your example:  I put grosvenor into the forname box then I do a partial search with the **search term ending with**

I get a set of results which has a comparable set of results to  what FreeBMD1 gives me

![Screenshot 2021-07-20 173359](https://user-images.githubusercontent.com/67054943/126362145-91332698-c361-4d8f-b054-f74dc3e89c31.png)

![Screenshot 2021-07-20 174954](https://user-images.githubusercontent.com/67054943/126363976-5ec8f510-ac74-49ae-b793-6825342b2c37.png)

**Comment by Vino-S** [comment]
@AlOneill 
There is little difference where **In First Name or Middle Name** search becomes a bit more broad:
And it also works with
firstname=grosvenor smith
surname=bloore
Choose the Name field: First Name
Select one of the following: Contains or Ends with
This will give us no results

However:
firstname=grosvenor smith
surname=bloore
Choose the Name field: Other
Select one of the following: In First Name or Middle Name
This will give us 22 results

**Comment by AlOneill** [comment]
@Vino-S This is great. Thank you!

Am also loving the use of `fieldset` elements. For the sake of screen-reader users, I think we could make the first `legend` a little better. 'Main search options' is the best I have come up with so far — can anyone improve on that?

And maybe the label for the second select could be improved to be more informative? BTW it makes no sense to include the labels in the tab sequence as there is no tool-tip to view: only the select boxes need `tabindex="0"`

I will create a story for adding some guidance to Help. Although it is pretty intuitive once you get going, we do need to say something. The challenge will be to not make it sound more complicated than it is!

**Comment by richpomfret** [comment]
@Vino-S to update 'legend' - 'main search options' and 'additional search options'.

**Comment by PatReynolds** [comment]
Testing the Advanced Search Options.

I don't understand what selecting the 'wildcard' option does (intuitively, it would mean that using a wildcard anywhere would be recognised as a wildcard, but it's not that ...)

Looking for an Elizabeth Ann MARSHELL  with the search Elizabeth Ann Marshe* works fine, with 'contains' and 'first name' selected

However a search for  Eli?abeth Ann MARSHELL tells me "Search Field used for advanced search must only contain alphabetic characters" (needs revising to - possibly -  "Search Field used with a wildcard must use wildcard options (below)"

Changing the selection to Wildcard and 'Contains' gives warning "Please select a name field and a wildcard option for partial searches"

Changing the selection to First name and Contains gives warning "Search Field used for advanced search must only contain alphabetic characters" again.

Needs to be an explicit message on the search screen about what to do to get wildcard to work.

Looking for Mary Ann (or Anne) MARSHALL, baptism born before 1850, gets 29 Mary Anns, then saying middle name 'starts with' and same search, just gets 9 Mary Annes - I would have expected both Anns and Annes from a 'starts with.

Changing the search to Mary An MARSHALL gets 9 Mary Anns _all of whom have a Mary Ann as their second and third names, and a different first name, e.g. Cecilia Mary Ann Marshall DECEMBER 1841 Clerkenwell.

Searching with a name in firstname (e.g. Richard) and the 'other' and 'first name' selected finds, as expected Richard George, Richard, George Richard, etc. etc., so working fine.

Results for a search by surname COLE, mother's maiden name Marshall finds 66, name ends hall finds only 26.

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds ,

It is my understanding is that is the **old FreeBMD1** way of doing things.  BMD2 does not use those wildcard functions, they don't work, see my comments 16-days ago, above. The dropdown search boxes are used instead and they do give comparable results to what FreeBMD(1) gives with wildcards (see my comments 16-days ago, above).

Alison raised a new issue #383 to cover this.

**Comment by AlOneill** [comment]
@PatReynolds The only wildcard character in use is the * (asterisk) and **you cannot use a wildcard symbol in an Advanced search**.

The top selection, the wildcard option, sets the search to use the * in a search, as before. Picking anything other than the default for the second field is a mistake if you are trying to use an asterisk.

I think you are possibly putting too much into which ever name field you are using.

Here is my (draft) introduction to the Advanced options:

---

There is a section at the foot of the search form headed *Advanced Search options* — these will help you with those tricky-to-find records as they add power and flexibility to your search. They give you access to what are known as partial searches.

**Partial searches** work on the name fields: First name, Surname and Mother's surname.  The search looks for those names that _include_  (all of) what you put in one of the Name fields in some way, as long as you type at least three letters and do not use symbols.

There are just two fields: *Name* lets you select which part of the name to look at and the second field, labelled *Select one of the following* lets you choose the type of partial search.

---

See also Vino's examples above for more details of what to expect.

**Comment by PatReynolds** [comment]
So (for clarity) to search using a wildcard, ignore the wildcard function at the bottom and use * as in the other FreeUKGen sites.

I think we should use a different term for whatever it is that the search function at the bottom does.

Also not note: if you select 'wildcard' at the bottom, it shows 'wildcard options' to the right.  If you then select one of the others, it shows their options.  If you then select 'wildcard' again, it doesn't revert to 'wildcard options' - is that what is expected?

**Comment by AlOneill** [comment]
@PatReynolds I agree that if you return the 'Choose the Name field' to 'Wildcard' then 'Select on of the following' should revert to the wildcard options. In other words, you should be able to change your mind and not ask for a partial search — this does not appear to be possible currently.

Do not quite follow your second para. The two fields at the bottom set up a partial search; a wildcard search is a plain 'Search people', as if there were no 'Advanced' search options. Yes, the top (do nothing special here) option for the 'Choose the Name field' would be better as maybe '(none)'.

**Comment by Vino-S** [comment]
@PatReynolds 
_Also not note: if you select 'wildcard' at the bottom, it shows 'wildcard options' to the right. If you then select one of the others, it shows their options. If you then select 'wildcard' again, it doesn't revert to 'wildcard options' - is that what is expected?_
 Yes, it has to revert to 'wildcard options' as you described. I will improve the form. 
@AlOneill 
The "Wildcard" prompt on the "Choose the Name field" seems to be causing confusion, should I replace it with some other term?
Should I also create a document with examples for each Option, so that it can help with creating the SEARCH HELP page?

**Comment by AlOneill** [comment]
@Vino-S Yes, I think the prompt on the "Choose the Name field" should be changed: "Wildcard" is a different kind of thing from the other choices and it does look and function more like a choice than a prompt. If I am correct in thinking of it as an indicator of "no name part chosen so do nothing more than a standard search", then I think it should say "**(none chosen)**" or similar.
But, I might not be looking at this field correctly or in the way other people do, so, we need to know to know what others would find helpful to stand for un-choose (!) the Name part to look at.

@PatReynolds what do you think?

@Vino-S Yes, a document with examples would be a help in creating the search Help section — it would also help with testing. (I've copied your posts above but they will become harder for others to find in the future.)

**Comment by PatReynolds** [comment]
If the 'wildcard' choice just means 'don't do a partial search' then "(none chosen)".  Is fine.

I'll wait for the help before further testing.

**Comment by AlOneill** [comment]
Another snag is that the 'Select one of the following' field reverts to the top option on using the 'Revise Search' button. I keep getting caught out with that.

**Comment by AlOneill** [comment]
@Vino-S I'm pretty sure that a search on _First name_ with option 'Any' is not working quite as described above. Putting 'john james' in the First names(s) field finds the forenames John, James and John James but it fails to find the  instances of James John that a plain search finds.

**Comment by Vino-S** [comment]
@AlOneill 
It second one in the list: _vino subbu, veena vino, vino veena subbu, veena smith_
here Veena is First Name and Vino is Surname
Apologies for choosing a confusing example.

I had created the technical help document:
https://docs.google.com/document/d/175ftfCDJ4UoZiKpvSFXWSadP7-1YIc6dar7g4X9kUmw/edit#
Please let me know if any information is needed.

I will fix the above-mentioned snags

**Comment by AlOneill** [comment]
@Vino-S Thank you!

**Comment by Vino-S** [comment]
Updated the code as suggested

**Comment by AlOneill** [comment]
The top choices in the select boxes have been changed to "None chosen" and "None" — are these better than the original suggestion of "(none chosen)" and "(none)" ? The choices are retained on using the "Revise Search" button which is great.

The fieldset legends have not been changed — I believe we decided on "Main search options" and "Additional search options".

**Comment by Vino-S** [comment]
Updated fieldset on test3

**Comment by PatReynolds** [comment]
Selecting firstname starts with "ann" produces a middle name of Ann [image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/98952bba-8418-4b65-93a9-398ebfb83340).

The use of 'exact match' is confusing me: this search
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/f33f1509-0700-4870-8a1f-8c91b0825cd9)
produces 2 results, but if the 'exact match' is not ticked, more results (with middle names) appear.
Information is "Exact match on first names" - should that be "Exact match on first name. Excludes entries with middle name"?  
To bring surnames info into line "Phonetic search of surname" perhaps (should definitely, I think be surname singular).

Other than that, the instructions suggested by @PhilipClarke712 are good.  Examples  (with screenshots) would be helpful.

**Comment by PatReynolds** [comment]
@PatReynolds to take another look and clarify what is needed.

**Comment by PatReynolds** [comment]
Anne does NOT find Ann or Anna or Annie.

Ticking "exact match on first names" excludes those entries for Anne with a middle name/initial.
Not ticking "exact match on first names" excludes variant spellings, but does include identical spellings also with middle names.  However .... a search for Ann finds Anne, Annie, etc.

Works the same on FreeBMD1 and FreeBMD2.  

Joe finds Joe and Joel, but does not find Joseph

So ... normally, FreeBMD returns "names beginning with characters as typed" and ticking the box means "name as typed, with no additional characters at all, not even a second name".

Since this is what FreeBMD1 does, this is fine for FreeBMD2.

#399 has my thoughts on improvements., including renaming feature as stands "excact match on names with no second name or initial".
