### ISSUE TITLE
Write sub-page  ABOUT The Current Team and Management structure (public page)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#304]
Current DRAFT is taken from FreeREG.  There is also a page DRAFT About Us.  Introductions to the Project Team.  which is very out of date - much is now History - some needs incorporating here, and some on FreeUKgenealogy.org.uk

Include on this page link to the FUG website page on the Team.

Remaining issues
 - [x] corrections needed to personnel
 - [x] contact details
 - [x] conformance to style, typos, etc.
 - [x] make th page sync-ready

**Comment by PhilipClarke712** [comment]
@PatReynolds 

Firstly, unfortunately I don't know what FUG is, so I can't do anything about that.

There are numerous problems with this page, as a whole. As you say, the current draft appears to have been taken from another site. The individual pages from FreeBMD(1) identified in the hyperlinks audit were moved onto Refinery back in May to June but have never been incorporated into the draft page and another FAQ page was created and also moved into Refinery but never incorporated; and all the FreeBMD(1) pages did not use active-case and the new guidance issued in October requires active-case. 

So, there are currently three inductions to the Current Team and I think two to the current management structure (which may be in the wrong case - non-active). Comfort and I, via Git, were asked to give priority to Help pages  and some of the About pages that were allocated to Transcriptions, so I don't think any editorial work has been done on the About tag, other than on the FAQ page; and that FAQ page is fairly close to completion. The FAQ version of about the Current Team, may be the most update, but it is un-liked to the top-level page. Many of these problems are common to the Help page.  

Can you advise where the most up to date version of the Current Team and Management structure can be found?

**Comment by PatReynolds** [comment]
First draft done.  Remaining work noted aboce.

**Comment by PatReynolds** [comment]
For discussion: I have removed most of the contact details because I believe this is intended to be a publicly facing page -  contacts for volunteers will be developed as another task (would need a new story creating).

**Comment by richpomfret** [comment]
@AlOneill to proof it and @PatReynolds to create the new story.

**Comment by AlOneill** [comment]
@PatReynolds I will assume, unless I hear otherwise, that this is the page you wish me to proof:
https://test3.freebmd.org.uk/cms/about/draft-about-us-introductions-to-the-project-team

There are some unexpected issues with this page, which is why I am asking if I'm looking at the correct one:

* `h1` heading includes two full-stops, i.e. "DRAFT About Us.  Introductions to the Project Team."

* top level heading used in Refinery is `h3`

* no layout

In addition, the casing of "linBMD" is different from the casing of other project software such as: WinBMD, MacBMD and so on. It does not seem to be a Linux thing to use lower-case like this, so I'll change it to LinBMD (which is incidentally easier to parse in a sans-serif font).

I was taught that a page should still make sense if all the headings are taken away (because it would be a mistake to read the headings out loud). That could be an old-school way of looking at things, but I'll expand the opening sentence of each section so that it can stand alone without any loss of information or meaning. And after all, the actual content is pretty sparse.

**Comment by AlOneill** [comment]
@PatReynolds 

Initial checking of page completed. The address is now (provisionally): 
https://test3.freebmd.org.uk/cms/about/draft-introducing-the-project-team

Issues noted above have been fixed. There are two queries near the top of the page — both are marked with highlighter.

The other thing to consider is whether and how we use **email links** — there are pros and cons. (There was one malformed email link already on the page, so I've marked up both addresses to be valid, at least for now.)

* selecting the email link is convenient if you use an email client (e.g. Mail or Outlook) but might produce an unhelpful result if you do not. For instance, opening Mail and asking if you want to set up an account
* mobiles should be OK — they will take a user to the default app, whatever that is
* copying an email address from the link is possible but awkward for some
* will our users be familiar enough with the vagaries of an email link on their device to not let any odd behaviour bother them?
* it might be better for desktop and laptop users if we ditch the email _links_ — but how awkward would that be for mobile users, if at all?

**Comment by PatReynolds** [comment]
FreeBMD1 links to a form - which might be more convenient for all?

**Comment by PatReynolds** [comment]
@PatReynolds to check how this operates on mobiles.

**Comment by AlOneill** [comment]
@PatReynolds I have un-linked the second email address so that you can compare the two approaches.

**Comment by PatReynolds** [comment]
On Chrome the 'mail to trustees link' does not engage with Gmail. But the address can be copied and pasted.  I much prefer the 'unlinked' version of presentation of information used at the bottom of the page.

Test on Android showed first type opens up gmail with the correct address.  The bottom of page version of the markup offers a choice of gmail, copy, share or "select all".  

Because of increased ease of use on Chrome, and increased range of utilities on Android, I suggest we go with the bottom of page implementation.

Minor edits made where requested,

**Comment by AlOneill** [comment]
@PatReynolds 

Thank you. I've removed the link for the first email address.

Next I'll make the page sync-ready which will include listing a link to it in 'Related pages' on the About page. Let me know if that is not what you want.

**Comment by PatReynolds** [comment]
Thanks, @AlOneill yes, that's what is needed.

**Comment by AlOneill** [comment]
@PatReynolds Thanks. Pages — this one and About — now sync-ready.
