### ISSUE TITLE
Searching for a marriage with Spouse's surname "breaks" test2 & 3

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#307]
I searched for a marriage of named person within a 12-month period and I got 75 "hits" one of which was the one I wanted. 

So I Revised the search and added a Spouses surname. Nothing else was changed.

test3 came up with: _We're sorry, but something went wrong with processing your request. A report has been produced and sent to the webmaster. Please return to your prior activity but try to avoid doing the exact same action again._

Test2 came up with: _NoMethodInSearchQueriesController#Create
Extracted source (around line #1572): 
    records_with_spouse_surname = spouse_surname_records(records)
    records_without_spouse_surname = non_spouse_surname_records(records)
    spouse_surname_search(records_with_spouse_surname) + search_pre_spouse_surname(records_without_spouse_surname) if self.spouses_mother_surname.present?
  end_

  def spouse_given_name_filter records

**Comment by richpomfret** [comment]
@Vino-S to take a look.

**Comment by richpomfret** [comment]
@PhilipClarke712 can you take a look and see if this is fixed?

**Comment by PhilipClarke712** [comment]
@richpomfret 

It works perfectly well now on **test3**: I can search with just two surnames, or one first name & surname plus a surname, (provided I limit it, say between two dates). It finds a marriage or marriages and they are viewable. That is I get the Entry Information page for the first Entry; and if I click on the Page No. I get to see four names (assuming it's two marriages to the page).

On **test2** the same search will find a marriage or marriages, but if I click on a view button it crashes with a "NoMethodError in BestGuess#Show.

Since test3 works, the problem has been solved (I don't know why test2 is different).

**Comment by richpomfret** [comment]
Thank you. Now closing.
