### ISSUE TITLE
FreeBMD2 fails to indicate that a marriage entry was Registered by the GRO in the form "Smith or Jones" for spouse's name

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#308]
I wanted to check out searching for marriages where a page number has UCFs (uncertain character format), so I started looking at some of the marriage files that I had transcribed; and I got side-tracked onto this particular topic.

The page 1950-M1-B0086 has an "entry" of the form:
Betts, William R., McCarthy, Southwark, 5d, 1222
#Comment(2) entry reads McCarthy or Taylor for Spouse's name
Betts, William R., Taylor, Southwark, 5s, 1222

and on FreeBMD1 it is displayed as: 
![William Betts](https://user-images.githubusercontent.com/67054943/106935508-58653780-6713-11eb-8fd3-9d2f4371ad3c.png)

The FreeBMD1 Entry information page has: 

Betts | William R. | Taylor | Southwark | 5d | 1225 | prclarke |  
 #COMMENT entry reads McCarthy or Taylor for Spouse's name.

I don't check the FreeBMD1 Entry information for the other William, but the same Comment is likely to be there.

In Contrast: if I do a search on FreeBMD2 test3 for William R. Betts in March 1950, I get only two results: "our William".
If I go to the Entry Information page for the first William, his spouse is McCarthy.
If I go to the Entry Information page for the second William, his spouse is Taylor.
If I click on the Page number there are six entries: two for William, one for Jean A Taylor, one for Jean A McCarthy, another "man" and another "woman".

We have "thrown away" / neglected to display / not yet implimented the ability to display the COMMENT for William: entry reads "McCarthy or Taylor" for Spouse's name. 

Note: there is an earlier entry on the same Index page (not the same Register page):  Lamb or Betts or Sandilands.
Both of these can be found by looking at the Scan of the index.

Anyone not looking at the scan image on FreeBMD2 would be unaware that there was only one **William** and only one **Jean** and, by inference, that William _might_ be Jean's second husband.

**Comment by PatReynolds** [comment]
View is comparable.  What is missing from FreeBMD2 in this instance is the #Comment accessed via the question-mark symbol on FreeBMD1.

This is not just about marriage partners - all comments are missing - see for example marriage of  Richard George Alcock DECEMBER 1881 and 
Newark and birth of Edith Alcock DECEMBER 1891 Malton.

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds ,

My thoughts: FreeBMD(1) and FreeBMD2 display things differently and I know that the "look and feel" of FreeBMD2 was designed using wireframes (if that is the right terminology), but those are not something that I would necessary see (or have access to).

If FreeBMD 2 worked the same way as FreeBMD1 then this screen capture would have another column on the right with either symbols or words indicating that there are: Postems, Comments (such as Smith or Jones) and Late Entries, etc. associated with a particular entry.

![image](https://user-images.githubusercontent.com/67054943/114393485-f6510480-9b91-11eb-8035-aba820776c5b.png)

The FreeBMD2 Results page does not have such an third column, so I just assumed that these symbols or words were being done at the level of the Entry Information Page, not on the Results page level (and this appears to be the case now for Late Entries).

If we take the example of the birth of William E Betts:

![image](https://user-images.githubusercontent.com/67054943/114396189-2e0d7b80-9b95-11eb-899f-5dba382828c5.png)

The FreeBMD(1) Entry Information page has the information **The above transcription represents what is in the GRO index but it is referred to by the following entry: Births 1904 Sep: BETTS, William E,Wellingbro',3b,S/34**

 FreeBMD2 **has implemented** this Late Entry on the Entry Information Page, not on the Results page.

So, on that basis, those two two 1950  marriage Entry Information pages for William R Betts (above) should be implementing the equivalent of  the FreeBMD(1) "**COMMENT entry reads McCarthy or Taylor for Spouse's name"** against each entry on the two Entry Information pages and they don't appear to do so. 

Note: as Researcher, I would prefer to see this information (in summary form) on the Results page, but it could go on both individual Entry Information pages (this is a design question - it could go on all three pages e.g. the Results Page and both Entry Information pages).

There are very few Postems on the the Database being used on test2 & 3 so I have not found any yet. Postems need to be displayed, as per alternative surnames, and suspect page ranges, etc; and it appears to be the Entry Information page where they should go.  

I've not checked another other Late Entries - but FreeBMD2 does appear to have addressed the Late Entry for William E Betts (in 1904 and 1934).

**Comment by PatReynolds** [comment]
Hello Philip, yes, the comments, scans, etc. are now all on Entry details pages (logic being that you would not use these to do a first-level identification of an entry warranting further investigation).  

Since both in FreeBMD1 and FreeBMD2, the user has no idea that there is a doubt over the surname of the partner, without clicking through to the entriy infomation, I don't expect user testing to suggest that anything more is needed on the results pages (but could be wrong!)
