### ISSUE TITLE
Add 'Volunteer as a transcriber" to Refinery

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#310]

**Comment by PatReynolds** [comment]
Completed?

**Comment by PatReynolds** [comment]
No, still needs adding.

Also pathway needs to be confirmed (email sent with a link to 'choose a syndicate' on FreeBMD1 - https://www.freebmd.org.uk/Signup.html

**Comment by PatReynolds** [comment]
Draft here: https://docs.google.com/document/d/1FtJLpqm4eNbblYT8aUVnQ4-PKhMmh_P05AOB69PJZPE/edit?usp=sharing

**Comment by richpomfret** [comment]
@DeniseColbert to review for content and @AlOneill for typos.

**Comment by AlOneill** [comment]
No typos! (E&OE)

**Comment by DeniseColbert** [comment]
Comments made. 

This looks like an emailed response to the prospective volunteer's expression of interest. Is that them completing the form on the volunteer page? If so, we may need to modify the form (remove "Syndicates Available"?) Also, if they complete the form and then sign up via BMD1, are we able to attach their TA answer to their account?

**Comment by richpomfret** [comment]
Next step is to move this onto Refinery.

**Comment by PatReynolds** [comment]
Some thoughts here - for discussion in Scrum https://drive.google.com/drive/folders/1b5-6aor-79IzOpAPe20Qf3wddQAnzJoX?usp=sharing

**Comment by richpomfret** [comment]
We took a look at this in the meeting, but would like @Vino-S to also read through and comment where applicable.

**Comment by richpomfret** [comment]
Good to go. Moving to be deployed.
