### ISSUE TITLE
Search not working on mobile phones

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#315]
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/ffc5d0c6-c34d-475f-959f-b0d32079941e)

The search button bar  is now 'pinned' to the bottom of the screen, and does not work.

**Comment by Vino-S** [comment]
Ready for testing in test2

**Comment by richpomfret** [comment]
@PatReynolds and @richpomfret to test.

**Comment by PatReynolds** [comment]
Still pinned, but now works.

Advantages to the pinned search:
* it allows the user to skip to the search as soon as they've entered what information they think will get them to a reasonable number of records.

(Possible) disadvantages to the pinned search:
* it may cause conflicts with a pinned advertisement. 
* if there is no conflict with a pinned advertisement, it may take up in total too much screen space on a small phone
