### ISSUE TITLE
test2 & test3 Results pages hyperlink to wrong district on UKBMD

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#325]
I would note that Test2 & test3 Results pages have the wrong Registration District hyperlink for **Weston** (or Weston_Super_Mare, if you prefer): the District (Weston) is correctly displayed on FreeBMD1, test2 and test3 Results Pages.
FreeBMD1's was the only hyperlink that took me to https://www.ukbmd.org.uk/reg/districts/weston%20super%20mare.html -  which is where I should be.  Test2's and 3's took me to https://www.ukbmd.org.uk/reg/districts/welton.html - a typo presummably in the hyperlinks.

Expression of Bias: I must admit I find the test3 drop-down year-selection method  much faster than test2's. I was looking at post-WWII records and I can get there faster on test3 by dragging the bar than I can on test2 (either by repeated clicking, or holding down my left mouse botton - both work).

**Comment by PhilipClarke712** [comment]
Sorry, I found another one.

The record was transcribed with the District name of **Littleboro'** (as per the transcript) and on FreeBMD1 that same record would take you to https://www.freebmd.org.uk/cgi/districts.pl?r=203971021:3200&d=bmd_1612775592 , which has a link to https://www.ukbmd.org.uk/reg/districts/littleborough.html
FreeBMD2 goes directly to https://www.ukbmd.org.uk/reg/districts/littleboro'.html which produces a 404 error on UKBMD. This FreeBMD2 process does not seem to address the problem of **alternative names for Districts**: the district link should go to https://www.ukbmd.org.uk/reg/districts/littleborough.html

**Comment by richpomfret** [comment]
Thanks @PhilipClarke712, we need to find a method of determining/finding such broken or incorrect links before we go live.

**Comment by PhilipClarke712** [comment]
I'm going to give one final example: **Kings Norton** works, but **King's N** and **Kings N** cause UKBMD to fail with a 404 error.
So Weston going to Welton was probably a simple typing error. Littleborough and Kings Norton are two cases where the official District name **does work**, but the alternative names **don't** (see https://www.freebmd.org.uk/DistrictInfo.html )

**Comment by PatReynolds** [comment]
The problem is how the generator interprets full stops, lack of spaces, and abbreviations in the name, e.g. W.Derby links to 
https://www.ukbmd.org.uk/reg/districts/w.%20derby.html (which is not a UKBMD page)
and should link to
https://www.ukbmd.org.uk/reg/districts/west%20derby.html

NB
If our link is https://www.ukbmd.org.uk/reg/districts/wderby.html, UKBMD unhelpfully interprets it as https://www.ukbmd.org.uk/reg/districts/derby.html so spaces need to be added

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
Thanks, @Vino-S working as expected now.

**Comment by PhilipClarke712** [comment]
Hi @Vino-S ,

I will have a look later today, probably in about 2 or 3 hours.

Hi @PatReynolds ,
I've been transcribing for FreeBMD for almost exactly 11 years, so I know that there is a District Alias team, lead by Martin Cope (I offered to fill a vacancy, I suspect about 5 to 7 years ago, but I was too slow off the mark and it was filled before I applied).

So I suspect that is where https://www.freebmd.org.uk/district-list.html ,  https://www.freebmd.org.uk/district-map-alt.html and https://www.freebmd.org.uk/district-map-all.html get populated. 

Without knowing how the URL generator works, I suspect it just takes what it was given. So if it is given "W. Derby" if puts that into a field within the UKBMD address string and that can crash UKBMD if it is not a proper district name.

It appears to me that there aught to be an intermediate step: take the field that it is given, go the FreeBMD's District-map list to convert that to the matching _official district_ name and put that into the URL generator. So, e.g. all our **King's N.**  **Kings N.** get converted into **Kings Norton** and that is what is put into the  URL generator.

Fortunately, I don't have to do the coding ( I'm not competent).

**Comment by AlOneill** [comment]
@Vino-S FWIW, I can confirm that the correct district is being found now.

The link still needs a warning — somehow and somewhere! — that it will open in a new tab. Perhaps there is already a story for that?

**Comment by PhilipClarke712** [comment]
Hi @Vino-S ,

1. I agree with Pat and Ailson, I've looked at quite a few abbreviated districts and they all now link to the correct page in UKBMD.

2. In respect of Alison's comment about the need for a (open in new tab) warning, that has been addressed already for Districts on the corresponding Entry Information pages, but **not on the Results Pages**.
