### ISSUE TITLE
"Clear Form" doesn't work when Revise Search has been clicked

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#326]
Link next to search button doesn't work when a search has been performed and Revise Search selected.

A black box appears around it when clicked, but nothing happens.

**Comment by PatReynolds** [comment]
@Vino-S to take a look

**Comment by PatReynolds** [comment]
Takes you back to search form, but the form is blank.

**Comment by richpomfret** [comment]
Fixed. Closing.
