### ISSUE TITLE
On multiple event search, record type is blank in grey box

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#331]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/685c5b36-2ecc-48b6-b278-e28f3b7dc20a)

**Comment by PatReynolds** [comment]
@Vino-S to chec, and feed if need be.

**Comment by Vino-S** [comment]
ready for testing in test3

**Comment by PatReynolds** [comment]
@PatReynolds and @DeniseColbert to test

**Comment by PatReynolds** [comment]
Working fine, thank you @Vino-S 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/7cb8ed9c-bf7a-4c64-ba6f-f98e8a779197)
