### ISSUE TITLE
Design question: "Report an Error in this Data" - Button?

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#333]
This is what the Report an Error in this Data button looks like on FreeREG:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/e670aa6e-9844-488f-b437-768d9149866a) 

...but as you can see from FreeCEN, we just use a link there:
 
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/8c355261-92c3-4de6-ab98-7f47b2825515)

FreeBMD1:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/4a795763-5bdf-4db6-b4d6-b4e440e1d4d3)

How and where do we want to show this on FreeBMD2?

**Comment by richpomfret** [comment]
Discussed - let's go with a button as in FR. We should also move this into SystemWide and update FC also - although note that the positioning of the button should include more space above the button.

**Comment by KristinaGadzhieva** [comment]
Not relevant for MVP.
