### ISSUE TITLE
Image table on t3 has been replaced with images from REG and some Refinery pages are missing

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#335]
The Image table in Refinery has names of image files but there are no thumbnails and all the names look like those on REG.

One Refinery page was definitely missing (I've since recreated it); it looks as if a bunch of other pages are also missing.

I suspect this has to do with recent software updates.

**Comment by PhilipClarke712** [comment]
Hi @AlOneill ,
Well spotted. It's more serious than that.

I've lost every image and every Draft-html page that I have put on the system, plus the ones that Comfort put on. That's a year's worth of work gone from Refinery.
I hope that files are backed up on the system somewhere: I have the original images on a local machine, but I don't keep copies  (of the source or body) of html pages.

Note: I've had other commitments, so I've done little or no Refinery work for a couple of weeks. If say, there were four-week-old copies of all these files, I could cope with that. That would probably just mean the lose of one complete draft-page, plus Alison's review and some corrections to another page.

**Comment by Vino-S** [comment]
Hi @AlOneill , @PhilipClarke712 
The Refinery pages and images are intact in the [Vervet.](https://test3.dev.freebmd.org.uk/cms/refinery/pages). These need to be moved to the rails1 server. 
I Will let you know once done.

**Comment by AlOneill** [comment]
@Vino-S that's a relief! Apologies for the panic.

**Comment by Vino-S** [comment]
Hi @AlOneill , @PhilipClarke712 
@lemon-ukgen had transferred the Refinery content from Vervet to rails1. 
Missing content should be now visible in  [test3]( https://test3.freebmd.org.uk/)

**Comment by PhilipClarke712** [comment]
Hi @Vino-S , @lemon-ukgen , @AlOneill 

Yes!
As far as I can remember all the html pages and images are back in their correct places. I've not tried to edit them, but I can read them and the hyperlinks work.  Thanks very much.

**Comment by AlOneill** [comment]
@Vino-S @lemon-ukgen lem I can confirm that the Image table has been restored — thank you!

@PhilipClarke712 I have restored the markup guide to the 30 Mar (latest) version.

**Comment by Vino-S** [comment]
Done.Closing it
