### ISSUE TITLE
FreeBMD2 test3 (& test2?) miss-reports deaths for post-1983 records as occuring in March of the year and misses out (actual) Registration date

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#339]
Ted Southcombe raised on discuss@freebmd.groups.io , an enhancement request for FreeBMD(1) in respect of reporting death records for deaths from 1984, forwards.  In effect, asking if the FreeBMD Results page could be modified to provide information that is only given on the individual Entry Information pages.

I was not expecting to find any such "modern" deaths on test3, baring in mind the data-set, but I found just over 520 death records  for 1984 and 1985, in total on test3. 

In respect of the ones I looked at the Entry Information pages on test3 : all the Entry Information pages were of the form: 

![Screenshot 2021-04-21 204004](https://user-images.githubusercontent.com/67054943/115611368-e6e46080-a2e1-11eb-86c9-1b02fb164688.png)
![Screenshot 2021-04-21 204212](https://user-images.githubusercontent.com/67054943/115611543-20b56700-a2e2-11eb-8c9f-3f8f5ecbd82d.png)

**Note:** From the start of 1984 forwards to (1992 for FreeBMD1) t**here are no quarterly GRO indexes, only annual indexes** and the **Annual index gives the month of the event** in the form say, 01.86 (January of 1986).

In the case of the first example **Fred Ager** the FreeBMD1 search page gives: 

![Screenshot 2021-04-21 204419](https://user-images.githubusercontent.com/67054943/115612053-c10b8b80-a2e2-11eb-8279-4701b09b18db.png)
and I think test3 has "converted" this in a March death .

The FreeBMD1 Entry Information pages gives that actual month of death, which is this case would be a Q1 event (but the GRO does not use quarters): 

![Screenshot 2021-04-21 204930](https://user-images.githubusercontent.com/67054943/115612654-69215480-a2e3-11eb-9f29-622a7c257696.png)

For my second example, for one of various Winifred Allen deaths in 1985, FreBMD1 comes up with:

![Screenshot 2021-04-21 205530](https://user-images.githubusercontent.com/67054943/115613715-a9cd9d80-a2e4-11eb-9f76-4a9c29fa5382.png)

Looking at the last entry: **Winifred Sarah R. Allen**'s Entry Information page on FreeBMD1 gives her month of death as: 

![Screenshot 2021-04-21 210254](https://user-images.githubusercontent.com/67054943/115613995-04ff9000-a2e5-11eb-91ca-fc489ed15f30.png)

that is, December 1985, but test3 still considers it to be March (or March Quarter) death of 1985 - note the year is right.

**Comment by PhilipClarke712** [comment]
I don't know how this is be addressed, but potentially there are two problems that need to be addressed. Quarter and Year just becomes a Year and there is a new field: the **Registration date** (month + year) which is not visible in the results.

The **Results page** for pre-1985 records displays an individual as three lines in a box:
 Joe Bloggs   (his name)
June 1888 (June here is the June quarter, or 2nd Quarter, not the month of June, and 1888 is the year).
W.Bromwich (in this case an abbreviated District name)

The **Entry Information page** for this result would have a date of June 1888 (again, June here is the June quarter, or 2nd Quarter, not the month of June, and 1888 is the year).

If this event took place 100 years later, say in 1988. Then the GRO index would be for the year 1988, FreeBMD2 test3 appears to convert that year to  **March** 1988 (every post record 1984 appears with a March quarter). FreeBMD(1)'s implementation appears to blank out the quarter and just give the year, in this case 1988. That implementation would address half of the problem.

The other half of the problem is that from 1st January 1985 Joe Blogg's event was indexed in the Annual index and there is a new field the Registration date of the event. Joe's birth, marriage or death was Registered in August, so that was indexed as **08.88** and this field is not currenly shown on FreeBMD2 test3.

To me, there are potentially two solutions: for post-1984 indexes, but I don't  know how the database stores this data:
 (1) The **Date** (quarter + year) from the GRO index, on both the Results page and the Entry Information page are replaced with the Registration date given in each record, so in this case 08.88 = August 1988. We don't appear to be indexing post-1992 indexes, so the year date-range is just .85 to .92 = 1985 to 1992. This might confuse a Researcher, who would normally expect to see just the _months_ of March, June, September and December in the date field.
 (2)  The **Date** (year only) from the GRO index, on both the Results page and the Entry Information page  are displayed as just a year-date; and a new field (perhaps) called **Registration date** is added to the table in the Entry Information page, (and the Results page?) which is blank for pre-1985 records and is populated for 1985 and later entries.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richpomfret** [comment]
@PhilipClarke712 can you take a look and test this?

**Comment by PhilipClarke712** [comment]
@Vino-S 

Sorry for the delay in looking at that this. It is partially fixed, but not entirely.

I used the Fred Agar result(s), above - there is also FREDERICK HUBERT LAMBERT AGAR death in 1984 - and the various Winifred Allen deaths in 1985.

The **Results page** has been fixed, for all these post-1983 entries the - Results pages just give the Year, not the quarter and year as per pre-1984 indexes.

The table in the associated individual **Entry Information pages**, has a **Date** line and in all the examples above are given as either MARCH 1984 or MARCH 1985. Almost at the bottom the table is the Registered Date, in the form month and year e.g. 06.85. Post-1983 indexes do not use quarters, the are annual indexes, so March will _right_ in only 25% of the time.

The simplest fix might be to change definition of the post-1983 **Date** field to display only the year (as a four digit number). An enhancement for post-1983 records would be have a magenta "i" button referring the researcher to the **Registered** line, below, which gives the month of registration.

**Comment by Vino-S** [comment]
Made the changes. Still need to decide the content of info button

**Comment by richpomfret** [comment]
@Vino-S Need to reorder the table.

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 

These latest changes show the desired presentation of **Date** (of the event) on both the Results and Entry Information pages for post-1983 records.

My suggestion for the button, would be: Starting in 1984, the indexes were issued yearly  - instead of quarterly - and they now have an entry showing the month (and year) of Registration of the event (birth, marriage or death).

There may be better ways of phrasing this, but that is the information that I think we wish to impart to researchers.

**Comment by PatReynolds** [comment]
@AlOneill  can you reduce the length of the infobutton text?  Perhaps with a link to this text (added to the Help page

**Comment by AlOneill** [comment]
Could someone please clarify where this info-button will go? Are we talking Search form or Results table or Entry Information?

Also, I do not know how we would make a link in an info-button (tooltip) accessible to a sighted keyboard-only user.

**Comment by PhilipClarke712** [comment]
@AlOneill 

1. Going back to the **Frederick H L Agar** death search I mentioned above . If I search over the whole of 1984 & 1985 on test3. I get one Hit: the Results page dates the event to 1984; as does the Entry Information Page. The latter has as **Year** line  with the value 1984 and a **Registered** line with the value 02.84. 

If I did not know what "Registered" meant - it would help my understanding if the Entry Info page had an info button  telling me that: (this was an an annual index) which had a extra peace of information which gave the month of registration of the event (it's the month and the year in two-digit form). So, placement could be near year box, or better still Registration box.

2. That makes two of us. I don't even know how I could do a search on FreeBMD1/2 with my computer's monitor turned off. How do I know what input is needed and were to put it. (Not very helpful, I admit).  
 
 So, I put the search term into google and that is (apparently someone who can't use a mouse). But, they can it appears use a tab key. In the old days, a computer program could "branch" depending on what the input was. So search for a tab input (in the old day an ascii code). A tab is a different code to End of Line (implemented in those days as C/R + L/F ) and if one is found, display (or speak) what is in tooltip.

**Comment by AlOneill** [comment]
I agree that the **Entry Information page** would be the best location. The hint needs to be in plain sight: we have not got `.tooltip` to work well in a table.

So, I suggest a strap-line in the *Registered* cell, something along the lines of one of these (any link text in bold):
1. For more information, see **details of months and quarters**
2. From 1984, the Index was put together yearly, by month of registration

**Comment by PhilipClarke712** [comment]
Yes, I would agree with most of that, however it is only post-1983 Entry Info pages that have the Registered cell; and the Year cell is either Qtr and year or just year, depending on the time-frame.

(1) If my Entry Info Page refers to a pre-1984 result then the Year box will state: December 1912, June 1914, etc. and we need to inform the user, **somewhere**, that those results mean (4th Qtr 1912, or Oct-Dec 1912); or (2nd Qtr 1914, or May-June 1914), respectively. 

Your suggested strap-line **1** may be all that is needed, but see below.

(2) If its a post-1983 record, then the Year box shows only the year and the Registration box appears as (mm.yy).

I have reservations about your 2nd line and suggest, instead: **2.** From 1984, the Index is yearly, with a new field (or synonym) giving/showing date of registration as (mm/yy). - I tried not to make the strap line too long.

With the tooltip in a table problem, we could presumably make the name of the Year cell (not its value) a hyperlink and point it to https://test3.freebmd.org.uk/cms/help#gtkResults  - **the Good to know — about the the results page** section.  We could do the same with the Registration cell, but info on that topic would need to be added to the page. Is there a preference between tooltip vs. hyperlinking the name of a cell to an existing Help page?

Alternatively, Sometime in the future we might be able to point them to  https://test3.freebmd.org.uk/cms/help-superseded-or-draft/draft-understanding-the-gro-index-page - but that page does not have a story (it was put on using the story for putting pages on from BMD(1) ), has not been reviewed, but there is scope for expanding it to cover the info that the FreeBMD2 Entry Info page is now showing.

**Comment by DeniseColbert** [comment]
New story #409 to discuss display of Registration field

**Comment by richpomfret** [comment]
Is this story still needed? Or has it been replaced by the new story Denise created? @AlOneill it would be fantastic to get your input.

**Comment by richpomfret** [comment]
@PhilipClarke712 would be good to have your input too in terms of actions for this particular story.

**Comment by PatReynolds** [comment]
Action points now covered as story #409, so closing.
