### ISSUE TITLE
Enhance searching by districts

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#343]
https://test.freebmd.org.uk/trac/ticket/545 - currently searching by districts is only by a standard term, which is sometimes comprehensible (e.g. a search for Bloosbury in the drop-down list will not find it, because although the district name is "St. Giles and St. George, Bloomsbury", the name n the list is St Giles.

**Comment by PhilipClarke712** [comment]
It appears that the name of the civil parish (and eecleasiastical parish) is being considered to be identical with the name of the Registration district, **and it was not the case**. All the documentation on FreeBMD(1) and 2 warn that they are not necessarily the same areas.

In this case the name in the list, **St Giles**, was the name of the Registration district for the marjority of its life: **1st April 1838** to 1st 1930.

The original registration district of "St. Giles in the Filelds & St. George Bloomsbury" or "St. Giles & St. George" was only in existence for nine months (1 July 1837 to March 1838) and it **only covered** the ancient parish of St. Giles in the Fields - which was in the civil parish of St. Giles in the Fields & St. George Bloomsbury  (see https://www.ukbmd.org.uk/reg/districts/st%20giles.html ). There was another registration district of **Bloomsbury,** which was also in existence for nine mouths https://www.ukbmd.org.uk/reg/districts/bloomsbury.html which **covered only** the ancient parish of St, George Bloomsbury - which was in the civil parish of St. Giles in the Fields & St. George Bloomsbury.

The Registration district of **St Giles** created on 1st July 1838 appeared to cover the whole of the civil parish of St. Giles in the Filelds & St. George Bloomsbury. It was abolished in 1930 to become a larger district of https://www.ukbmd.org.uk/reg/districts/holborn.html 

There is a warning about confusing the name of the Civil Parish or place with the name of the Registration District. King's Norton for instance is a Parish, with a church, originally in Worcestershire, but is now a suburb of Birmingham. Kings Norton and Northfield was an Urban Union, a union of two villages, and there was also a Workhouse Union and Registration District of Kings Norton, which covered parts of three counties (Worcester, Warwickshire and Staffordshire). Geographically the village of Kings Norton is just a small corner of the Registration district of Kings Norton.

**Comment by PatReynolds** [comment]
Hi @PhilipClarke712 I think you mean in the dropdown list of districts when "London (to Mar 1965) (LND)" is selected, so the requirement is to rename 
St Giles to St Giles (to ?Apr 1930) (just checked against FreeBMD1 and it is Mar 1930
etc

Is that the case?

**Comment by PhilipClarke712** [comment]
Hi @PatReynolds,
 Sorry. That **?** was a reminder to me to check the date: both Bett Langstone, "A Handbook to the Civil Registration Districts of England and Wales", 2nd Ed.  and UKBMD (https://www.ukbmd.org.uk/reg/districts/st%20giles.html ) give the date of abolishment as the 1st April 1930, but UKBMD also records that St Giles lost its constituent parishes on 31st March 1930.

It gets a but messy but:  rename St Giles to  **St Giles (to Mar 1930)** . It needs to be in the drop-down lists of both the counties of London and Middlesex.

**Comment by PatReynolds** [comment]
@Vino-S to take a look

**Comment by richardofsussex** [comment]
I'm not at all clear what this issue is actually trying to achieve. If we remove the discussion of the historical changes to Districts, and the discrepancies between Registration Districts and civil parishes, what are we left with? If searchers filter by the "wrong" district, there is nothing we can do about that.

Is the requirement simply to have more precise district names, including dates when they were valid, in the drop-down list? Or something else?

The only concrete suggestion I would make is the selection list could have an autocomplete aspect to it, so that if you type "Giles" the list would contract to show only names containing "Giles". That would get around the problem discussed above, but then as I said it's not clear [to me] if that is actually the issue.

**Comment by PhilipClarke712** [comment]
Yes Richard, you've 'hit the nail on the head': it's a discussion without a a precise action. 

The 'problem', might be addressable by a reference to a help page (topic: searching), or one of those buttons that can be hovered over (can't remember what we call them).  But, that brings in a question of how fuzzy is the search, or how fuzzy we make it, e.g. I could look for my grandfather Fred across Birmingham, N. Birmingham and S. Birmingham (all valid Districts sometime over the last  two centuries, or more); or using Birmingham, Kings Norton, and West Bromwich - provided I know I can do that): but if I use the wrong District, I may not find him.  In respect of auto-fill There are the difficult Districts: if, say I start typing Birm... would an auto-fill suggest North Birmingham, South Birmingham, or just  Birmingham; or if I start typing Derb... would it suggest West Derby (now part of Liverpool and not in Derbyshire). 

Perhaps, if there is agreement, close this story.

**Comment by DeniseColbert** [comment]
Closing: new story for autocomplete in Districts and Counties
