### ISSUE TITLE
Change text showin in 'Districts' when Yorkshire is selected as the county

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#344]
Currently, when Yorkshire is selected as a county, the District list shows YRK

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d90de36b-451b-43f5-a06e-a844e10cca0e)

This should be changed to something along the lines of
"Please select a County/Riding of Yorkshire to see a list of districts in that part of Yorkshire"

**Comment by PatReynolds** [comment]
@PatReynolds to test again once updated by Vino.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
Yorkshire is no longer showing as a county.

Text needs to say: "Please select a County/Riding of Yorkshire to see a list of districts in that part of Yorkshire.  Searching Yorkshire searches the whole count. "

**Comment by PatReynolds** [comment]
@PatReynolds to check/close

**Comment by PatReynolds** [comment]
Now counties are split, working on Beta as expected, so closing
