### ISSUE TITLE
Remove places from search for which FreeBMD does not have the data (e.g. Ireland)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#345]

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richpomfret** [comment]
@PatReynolds to take a look.

**Comment by PatReynolds** [comment]
Take out 'England'

**Comment by PatReynolds** [comment]
Tested, now working as expected.

**Comment by PatReynolds** [comment]
Sorry, England still there!

**Comment by PatReynolds** [comment]
@Pat to check whether there are any cross-border districts:  there are we need to remove England, if not, either remove England, or  add 'skip to Wales' above it, and list Welsh districts separately.

**Comment by PatReynolds** [comment]
Yes some districts England/Wales are cross-border - see e.g. https://www.ukbmd.org.uk/reg/districts/chepstow.html (Chepstow) includes Alvington  and Aylburton (both Gloucestershire) and Caerwent and Caldicot (both Monmouthshire) to take just the first four subdistricts.

In the case of William Robert Smith, baptised in Chepstow in 1854 (https://www.freereg.org.uk/search_records/5f932ccef493fd032b89c120/william-robert-smith-baptism-monmouthshire-chepstow-1854-09-14?locale=en) 
On FreeBMD1 a search of Gloucestershire reveals him in the Chepstow district, and a search of Monmouthshire reveals him in the Chepstow district.  Chepstow town is in Monmouthshire.
On FreeBMD2 he is found searching Monmouthshire, but not searching Gloucestershire.

**Comment by richpomfret** [comment]
Decision to change 'England' to 'England and Wales'.

**Comment by richpomfret** [comment]
@PatReynolds to take a look.

**Comment by PatReynolds** [comment]
That's perfect, thanks, @Vino (tested on test3)
