### ISSUE TITLE
test3 and FreeBMB(1) behave differently when searching marriages using a spouse's surname in pre-1912 marriages

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#348]
Hi @PatReynolds

I was checking the Help documentation for this - I do not like the (lack of) "flow of the words" - which states:

![Screenshot 2021-06-02 163641](https://user-images.githubusercontent.com/67054943/120509898-d46d4480-c3c0-11eb-88ad-7247774f9aa7.png)

I searched for the marriages of two **females** who married the same spouse. For each search, specifying their Forenames and Surnames; specifying the spouse's surname (in this case it's a **male spouse**); and search dates of 1900 to 1915. FreeBMD(1) found both marriages using, I beleive, the search algorithm described in the documentation (third paragraph). 

Test3 gives nil matches. Note: both marriages were pre-1912, so the spouse's name is not given in the GRO Index.  The first wife died shortly after giving birth, which is probably why the widower concluded that new wife was needed.

If I leave out the spouse's surname test3 finds both marriages. So the search algorithm specified in the third paragraph for pre-1912 marriages with this search criteria is probably not being done on test3 at the current time - it's just a simple search for two spouses in a marriage. 

So what to do, and is this MVP?

If it is MVP the search algorithm needs changing; and the documentation improved,
If this in not MVP, I simply change the documentation to say (in effect) that if you spearch for marriages and specify a spouse's surname (and forename?) FreeBMD2 (test3 to be precise) will not find any pre-1912 marriages, so don't do it for pre-1912 marriage.

**Comment by Vino-S** [comment]
It was a bug. Fixed it. Ready for testing in [test3](https://test3.freebmd.org.uk/)

**Comment by PatReynolds** [comment]
@PhilipClarke712 could you test this, please?

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 
 
Yes, that **has fixed** the problem, test3 is now working as per BMD1 in respect of searching pre-1912 marriages against a given spouse name.
