### ISSUE TITLE
Add Google Tag Manager code to website

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#35]
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MMJNGL7');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MMJNGL7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by DeniseColbert** [comment]
@dhousman to check code above ready to be placed in the website

**Comment by dhousman** [comment]
Updated tag snippet

**Comment by DeniseColbert** [comment]
@dhousman code seems to have vanished, could you email it to me, please?

**Comment by richpomfret** [comment]
@dhousman this now seems to be done, can you test for us?

**Comment by richpomfret** [comment]
Completed - @Vino-S has added the tag given by @dhousman.
