### ISSUE TITLE
searching for marriages with a spouse name crashes test3 on three fields  in / or from the Entry Information page

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#350]
Off and one I've been running marriage searches on test3, with a spouse's name added.

Test3 finds the marriages  but crashes in three particular cases when hyperlinks are clicked:

(1) going to the Entry Information page and clicking on the **spouses surname** (view marriage) crashes the system - screen capture below.

(2) Also, when on the Entry Information page, clinking on the Page number gives a strap-line with the sucessful search result (Entries in Page #, Volume #, at District #, for date #) 

and underneath: both spouse's names in a grid; View1 is person matching the secondary search (the spouse) and View 2 is the person matching the main search (forename / surname) (as appropriate). 

Clicking on either of these View buttons (View1 and Veiw2) crashes the system.

![Screenshot 2021-06-05 192039](https://user-images.githubusercontent.com/67054943/120902025-ec99c980-c635-11eb-849a-602a052f554c.png)

**Comment by richpomfret** [comment]
Thanks @PhilipClarke712, @Vino-S shall take a look.

**Comment by Vino-S** [comment]
ready for testing in [test3](https://test3.freebmd.org.uk/)

**Comment by PhilipClarke712** [comment]
Hi @Vino-S ,

Sorry I forgot to put a "to read flag" on this message and it got "buried" in my inbox.

I'm pleased to say that everything mentioned above in this story is working on the **test3 site**. 

Its not part of this story, but non-official District names give 404 errors on an external site - UKBMD (see below).

**Detail:**

I searched for a 1928 marriage (spouse's spouse names are given in GRO index), with full name, spouse surname and year.
 Got my  correct "hit"; clicked **view**, then on **Entry Info** Page  - **page** hyperlink to get four "hits".  Going back to **View** and clicking on **Spouse** gives my relatives in two side-by-side which I am beginning to **like** , clicking on **page** lets me look at one of the "non-relatives" and clicking on their spouse's name, gives another set of two side-by-side boxes.

Out of curiosity, I did a pre-1912 marriage search, in 1888. I got one spouse, clicked on **View** and the **Page** number which gave me three "hits", (not "four" - this couple do have mis-matched page numbers 511 and 541). I then did a search for "my" person and added one of the other two surnames as a potential spouse's surname. It found "my" person, and it **correctly** had a blank **spouse forename** name field. Clicking on the **Page** number gives three people. So pre-1912 marriages are OK.

**Off-story error:**
There is one problem, **but that is outside this story**. The **District** for "my" marriage-search is given as "Birmingham N." and that produces a 404 error @ https://www.ukbmd.org.uk/reg/districts/birmingham%20n..html  the **official** District name is to be found at https://www.ukbmd.org.uk/reg/districts/birmingham%20north.html  There is another story ( #325 ) or stories for District names.
