### ISSUE TITLE
Record Type column-sort doesn't give Deaths

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#357]
Marriages is first, then Births, than Marriages again. When fixed, order should be Births, Marriages and then Deaths.

**Comment by richpomfret** [comment]
@PatReynolds to check deaths are now in there.

**Comment by PatReynolds** [comment]
Still only showing sorted Birth first and sorted Marriage first, then back to Birth first - Death first still missing

**Comment by richpomfret** [comment]
Vino has made a change in Test2 - to update and move into ready for testing when ready.

**Comment by richpomfret** [comment]
This issue may now be null if the 'sort' has been removed (for filter).

**Comment by richpomfret** [comment]
Checked and a non-issue. Closing.
