### ISSUE TITLE
Scans not being displayed

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#358]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/344c5938-9ebc-421d-b17c-5f8cd6c2a911)

Hi @Vino-S could you take a look at this, urgently, please?  We need it to work for user testing next week.

Many thanks, Pat

**Comment by richpomfret** [comment]
@DeniseColbert to test (scans should now be available) on beta site.

**Comment by DeniseColbert** [comment]
Scans now available. Thanks Vino!
