### ISSUE TITLE
Where can I translate the Districts code(s) into a District(s) / is this a temporary fix.

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#359]
In response to an _issue_ raised on the meanings of a paragraph in my draft of the Help page (for Beta), I did a randon search on test3 for a person within two Registration Districts, within the county of Warwickshire: which happened to be Aston and Birmingham, in that order.

![Screenshot 2021-06-20 184642](https://user-images.githubusercontent.com/67054943/122683590-205d1d80-d1f8-11eb-821d-84658c0efdbf.png)

My first comment as a Researcher is: are those the same numbers that appear in the 1939 Register for the Registration District / sub-district codes? I could start checking, but have not done so.  But more importantly how do I relate those numbers back to the Aston and Birmingham that I put in. 

All the results are in Birmingham (the majority) or Aston (the minority), so I'm fairly confident that my search terms were correctly entered; and as a Researcher District names are more useful to me.

Note: if I click on R**evise Search** it takes me back to the search page - keeping the County and most of the search terms (names,  etc), but clearing District(s), so I can't check my District(s) that way. I'm not objecting to this.

Is this a temporary fix, or a way of saving space on the page?

If the latter, is there a way on FreeBMD, or perhaps on another site, of quickly converting a district number to a District name.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 
It works very well when I search a single county, in this case Warwickshire, **and** I hold the Ctrl (Control key) down as per BMD1 when selecting the second and any subsquent District. If I don't use the Ctrl key it just uses the last district selection.

So, I selected the two counties of Staffordshire and Warwickshire. Then selected from the dropdown:   Aston (1837-1924), Rowley Regis, Birmingham (1837-1924), West Bromwich - two from each county using  Ctrl key- and that also worked and displayed the districts correctly and found "hits". If I don't use Ctrl, it only uses the last selected district, the same as for a single county.

Is this working to its design spec, that is must use Ctrl, as per BMD1, to select multiple districts - if so the help page needs to mention this?

**Comment by AlOneill** [comment]
@PhilipClarke712 Selecting more than one option from a drop-down list is accomplished the same way all over the internet, unless only one selection is allowed. Do we also need to explain how to select more than one option using a touch screen?

The explanation for how to choose more than one county or district, for devices with a keyboard, is on 'More about searching'. I suggest we put a link from the 4th item under 'Good to know — about searching'  to the information about counties and districts on 'More about searching'. Would that cover the issue?

**Comment by PhilipClarke712** [comment]
@AlOneill 

I eventually found that page: I first went to **Help** and there is no obvious link to 'More about searching', I used edit to search for that string on the page and it did not find it - only a link to 'more about names'.

The way I eventually found it was by going to  the **How to find the name of a spouse** section and at the bottom was a link called See help with Counties if you do not know which county a district is in and that is the link to https://test3.freebmd.org.uk/cms/help/more-about-searching#countyDistrict . 

Arguably, I did not know how to select Districts and the only way I could get there was by selecting how to the find the name of a spouse. I call that a totally illogical and a user-unfriendly help path - the user has to do lateral thinking - but it did give me the answer to my question above.
 
So, yes your suggestion about a link from the 4th item under 'Good to know — about searching' to the information about counties and districts on 'More about searching', is a good one. However, sometime more links will be needed.

#382 is about adding more information, and I'm suggesting a page which you have not seen (splitting hairs reviewed), but there is no obvious ways of 'hanging' links from **help** to other subpages, like help with marriages, help with Late Entries, (how to get certificates for the Isle on Man, etc).

Sorry, I missed out the first question. I don't use smart phones for searching, so I tried out FreeBMD1 on my phone, 4 1/2" using the chrome browser. The instructions tell to hold Ctrl while I use my mouse. I don't have either but I did manage to select two districts from a global list for England and Wales, by putting a tick in a box - that far took nearly five minutes. I got nil hits and I could not go backwards to add more districts.  Its unusable, in my view. At least I was wireless-connected to my router and not paying phone charges by the digit and the second. That has totally put me off doing a smart phone search.

**Comment by AlOneill** [comment]
I think I focussed on the wrong details yesterday.

If it becomes apparent from testing that our users do not know (or have forgotten) how to select multiple options in a drop-down, then do we explain it? and if yes, where would be the best place? (The current place is probably not the best if lots of users need a reminder.)

As for links to other Help pages, the most obvious thing would be to create a sub-menu of 'Related pages' or 'You might also like' or 'See also' or similar. A short sub-menu would work if placed after the 'On this page' sub-menu. If and when it becomes long enough to interfere with the responsive behaviour of the page, then we'll have to think again.

I'll add these thoughts to #382.

**Comment by PhilipClarke712** [comment]
Hi @AlOneill 

Thanks for your comments. I'm going to add some lateral thinking. 

On some systems if you do something 'wrong' you get a dissonant sound - in the old Popeye films, steam coming out of the person's ears and a shrill whistle, the opposite might be white doves and some Mantovani music. There are three ways of selecting and they all appear to be valid, but there are different amounts of _instant feedback_ that are sometimes overlooked  (I overlooked them all at the time of selecting). So, you might use the wrong 'valid means of selection', and not realise it at the time.

The system would 'allow' me to select multi-choices using (on a computer):  just key clicks; a key click with Cntrl; and key click with shift key. The last one (click and shift) selects all adjacent entries between two entries and it's a strong feedback because a block of entries turn red. The click and Cntrl selects multiple, non-adjacent, entries and if you take the time to scroll up and down you should see more than one red entry. The click and click (and click etc) only selects the last entry-clicked and so only one entry goes red (if you scroll up and down).

We should make it easy for someone to find that relevant help section, via the shortest possible path (least number of jumps), However, perhaps just a short note under 'Select one/more Districts or none' possibly saying _scroll up and down to check your selection (a red entry / entry)_ might be need for those who have just forgotten for the moment what to do.

The other point, is that at this stage (have selected a  county/counties or district(s) and you realise that you would like to change your mind there is no 'back' button on the search page. Its only when you get to the Results page, do you have two buttons Revise search or New Search. I think I would like a Revise search button on the search page.

**Comment by AlOneill** [comment]
What would a 'Revise search' button do on the Search page? I think you mean a 'New search' button: the Scrum decided to remove the 'Clear form' button because it would be all too easy to select that by mistake, instead of 'Search'. The safer way to clear the form is to select the logo in the header — that is how REG and CEN do it.

If testing tells us that users need help to select multiple options, then placing something on the form could be the best solution. But, think about source order: if you cannot scan the page (with your eyes) then you need the info on multiple selections _before_ you want to use it. A brief tooltip (on the Counties label) would provide that: Use ctrl (cmd on Mac) to select or deselect more than one county.

**Comment by PhilipClarke712** [comment]
@AlOneill 

Thanks, I learnt a few things, above. 

Yes, I can do every thing now without a back button: clicking on the logo clears every selection, I did not know that; and, having selected multiple places, with either shift or Ctrl, repeating the process clears the existing County(ies) / District(s) selection. I was undoing things using my browser's back button, which is a very blunt way of undoing place(s) selections.

The tool tip is presumable the coloured-'dot' with the 'i' inside, or is it that the words 'select one or more {widgets}' under the dropdown? It's a term I've not come across. Either way would be a helpful way forward. 

My preference would be to expand that text to refer to the use of shift for adjacent selections, or ctrl for multiple non-adjacent selections; ctrl could also do an adjacent block of selections, but would need more key-strokes than a shift key.

**Comment by AlOneill** [comment]
Yes, a tooltip is the text that appears when the 'i' icon is focussed or hovered.

_If_ we decide that we need to provide the how to use your device information, then it needs to be kept brief for the sake of screen-reader users who will hear it every time they pass through the form — we do not want to drive them mad!
