### ISSUE TITLE
Disseminate Survey (was Update survey)

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#36]
Following feedback.

**Comment by DeniseColbert** [comment]
Sent 14/11 for final check before sending

**Comment by richpomfret** [comment]
To also investigate whether we might add the survey link to the FreeBMD1 search page (ask Barrie where we might place it).

**Comment by DeniseColbert** [comment]
Sent out 4/01
Scheduled for SM

**Comment by richpomfret** [comment]
We have a story on TRAC now to add this onto the search page - Pat & I to discuss with Barrie in terms of when we might get it added.

**Comment by richpomfret** [comment]
Not practical (in terms of speed of adding or removing) to site currently. Once Scott/Vino are set-up, we can revisit. As core story is complete, moving this to done and complete.
