### ISSUE TITLE
Rename 'Coverage page' as records page throughout

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#360]
Coverage page in FreeBMD2 is now called 'Records'.

See Systemwide#193 - changes needed to documentation.

I can't find any reference to "coverage" outside of the "Coverage" page.  

FreeCEN has Database Coverage
FreeREG has County and Place Records

**Comment by PatReynolds** [comment]
Check when all/most Refinery pages are made.

**Comment by KristinaGadzhieva** [comment]
@Vino-S @richardofsussex  Is it relevant now? Do we need to make changes?

**Comment by richardofsussex** [comment]
The only mention of 'coverage' I can find is on the About page, where it is a link to the coverage page of the FreeBMD1 site. This is correct, since that is what the page is called when you arrive there. I suggest we close this story.

**Comment by KristinaGadzhieva** [comment]
Thank you, closing the story.
