### ISSUE TITLE
Permit searching by whole of Wales & whole of England

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#361]

**Comment by richardofsussex** [comment]
This should be simple: provide an entry in the county drop-down list which, when clicked, selects all Welsh counties. (To be fair, there should also be a "Select all English counties" as well ...) The existing "All counties" item at the top of the list will undo either selection if/when it is no longer wanted.

**Comment by richardofsussex** [comment]
OK, I think I've implemented that. You now get:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--429a30effaf9ed3ec96287f7aaa3d86fef2242e6/image.png)

and if you select "All Wales" the Districts box fills with all the Districts in Wales. You'll notice that English and Welsh counties are now listed separately: this is more in line with what the other projects offer.

**Comment by richardofsussex** [comment]
@vino could you please put my branch fb_361_rbl into test3 so that Denise can check this?

**Comment by KristinaGadzhieva** [comment]
ready for testing on test3

**Comment by richardofsussex** [comment]
Looks OK to me.

**Comment by DeniseColbert** [comment]
We will revisit this when autosuggest is fixed (next scrum?)

**Comment by Vino-S** [comment]
Deployed

**Comment by KristinaGadzhieva** [comment]
@Vino-S please change the name for All England without brackets after

**Comment by DeniseColbert** [comment]
Also, change Counties title to Counties/Country and label to Start typing county or country names
