### ISSUE TITLE
Save a result

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#362]
New feature: Logged in Researchers can save an entry from the entry information page.

@PatReynolds I just realized the feature we needed was to Save Search Results. My mistake. 
Please do let me know your thoughts.

**Comment by Vino-S** [comment]
Can be reviewed in test3

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 

I got mixed results.

I normally use Firefox as my browser. So in Firefox, I went to test3 and ran a search using an ancestor's name which produced two "hits" (father and son). From the Entry Information Page, I clicked the "heart" icon and an https:// address appeared, so I opened a new tab and copied the https:// address over and got that same Entry Information page in the other tab. That worked fine for both "hits".

I went back to the first "hit", opened Microsoft Edge and copied the https:// address over: test3 asked me to log in and then test3 crashed  - "We're sorry but something when wrong (500)". I opened a new tab in Edge and copied in the second https:// address over (no log on request) and test3 crashed again, same error.

I've never used Edge on that computer to run test3, perhaps it's a cookie problem. But it looks like a can't copy the address between FireFox and Edge.

Anything else you want me to try?

**Comment by Vino-S** [comment]
Thanks for testing @PhilipClarke712 
You should be able to see the saved results in Saved Entries Action. Below is the screenshot
![image](https://user-images.githubusercontent.com/26073943/122829775-56c19800-d2df-11eb-866e-f82f4c358b12.png)

Once you click on the action, it should list all the entries  that are saved by you: Below is the screenshot:
![image](https://user-images.githubusercontent.com/26073943/122829962-94262580-d2df-11eb-95ba-582c3db97f01.png)

**Comment by PhilipClarke712** [comment]
Hi @Vino-S 
Thanks. I never saw that screen last night.
I tried again just now, but the "pink heart" is absent from the **More Infomation** box, so I guess that function has been temporarily removed from test3?

**Comment by richpomfret** [comment]
@PatReynolds let's clarify this before Vino develops it.

**Comment by PatReynolds** [comment]
If this story is about "saving the results of a query" ( cant see such a story) then,
a) generate a printable copy - functions but some changes needed
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/31edbf5a-fb01-4ec7-b683-902ecc41e496)
 - [ ] add margin to left so that people can put holes in before adding to a folder
 - [ ] reformat the data so that the volume and page follow the district - e.g. in the example above
Joseph Randle 
MARCH 1854
Foleshill 6d 376

 For consideration (possibly for future version)
 - [ ] Format as Foleshill Vol 6d  Page 376
 - [ ] Capitalise all surnames, eg. Joseph RANDLE 

b) Download as CSV is not working

The 'saved search' feature is 1.5, and I don't see the hearts any more, so assume the feature has been put in abeyance.

**Comment by PatReynolds** [comment]
Implemented as Download as CSV.

Are we going to re-implement the saved search?

**Comment by richardofsussex** [comment]
"Download as CSV", as I understand it, downloads _all_ the records in the current search. The "Save a result" function as described above saves _only_ the current record. Therefore it is a different function, and has a different purpose. (It is also different from "Save a search", which saves the search logic.)

"Save a result" can mean that one or more of a number of things can happen. 

The "saving" aspect can mean something temporary, like setting a cookie, or something more permanent, like creating a MongoDb record linking the user with that record. (This new record could include metadata, e.g. a timestamp or the search logic, and/or user data such as comments or assertions about the relationship between this person and others. It will rely on our developing a strategy for persistent IDs for BMD records.)

The "result" aspect - what can the user do with it - can be implemented as a simple "print this record" as noted above, or as one or more machine-processible formats. CSV has been mentioned (although not yet implemented for the Saved Entries view?); we could also think about offering GEDCOM export, which would allow the user to import the data into other platforms.

**Comment by KristinaGadzhieva** [comment]
Implemented, can be closed.
