### ISSUE TITLE
District page link in the search result table doesn't work

### ISSUE THREAD

**Issue by lychee616** [FreeUKGen/FreeBMD2#363]
When looking for the birth registration of Josephine Smith, mother’s surname was Jones (she was born just before the First World War), on the result page, when clicking the registration 
district name, it said the page was not found.

![issue1-1.png](https://images.zenhubusercontent.com/60cc693d082c1d4520780b98/b6c43322-d4b3-46da-8b58-fe4d4e448b9a)

![issue1-2.png](https://images.zenhubusercontent.com/60cc693d082c1d4520780b98/93840501-01ab-4762-b8bc-07fbb47d7984)

**Comment by PhilipClarke712** [comment]
also covered by #325

**Comment by richpomfret** [comment]
Now fixed so closing.
