### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#364]
Search page: Month field is confusing to non-genealogists. Would Jan-Mar; Apr-Jun; Jul-Sep;

Tools menu has gone from Entry Information.

Transcriber info is often (always?) missing

**Comment by PhilipClarke712** [comment]
Hi @DeniseColbert,

As a comment, FreeBMD(1) and test3 implement the **"month"** field the same way on both search pages: via  a dropdown with only four choices. Note: years are selected separately - typed in on BMD1 and a dropdown on test3. 

Neither of these sites **name** this field - it is **not called the Month field**. So, people moving across from FreeBMD(1) should not have any problems.  The pay-to-view site, Ancestry calls its field the **Registration Quarter** , and it defines them as Jan-Feb-Mar, etc, in the same way that our Help pages do / will do. The Help page on BMD2 and the test3 version (not the current Help page, but the one under review by Alison) specifically define what the quarters are, e.g. March quarter contains the registrations in January, February and March".

On both of our systems, this field has the advantage of being **short** - just three letters  Mar, Jun, Sep, etc. Your suggestion of Jan-Mar, Apr-Jun, etc, would increase that to seven characters, but that might not be a problem - a slightly wider dropdown box would suffice. An alternative style of naming would be to specifically refer to a Quarter, such as March quarter, June quarter but use an abbreviated form : e.g. **Apr Qtr**, **Jun Qtr**, etc. This is also seven characters long.

**Comment by Vino-S** [comment]
_Tools menu has gone from Entry Information_

Tools menu had only two options for MVP: Postems and View Scans
These two options have been moved to Entry Information table. So removed the Tools menu
![image.png](https://images.zenhubusercontent.com/5ca2316a45147541ad68a420/8fb19fd2-f715-4751-8bbc-2609db53d22c)

_Transcriber info is often (always?) missing_
Transcriber info needs a complete database.

**Comment by richpomfret** [comment]
@Vino-S to implement/comment and deploy the code to beta (full db).

**Comment by richpomfret** [comment]
Suggestion of tool-tip to help with months/quarters (new story created for this).

**Comment by richpomfret** [comment]
Complete (or other stories to cover these). Closing.
