### ISSUE TITLE
Results page — changing Show (number of results) results in a crash, sooner or later

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#368]
When I try to change the Show (number of results) from default of 20 to 100 (with more than 100 results), I get the red "Something went wrong …" page.

Trying to change to show 40 works initially, but crashes when asked for next page.

**Comment by Vino-S** [comment]
Hi @AlOneill ,
I was working on #325 which caused this bug. Now fixed.

**Comment by AlOneill** [comment]
@Vino-S Sound. Working OK now. Thanks.

Closing.
