### ISSUE TITLE
User experience - change default search end-quarter from March to December

### ISSUE THREAD

**Issue by PhilipClarke712** [FreeUKGen/FreeBMD2#371]
This is a user-experience request that has caught me out a few times on test3.

If I don't set search dates the default is Mar 1837 to Mar 1992.
I suggest that the End-quarter box should work be configured the same way as the End_year box, that is, it  **defaults** to the December quarter, not March-quarter.

If I choose to set a Start-Year (very well thought out) I _move_ the start year forward from 1837; and if I choose to set an End-year I _move_ the end year backwards from 1992.

Now If I choose to search just a 12-month period, say 1945, I just set the start and end years and then hit Search. Actually on test3 it searches only the March-quarter of 1945, because the do-nothing option on **both quarters** is March (but on FreeBMD1 the do-nothing option is March and December, respectively).

**Comment by richardofsussex** [comment]
Also, when the 'from' year is entered, the 'to' year should change to show the same value. That (together with the suggested change to the default quarters) would allow a single-year search to be carried out, simply by specifying the 'from' year.

**Comment by DeniseColbert** [comment]
Ready for testing on Test 3

**Comment by richardofsussex** [comment]
Yes, that works as intended. The only peculiarity is that the quarters in the 'To' date are reversed: Dec then Sep then Jun then Mar.

**Comment by KristinaGadzhieva** [comment]
I think it is better to do it in the same order (from Mar to Dec) but set December in 'to' field by default. Is it possible @Vino-S ?

**Comment by PhilipClarke712** [comment]
The suggestion was mine: at the time that I made it (July 2021), the Start-year was a drop-down that defaulted to 1837 and the Finish-year was a dropdown that defaulted to 1992. So, it made sense to me to treat the Start and finish months in the same way, i.e. defaulted to Qtr. 1 and Qtr. 4, respectively . Looking at test3 now, the default years are both 1837, so - as stated above - it would be consistent to treat the start and final months in the same way.

**Comment by richardofsussex** [comment]
Sorry: the end-date quarters are still in reverse order on test3.

**Comment by KristinaGadzhieva** [comment]
It is done on test 3. @Vino-S could you please move it to Beta
