### ISSUE TITLE
Contrast ratio of main navigation is too low

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#372]
The contrast ratio, between the magenta and the light grey in the main menu, is too low at 4.21:1

With magenta isles and buttons, the contrast is against white which is fine.

With islands and islets that have the light grey background — `#f4f4f4` — the magenta link colour is adjusted to use the more saturated version of magenta, `#BE3778` — this is a named colour in the SCSS (I forget the name).

The menu bar should either use this version of magenta, or revert to white where there is now light grey.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by AlOneill** [comment]
Light grey has been replaced with white so now passes AA.

Thank you, @Vino-S
