### ISSUE TITLE
Saving the results of a search query

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#376]
Saving the results of a search query can be done in two ways
a) generate a printable copy - functions but some changes needed
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/31edbf5a-fb01-4ec7-b683-902ecc41e496)
 - [ ] add margin to left so that people can put holes in before adding to a folder
 - [ ] reformat the data so that the volume and page follow the district - e.g. in the example above
Joseph Randle 
MARCH 1854
Foleshill 6d 376

 For consideration (possibly for future version)
 - [ ] Format as Foleshill Vol 6d  Page 376
 - [ ] Capitalise all surnames, eg. Joseph RANDLE 

b) Download as CSV is not working

**Comment by PatReynolds** [comment]
Tested on Beta.

For discussion: do we want something that will be useful when printed out - or useful to see on a small screen, or both?

Download as CSV now working.

**Comment by DeniseColbert** [comment]
@Vino-S to take a look

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richpomfret** [comment]
@DeniseColbert has tested and works fine.
