### ISSUE TITLE
Infobutton change: Date Range

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#379]
- [ ] Date range from / to - decide text (current text does not refer to current system)
 - [ ] Date range from / to - implement new text

**Comment by PatReynolds** [comment]
Text on first button is currently: Leave Year blank to search the whole year
Suggest: Choose quarter and year for the start of search

Text on second button is currently: Choose quarter and year for the start of search

@DeniseColbert @AlOneill what do you think?

**Comment by AlOneill** [comment]
@PatReynolds On test3, there are no longer any info buttons for the Date range — not needed.

@Vino-S There is an empty tooltip (with associated `tabindex="0"`) for the District field — it should be removed.

**Comment by richpomfret** [comment]
Duplicate story - closing.
