### ISSUE TITLE
Selection of data type for Age at Death in Search page is not working

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#381]
@Vino-S could you take a look at this - perhaps affected by issue yesterday?

**Comment by Vino-S** [comment]
Hi @PatReynolds ,
It seems to be working now. Could you give me the search conditions, please so that I can replicate the issue?

**Comment by PatReynolds** [comment]
The drop-down list still does not appear when Death is selected, The 'Select Death Age' is visible, but no selection is possible.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/67dbe3b2-d721-4315-8553-75f08691567c)

Tested on Chrome.

The dropdown/choices work as expected on an android phone.

**Comment by PatReynolds** [comment]
Pat to check status of pop-ups ?blocked on her computers and phone

**Comment by PatReynolds** [comment]
Works fine now on Chrome.  Cannot test on phone because google refuses to redicret to url, and instead just searches ....
