### ISSUE TITLE
Add guidance for "Additional search options" to researcher Help

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#383]
The Additional search options are beautifully intuitive once you get going, but we do need to describe their use. The challenge will be to **not** make them sound more complicated than they actually are!

Perhaps do this in two stages:

1. Something brief to be ready in time for testing and MVP

2. More details and examples when ready

**Comment by PhilipClarke712** [comment]
There is a draft  Advanced search facility help  page at https://test3.freebmd.org.uk/cms/help-superseded-or-draft/draft-advanced-search-facilities  but it focuses on what BMD1 can offer and almost all of those functions are either not yet available on BMD2, or done in another way, such as using drop-down boxes, not wildcard characters, such as (plus) (+). 

Note: it does have a Names section which would need to rewritten from scratch and and a Postems section which might be needed if the beta version goes onto a production server with a full version of the database and a postem search capability is implemented.

**Comment by AlOneill** [comment]
@PhilipClarke712 This will need to be completely new, using Vino's description and our experience of the new fields.

**Comment by AlOneill** [comment]
The most obvious problem in describing the partial search options is keeping the terminology consistent for parts of a name. This terminology will need to be explained near the top of the section.

For the purposes of this Help section, I propose that we use use **forename** for everything that is not part of the surname. We then consider the forename as comprising a **given name** plus a **middle name** (or names).

If anyone can see any snags with this particular scheme **_and_** can suggest a better one, please say so.

**Comment by richpomfret** [comment]
No snags spotted. To continue with write-up based on the suggested approach.

**Comment by richpomfret** [comment]
Is this one for @PhilipClarke712 to continue with?

**Comment by AlOneill** [comment]
It is not ready to be handed on, yet. It's on my laptop, written in MarkDown. Some bits remain to be translated from developer-speak into something more suitable for users.

**Comment by AlOneill** [comment]
Have made quite a lot of progress on this story. Was hoping to put the HTML version into Refinery this weekend, but got de-railed by other issues and life.

**Comment by richpomfret** [comment]
@AlOneill any updates on this one?

**Comment by AlOneill** [comment]
A first draft of [Additional search options](https://test3.freebmd.org.uk/cms/help/draft-additional-search-options) is now in Refinery on t3. The final set of options is not edited from the developer's text: making this suitable for a user is the next part of my task.

**Comment by AlOneill** [comment]
Complete draft of [Additional search options](https://test3.freebmd.org.uk/cms/help/draft-additional-search-options) is now in Refinery on t3. Still tweaking some of the more awkward text. A few queries to resolve.

**Comment by AlOneill** [comment]
DRAFT version of [Additional search options](https://test3.freebmd.org.uk/cms/help/draft-additional-search-options) updated with queries resolved.

Page needs review and checking. Does anyone have better examples for the three sections listed at the top of the page?

**Comment by PatReynolds** [comment]
Example of finding Contains (Surname)
a search for Alex STONE finds Alex STONE, Alexandra STONEY, and Alexis STONESTREET

Example of finding Ends With
a search for Mary COLE finds Mary COLE, Mary SEACOLE, and Mary WELLS-COLE
Field finds FIELD, OLDFIELD and WAKEFIELD

In Middle Name or Surname
[FreeBMD keeps crashing out - will try and answer this one tomorrow]

**Comment by AlOneill** [comment]
@PatReynolds thank you.

Do you want us to put all surnames in upper-case? Or was that force of habit?
Bear in mind that the letter casing of surnames (and first names!) is all over the place in the Index itself and so also in Search Results and Entry Information.

**Comment by PatReynolds** [comment]
@PatReynolds to specify how the given name(s) and family names(s) should be layed out on this page.

**Comment by PatReynolds** [comment]
Maybe say "familly names in the examples below where it is important to distinguish given and family names are in *bold* [or some other distinguishing feature].

Maybe add a video so there is an oral description of these features (maybe it only is relevant for search-by-middle-or-familyname?)

**Comment by AlOneill** [comment]
@PatReynolds That does not sound accessible to a screen reader user.

**Comment by PatReynolds** [comment]
Pat to try a text re-write for clarification of the parts of the name in examples.

**Comment by PatReynolds** [comment]
Would a table be better, or throughout use

First name Jane family name Jones
First name Jane family name Jones-Prentice
First names Jane Alice family name Jones 
First names Jane P family name Jones

**Comment by PatReynolds** [comment]
@PatReynolds to make sure this is the only case where it is needed, so examples are

First names Jane Prentice surname Jones
First names Jane surname Prentice Jones

**Comment by PatReynolds** [comment]
I think middle name/surname searches are the only ones where it would be necessary to identify the name parts with words.

**Comment by richpomfret** [comment]
Added to documentation meeting to be reviewed/discussed.

**Comment by PatReynolds** [comment]
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/c518411c-217e-4ff1-9b84-73b40979359a)
Search for Bowes Lyon in surname, 1925, on middle or last name 'other' option.
Finds: any first names + surname =
Bowes
Lyon
but not any  Bowes Lyon

Is this expected @Vino-S ?  I would expect to find only people with the surname Bowes Lyon or Bowes-Lyon, and people with a middle name of Bowes and a surname Lyon.

**Comment by richpomfret** [comment]
@Vino-S can you take a look when you can?

**Comment by Vino-S** [comment]
_Is this expected @Vino-S ? I would expect to find only people with the surname Bowes Lyon or Bowes-Lyon, and people with a middle name of Bowes and a surname Lyon._

It would find people with surnames Bowes or Lyon and People with Middle Name Bowes or Lyon. However, it will not find Surname Bowes-Lyon

**Comment by PatReynolds** [comment]
Based on the Genealogy search by Google feature - @PatReynolds to look at that, and write a help based on it.

**Comment by PatReynolds** [comment]
Can you give me a link to the Google genealogy feature please, @Vino-S

**Comment by PatReynolds** [comment]
The Google Advanced search engine

**Comment by PatReynoldsFUG** [comment]
@Vino-S Google Advance search does not have fields for first and last names. 

The search you have implemented does not meet the specification. Personally, I can't see that it would be of use to researchers (but happy to be corrected on that).

What IS needed is a search that takes John Lyons Davis and looks for both John Lyons DAVIS and John LYONS DAVIS (first names are lower case, family names are upper case to show the difference, not for how they should be displayed).  Taking myself off this now for others to decide the next steps.

**Comment by DeniseColbert** [comment]
We need info from Vino about the additional search options design- how have you set this up @Vino-S ? Particularly the search by middle name. Additional search options should prevent the need for multiple searches for finding a middle name.

**Comment by DeniseColbert** [comment]
@richardofsussex to take a look

**Comment by richardofsussex** [comment]
I find the additional search options design unhelpful: search options for a field are completely separated from the field itself.  Also, those options can apply to any one of three fields - but only to one of them in any given search.  And if you've used the additional search facility, you have to remember to switch it off again if you modify your search.

In place of the whole additional search options box, I would prefer separate 'options' controls for each search field. For First Name(s), we could have a drop-down, with values "Starts with" (default), "Exact match", "Name in any position", "Contains" and "Ends with". For Last Name it would be "Starts with" (default), "Exact match", "Contains", "Ends with" and "Phonetic search". For Mother's Surname it would be  "Starts with" (default), "Exact match", "Contains" and "Ends with".

I don't find the "middle name" concept useful, and the proposal above gets rid of it, while (I _think_ - please check!) retaining all the functionality we currently have. In fact, my proposal gives the user more information, since the fact that searches are "begins with" by default is now explicitly stated.

It is a fact of life that the First Name(s) field contains a mixture of given names, "middle" names and the first half of unhyphenated double surnames. It is also a fact of life that our transcribers will have arbitrarily decided to put either GivenName: "Ralph Vaughan", LastName: "Williams" or GivenName: "Ralph", LastName: "Vaughan Williams". A search for "Vaughan WIlliams" suggests that the first of these strategies is by far the more popular.

The comments above suggest that you would like it to be possible for a single search to find all the Vaughan Williams', using the additional search options in some clever way. My view is that this isn't possible, and we should instead level with our researchers about the nature of the data.

One other comment: the "Middle Name + Exact Match" combination always give a timeout "Search took too long" error _instantly_.

**Comment by DeniseColbert** [comment]
Would the drop-down menus fit in the space below the fields?

**Comment by DeniseColbert** [comment]
Decided that autocomplete in names could solve this issue. As it currently is designed to search via Starts with... it will need further consideration to find names that are not at the beginning of the field.

**Comment by KristinaGadzhieva** [comment]
Not relevant for MVP. Additional options have been removed from the search page.
