### ISSUE TITLE
Review PID/Update

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#39]
Update (if necessary) and send around for review to Barrie etc.

blocks #44
blocks #11
blocks #7

**Comment by richpomfret** [comment]
Barrie has added in helpful comments for better distinguishing between backend/front-end features (or epics). Shall feed these into the roadmap & sprint-plan

**Comment by richpomfret** [comment]
For @PatReynolds to review in terms of any more recent changes to policy prior to sign-off

**Comment by PatReynolds** [comment]
Cannot find it - last version is Barries 12 November.  Please put in the FreeBMD2 folder.

**Comment by richpomfret** [comment]
In the process of updating 0.4 to include suggestions (via comments) and a reorder of items based on backend/frontend/new features or functionality.

**Comment by richpomfret** [comment]
Kirk has added his thoughts/comments. I think we are pretty much there now with the PID - from here we can involve the code team to determine the tech spec and order of delivery/sprint schedule.

**Comment by richpomfret** [comment]
Complete. Adding more specific stories for any outstanding updates required.
