### ISSUE TITLE
Late entry / entries links not working

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#400]
The link highlighted doesn't work for either of the linked entries for this individual

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/f27d7474-9ddd-448a-8d1f-c9ee52b27eef)

**Comment by richpomfret** [comment]
@DeniseColbert to test on beta.

**Comment by richpomfret** [comment]
Not working on beta.

**Comment by DeniseColbert** [comment]
https://beta.freebmd.org.uk/6151fa0a9c5d6164f04f1d40/entry-information/220087264/janet-henry-birth-hampshire-southampton-v6b-psee-j-60?locale=en

(Janet Henry; birth; Southampton; 1958-1960)

**Comment by richpomfret** [comment]
@DeniseColbert to test on beta.

**Comment by DeniseColbert** [comment]
Working as expected. Thanks Vino :)
