### ISSUE TITLE
Change "View Reference Record" (late entries) to View Linked Record

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#401]
Change the language in the link

![image](https://user-images.githubusercontent.com/19173257/134775128-13fb5b6d-609d-409d-88a0-8688e897620c.png)

**Comment by AlOneill** [comment]
Not sure that 'Refers' is the best heading for this row either. Will think on …

**Comment by DeniseColbert** [comment]
Row title: Linked records
Link text: View linked record

**Comment by richardofsussex** [comment]
I've changed the row title and link text as requested: see branch `fb_401_rbl`

**Comment by richardofsussex** [comment]
@Vino-S please merge in this branch

**Comment by richardofsussex** [comment]
This looks fine on test3. Sign it off?

**Comment by Vino-S** [comment]
Deployed
