### ISSUE TITLE
Beta loading/slowness issues

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#402]
- Clicking "View" button in search result table is slow to load
- Clicking "View" Scan button is also slow to load

**Comment by Vino-S** [comment]
Hi @DeniseColbert ,
I am fixing the reference entry, I noticed the slowness issue in the Entries with reference records.
Could you confirm it, please? Please also let me know if it's still slow with records that do not have a reference entry.

**Comment by DeniseColbert** [comment]
Still slow with records that have no reference (linked) entry, and also still slow with records that do have a linked entry. 

Maybe a _little bit_ faster, but still not great.

**Comment by richpomfret** [comment]
@Vino-S has this now been fixed?
