### ISSUE TITLE
Search Results page still using REG-appropriate wording for "no results found"

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#404]
The first para is fine. The following two need editing:

"Alternatively you were searching for entries that simply do not exist in our database because: We have yet to transcribe the registers; there are gaps in the registers or they no longer exist; the transcriptions are subject to an embargo on their publication; we do not have the financial resources to purchase the registers; or Record Offices will not permit us to acquire copies of the registers.

"Our Transcription pages can tell you what we have transcribed and the periods of their availability. They also contain lists of the actual names that appear in a register so that you may consider alternative spellings."

**Comment by richpomfret** [comment]
@DeniseColbert to write appropriate copy/text for @Vino-S to then update.

**Comment by DeniseColbert** [comment]
@AlOneill I've updated the doc we've looked at previously (and written improved CEN & REG text for), for FreeBMD2. It needs some work; I've added it to the list of docs for us to look at in our Documentation meet this Friday.

https://docs.google.com/document/d/1n58RWUVyqGe1pBf6YC7KAFkAdKE90m4hFJ60vBkWmZs/edit?usp=sharing

**Comment by Vino-S** [comment]
<img width="1499" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19203185dd39abb8cc7b9d461cbc3e12a430fc42/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
@Vino-S I see this on test3 <img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e61c2bb4826c71868cf487f7840ec003abf1df5/image.png" alt="image.png" />

**Comment by richardofsussex** [comment]
@KristinaGadzhieva I can't see any of your images. Can you make them inline rather than links?

**Comment by richardofsussex** [comment]
Isn't it General Register Office, not Government Record Offices?

**Comment by KristinaGadzhieva** [comment]
+ GRO is General Register Office.
+ Perhaps it might be better to mention a link to the help page at the beginning of the sentence as it is in the doc Denise mentioned above <img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0syQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--959d7ecffc7c5536b2b05ff504291ed0d35f59f3/Screenshot_2.jpg" alt="Screenshot_2.jpg" />

**Comment by KristinaGadzhieva** [comment]
<img width="1136" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4a34cd69ea1281b397dc06e34bb0096a3cb2411/Screenshot_3.jpg" alt="Screenshot_3.jpg" />
Can be deployed

**Comment by DeniseColbert** [comment]
Not yet on Beta as other code is running
