### ISSUE TITLE
Split Data Problem options into groups

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#406]
The list is long:

![image](https://user-images.githubusercontent.com/19173257/135122299-4d75829f-7637-43c6-8f45-b3d1617e0330.png)

Can these be separated with the headings from the spreadsheet? i.e:

![image](https://user-images.githubusercontent.com/19173257/135122569-f41f71a2-10df-4644-86ff-6ad807ea6b74.png)

(From https://docs.google.com/spreadsheets/d/1VQt3Fjl1y2eixHsPQVp2gSZ0VEVPZ4xYsisbkLiZ01c/edit#gid=942996947)

**Comment by DeniseColbert** [comment]
To be reviewed with report a data problem and comment with what needs to be done in this area for both stories

**Comment by richardofsussex** [comment]
Using broad headings from the spreadsheet will only make the list shorter if they are all that is displayed. This makes choosing the correct option into a two-stage process. There is a risk that the user will not recognize _any_ of the headings as describing their issue with the data, and so they won't find the explanation.

I suggest we leave this list as it is.

**Comment by richardofsussex** [comment]
Suggest three-way choice: missing data, query on data, query on scan -> different sets of specific questions.

**Comment by DeniseColbert** [comment]
@richardofsussex to take a look

**Comment by richardofsussex** [comment]
I've established that the "answers" appear in response to an Ajax call which fetches the document /public/faq.html.erb, and displays the relevant part of it. There is code which is intended to do the same job using an array of answers, but this approach has not actually been implemented. It's easy enough to change the long list of questions to the three suggested above, and hand-editing the structure of faq.html.erb to match these three questions would be one way of getting the desired set of answers to appear.

We need someone to decide which category (missing data, query on data, query on scan) each of our current questions falls into, and we need an introduction to each set of answers. Once we have all of that, I think I can see a way of implementing it in the web site.

**Comment by nurifreembd** [comment]
Solution is to consider the different ways users interact with select element via the keyboard, mouse or assistive technologies (screen reader) and digital devices and browsers.

**Comment by richardofsussex** [comment]
One thought is that we would only accept corrections or additional data if the corresponding scan shows that the data is missing or wrong. We can presumably tell whether the user has viewed the scan. If they have not, I would suggest outputting a fixed help text which offers no options at all (but which mentions that we are only interested in fixing errors in, and omissions from, the source page).

If they _have_ viewed the scan, we can go on to the 'data missing' or 'data wrong/questionable' options we discussed today.

**Comment by richardofsussex** [comment]
Thinking about this some more ...

This conversation/help needs to start one page earlier, at the search results page. If you get no hits, helpful text guides you to the searching Help page and the Records section (to allow a check on our transcription progress, N.B.). In the much more common case that you do get some hits, but the person you are after isn't among them, you get no help. There should be a "didn't find the entry you were looking for?" footer containing similar information to that on the "no hits" page.

This information should acknowledge that one possibility is that the entry is in the GRO Index, but hasn't been transcribed. (This is not currently mentioned as a possibility.) It should explain about using wildcards to broaden a search and to check both for gaps and for UCF usage. It should explain how to select an entry "adjacent" to the missing one and look at the source scan to see whether the entry is in the scan but has been missed. In this case, it should take the user to the same error reporting form as the one accessed from the Entry information page.

There should be no mention of missing entries in the questions/answers accessed from the Entry Information page.

**Comment by richardofsussex** [comment]
This is the 'no hits' page, with suggested additional entries:
![image](https://github.com/user-attachments/assets/310e19e6-def7-4a27-b9d8-62f4fe0c346f)
I wonder whether the last bullet point should be omitted.

**Comment by nurifreembd** [comment]
Good evening Richard,

Your response is very well thought out and your solution is valid after
performing the search. Thank you.  For example, if I search for Nuri Zorlu
1900 -1945, it makes sense to show a no hits (Record/Register not found)
page with the suggested entries.

I think the last point is valid and it may be the case that we do not have
the permission to transcribe the record.
Also 'some reasons for missing records' - should it read 'missing'? could
read some reasons for records not found, or records unavailable/not
registered?

This solution will also reduce the influx of missing entries reports from
users.  We may need a UX page design if required.

**Comment by KristinaGadzhieva** [comment]
Can be closed. The MVP implementation is addresed in #397.
