### ISSUE TITLE
502 Proxy error

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#408]
On both Beta and Test 3 (Saturday 2nd October 21)

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/5c197e25-6289-440d-a0bf-e612587042d8)

Is this the same issue that you faced on Friday 1st October @Vino-S ?

**Comment by Vino-S** [comment]
Hi @DeniseColbert ,
Yes, I got the same error yesterday.
I think the server is re-started but I am not sure

**Comment by richpomfret** [comment]
Fixed.
