### ISSUE TITLE
Update About Faq (part 1)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#410]
- [ ]  Edit those with the  'needed for BETA' and 'needing work' tag
 - [ ] remove other faq 'not needed for Beta' and 'needing work' from this version
 - [ ] readability / accessibility check on this version

**Comment by PatReynolds** [comment]
Is the AO version needed for testing, or is it for Beta (and the previous version for testing)?

Should I be updating the Needed for Beta paragraphs from previous version on previous version, or updating on the AO version?

**Comment by AlOneill** [comment]
@PatReynolds As I understand things, the [FAQ (AO remix)(https://test3.freebmd.org.uk/cms/about/draft-frequently-asked-questions-ao-remix) is the version being readied for testing and beyond.

I was not aware that you had not finished your editing — apologies. There are some questions that need addressing — these are detailed at the top of the page. Are there other aspects that you want to change in readiness for testing?

**Comment by PatReynolds** [comment]
I think it may be easiest if we go through this together on Friday, @AlOneill  (or at anoher time convenient for you).  

I also need to create new drafts of " Who owns the FreeBMD database and runs FreeBMD?" and "Why is it so difficult to submit a correction?"  for wider review.

**Comment by PatReynolds** [comment]
Duplicate of #214 so closing.
