### ISSUE TITLE
Text in search form is truncated on default settings

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#412]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/2cb0b00c-8fe0-41fb-9a0a-facc040e0705)

**Comment by DeniseColbert** [comment]
Is it possible to remove some padding?  @Vino-S

**Comment by PatReynolds** [comment]
This appears to be fixed (a possible duplicate story)
