### ISSUE TITLE
Improve More Information row

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#414]
The current hover state for each icon should be the default, and hover indicated by (for example) the dashed line appearing, ideally being fully visible as opposed to the top being missing per current state.

Example, for discussion:

![BMD2](https://user-images.githubusercontent.com/19173257/140520179-0d89f5d2-438f-449e-bd0e-d442fb83b160.png)

**Comment by PatReynolds** [comment]
Done, so closing.
