### ISSUE TITLE
Entry Details page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#415]
Add text below the table in the Entry Information Page:.

Suggested text:
Do you need help with this?  There is information about quarters, districts, and how to find the partner in a marriage in the Help section. Use the link in the menu at the top of the page.

**Comment by AlOneill** [comment]
@PatReynolds Where to find that information is missing — should there be a link to "Help", that would need to open in a new tab in order to make returning to results straightforward, or simply advice to look in "Help"?

**Comment by DeniseColbert** [comment]
Text only at this point, **to test** whether to include a link.

**Comment by PatReynolds** [comment]
@PhilipClarke712  wrote on 24 Jan 2022: (a comment on story re absence of back buttons on the Records page
The Entry Information page currently links to the relevant UKBMD page which has a 'bit more history information' than is given on test3 Records Tab - District Information page: but the latter already has a link to the UKBMD page. So, for instance, we could swap the District link on the Entry Information from UKBMD to the Records Tab - District Information page. Note: there is another story covering Districts and the relationship between the results page and the District Information Page hyperlinked to it.

I don't think we need two links on the Entry Information page: one to UKBMD and the other to the Records Tab - District Information page.

**Comment by DeniseColbert** [comment]
@AlOneill text suggested in story description should be enough to direct users to help.

**Comment by DeniseColbert** [comment]
@Vino-S to deploy to test3

**Comment by DeniseColbert** [comment]
@DeniseColbert to test on test3 (and Alison)

**Comment by DeniseColbert** [comment]
Text isn't there:
![image](https://user-images.githubusercontent.com/19173257/204522576-61bc370d-9cfe-47de-b115-2bcd529f83ca.png)

**Comment by DeniseColbert** [comment]
@Vino-S will have a look for the disappearing text

**Comment by DeniseColbert** [comment]
@Vino-S could you investigate please?

**Comment by DeniseColbert** [comment]
Text still not present, did you take a look @Vino-S ?

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Deployed, closing
