### ISSUE TITLE
unique names along with district information

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#421]

**Comment by richpomfret** [comment]
Apparently now complete - on TEST3.

**Comment by DeniseColbert** [comment]
Appears to be working well, functionally. A few minor issues with display but I'll make a separate story

**Comment by AlOneill** [comment]
@DeniseColbert I agree that the presentation could be improved (and the contents made more accessible). I will comment in detail on the new story, once it is created.

**Comment by AlOneill** [comment]
@DeniseColbert have you created the story for issues with the "unique names along with district information". I could not find it, but perhaps my search terms were incorrect?
