### ISSUE TITLE
Improve Print Page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#422]
Print page currently has "Column 1 has link to details of record; Column 2 can be sorted on First Name; Column 3 can be sorted by event." this applies to the results page, not the print page, so should be removed?

Display of results needs improve,ment - current example
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/71083df6-235b-4e16-95e2-1f66ef572ee7)
FreeBMD1:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/879b8c49-523e-4372-810d-8281bcd684f8)
Suggest single line is adopted, with the additional information added after testing has shown its importance to users

**Comment by PatReynolds** [comment]
see also #423

**Comment by richardofsussex** [comment]
Removed unwanted text as per request above.

**Comment by richardofsussex** [comment]
Make the instructions more separate from the listing: call-out, or put a box around it.

**Comment by richardofsussex** [comment]
As this screenshot (hopefully) shows, the instructions now have a box around them, and they are suppressed completely in the printed output:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/df6acefa-04e0-45d6-a38b-c13e0bdf0aa7)

**Comment by Vino-S** [comment]
Deployed
