### ISSUE TITLE
Make CSV download and printable format limited to 50 results.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#423]

**Comment by PatReynolds** [comment]
See also #422

**Comment by DeniseColbert** [comment]
I think it's pretty universal now that browser Print... function allows PDF download:

![Screenshot (20)](https://user-images.githubusercontent.com/19173257/143891758-ae4ec138-d909-4db1-818c-4365dc988688.png)

Perhaps this needs testing on various browsers? I tested Chrome, Edge and Firefox. The former two browsers offer the Print function on right-click, the latter via the browser hamburger menu. 

We would need to update the Help, perhaps with some general guidance.

**Comment by DeniseColbert** [comment]
@Vino-S to test on Safari, @PatReynolds to test on DuckDuckGo and Komodo

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Thanks Vino :)

**You can print these results or download to PDF using your right-click or browser menu.**

Could this be added to the Results page, perhaps where indicated below?

![image](https://user-images.githubusercontent.com/19173257/150831002-03b654d7-2bd1-49fc-b345-332bdb3fee08.png)

**Comment by AlOneill** [comment]
@DeniseColbert how does a keyboard-only user right-click? And what is meant by "browser menu"?

**Comment by AlOneill** [comment]
@DeniseColbert I've done some reading and testing and can say that, to cut a long story short, right-clicking by keyboard alone on a Mac is impractical. I cannot test on Windows.

Who wants their results saved as a PDF file? I did manage to save the page using the keyboard only, as text without the HTML, but it was a right palaver and the file would need a lot of editing to be useful to a researcher.

I agree with @Captainkirkdawson that a button to download a CSV file would be so much more convenient.

@Vino-S in the listing, there is a space missing between the District name and the opening bracket.

**Comment by DeniseColbert** [comment]
Thanks, @AlOneill. We already have the Download CSV option, so perhaps that's enough and we can remove this altogether? Although I think it's fair to say that lots of our users won't have a clue what CSV is...

I find saving PDFs a Good Thing in my research. It helps me to keep digital records without printing pages of info, but allows me to do so if I want to.

**Comment by AlOneill** [comment]
@DeniseColbert Oops, missed that! Mea culpa.

However, there is an issue. I can open the "Tools" drop-down with "Space", but I cannot select any of the options — I would expect to use the arrow keys to move between the choices.

**Comment by AlOneill** [comment]
@DeniseColbert Trying again, I find that "Tab" and shift-tab takes one through the choices. This is not the expected behaviour and will need explaining for our users.

**Comment by AlOneill** [comment]
@Vino-S @DeniseColbert The WebAim site has a listing of expected keyboard-only navigation:
https://webaim.org/techniques/keyboard/#testing

**Comment by richpomfret** [comment]
Update - @Vino-S currently looking to see if this is possible.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
@DeniseColbert

**Comment by DeniseColbert** [comment]
I can't see changes in Test 3

It's still 'Printable Format' in the Tools menu:

![image](https://user-images.githubusercontent.com/19173257/166492822-88ed72f7-7930-426c-aeee-9d8ed778b76f.png)

And there's nothing about Printing on the resulting page:

![image](https://user-images.githubusercontent.com/19173257/166493086-11f946e8-2760-435b-943e-0dc76975640d.png)

**Comment by richpomfret** [comment]
@Vino-S can you check this again? Denise could not find the updates you mentioned.

**Comment by PatReynolds** [comment]
Leave as 'printable format' but have a question in initial testing.

Consistency with FreeCEN/FreeREG needed.

**Comment by DeniseColbert** [comment]
Leave as printable format for now but add text to printable page.

**Comment by DeniseColbert** [comment]
https://github.com/FreeUKGen/FreeBMD2/issues/423#issuecomment-1020337555

This does need adding to REG and CEN also

**Comment by DeniseColbert** [comment]
Decision: add another option to dropdown: Download as PDF

**Comment by KristinaGadzhieva** [comment]
Amir, please have a look at Tools menu

**Comment by richardofsussex** [comment]
I've restored the list of results in the Print friendly version (required an explicit @timeout = false in the controller), amended the wording as requested and tweaked the format of the listing:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/80807259-096b-4d0b-8118-4dffb0235e3f)

**Comment by richardofsussex** [comment]
Note that the request to change the menu item to "Download/print" has been cancelled (twice) in the comments above. That's why it hasn't changed!

**Comment by richardofsussex** [comment]
Make the instructions more separate from the listing: call-out, or put a box around it.

**Comment by richardofsussex** [comment]
Set a limit of 50 for both printable format and CSV download.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by KristinaGadzhieva** [comment]
Doesn't work in printable format. @Vino-S please have a look

**Comment by KristinaGadzhieva** [comment]
when the number of results is more than 50, the print button can be hiden

**Comment by DeniseColbert** [comment]
Use of Print dialogue box means that the browser will print everything on screen, so Vino has removed the Print/Download buttons from search results pages with more than 50 records.

@Vino-S  to explore how we can tell people that we allow a max of 50 records to be downloaded

**Comment by KristinaGadzhieva** [comment]
To check on Beta.

**Comment by richardofsussex** [comment]
I had a note to check the GEDCOM download. I find that it works as per the spec - if 100 records at a time are displayed, it will only download the first 50. However I don't see any text or message advising me that I haven't got all 100 records in my download.

**Comment by richardofsussex** [comment]
@Vino-S please implement this

**Comment by Vino-S** [comment]
Ready for testing in beta

**Comment by KristinaGadzhieva** [comment]
Works on Beta, can be closed
