### ISSUE TITLE
County selection box cuts off longer text

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#425]
Is it possible to have the box a minimum character width? This should be the length of the longest entry.

We could lose some width from the Volume and Page fields if necessary, I think?

**Comment by PatReynolds** [comment]
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/d34396ac-fde5-49c0-b644-ab6d5c88955e)
No different on Test3 or Beta.
 
However now a slidy bar underneath, so allocating to a future version

**Comment by Vino-S** [comment]
REady for testing in test3
