### ISSUE TITLE
End of year in date range selection boxes is cut off

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#427]
The end of the year is cut off in some views.

Possible solutions (for discussion)
a/ make it a text entry box
b/ reduce the padding
c/ reduce the font size

**Comment by PatReynolds** [comment]
At 80% on both tests3 and beta
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/705335d5-aea3-43c8-bf55-3f424d057b29)
Fine at 100%
Fine on a pixelXL phone

**Comment by Vino-S** [comment]
REady for testing in test3
