### ISSUE TITLE
End ofmonth cut off in date range selection

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#428]
The end of the month is cut off in some views (this story updated as year cut off is #425)

Possible solutions (for discussion)
a/ make it a text entry box
b/ reduce the padding
c/ reduce the font size

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/4a1576b8-ac1d-484f-8e29-bfe66f698ce6)

Fine at 100% and on Pixel XL, cut off in view above at 90%

**Comment by Vino-S** [comment]
REady for testing in test3
