### ISSUE TITLE
'Why change?' page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#43]

**Comment by richpomfret** [comment]
@PatReynolds to add link. Draft in refinery - /cms/about/why-is...

**Comment by DeniseColbert** [comment]
Assigned myself so that I can publicise the page when made live.

**Comment by PatReynolds** [comment]
Discover (on test3) that this is the FreeCEN page and needs more work!!! Moving back to Sprint Backlog

**Comment by PatReynolds** [comment]
Discover (on test3) that this is the FreeCEN page and needs more work!!! Moving back to Sprint Backlog.

Update: now ready for checking / improvement sugesstion at https://test3.freebmd.org.uk/cms/about/draft-why-is-freebmd-changing
@DeniseColbert  could you take a look?

**Comment by DeniseColbert** [comment]
- Full stops missing at the end of paras 1 & 2. 

- "We are working towards **_a implementing 'as good as' the existing FreeBMD website_** (FreeBMD1) in almost every area" needs attention

Apart from that, all good.

**Comment by PatReynolds** [comment]
Done, could you make sure that second one now makes sense?

**Comment by DeniseColbert** [comment]
Yep, that's good.

**Comment by Captainkirkdawson** [comment]
Sorry but I find this page totally inadequate as a reason for making a change to BMD and investing the time and effort expended so far and that required for delivery.

**Comment by PatReynolds** [comment]
Thanks, Kirk, I'll take another look at it.

**Comment by PatReynolds** [comment]
@Captainkirkdawson  @DeniseColbert @richpomfret could you take another look, please?

**Comment by Captainkirkdawson** [comment]
Better but hardly compelling

**Comment by richpomfret** [comment]
Consider closing or indeed iterating (we can create another story if helpful).

**Comment by DeniseColbert** [comment]
I've had a look and tidied up some of the formatting/language. If @Daniel-silve1ra and @KatyMawhood are happy, we can close and count this as done .

**Comment by KatyMawhood** [comment]
@DeniseColbert Looks good to me. The new UX team hasn't had the opportunity to influence any of this, but I appreciate all in the works from wider BMD2 team and previous volunteers. 👍

**Comment by richpomfret** [comment]
@richpomfret to take a quick look.

**Comment by richpomfret** [comment]
Let's deploy this version and we can always create a new task to iterate this page if needed.

**Comment by DeniseColbert** [comment]
Has this been deployed? Do we need a story for linking to this page in About/Help?

**Comment by PatReynolds** [comment]
Page is signed off and deployed.

What is _not_ there yet is the link text from the About page. Part of #170.
