### ISSUE TITLE
Test Save Search feature: 

### ISSUE THREAD

**Issue by Vino-S** [FreeUKGen/FreeBMD2#433]
Save Search feature is available when logged in.

`View Saved Searches` in `Your Actions` lists the users saved searches.

On Running Saved Search we have a **Compare** feature on the search results page.  This feature displays new and old search Results. **Compare** is only available when we Run a Saved Search

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Seems to work well!
