### ISSUE TITLE
Review existing pages/drafts on Test 3

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#443]
@PhilipClarke712 noted "Two years ago I did not really know the difference between an html page and and shtml page: so a lot of the shtml pages were put in Refinery as html pages. They probably of no use because they can't pull up Perl page"

**Comment by DeniseColbert** [comment]
@PatReynolds and @DeniseColbert to review

**Comment by PatReynolds** [comment]
I can't see any page on Refinery that is not a html page (or is marked as Developer) and will be made live for testing (phase 3) - other than the Records page, which does not yet exist.

**Comment by richpomfret** [comment]
Pages/drafts reviewed and now closing.
