### ISSUE TITLE
Change to District information table in Records tab

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#446]
Also in the District information table, the link text "Click here for more information" will not be meaningful out of context — which is how it could be heard. I suggest, using the Hackney example, "More information about Hackney on UKBMD (opens in new tab)".

**Comment by Vino-S** [comment]
REady for testing in test3

**Comment by PatReynolds** [comment]
@PatReynolds top test

**Comment by PatReynolds** [comment]
Tested, just as requested, thank you.
