### ISSUE TITLE
Amend help page with info for smartphone users

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#447]
Text: It is possible to use most smartphones for searches. However, given the nature of the subject matter, this website is best viewed on a device with a screen size of at least 1024 by 768 pixels, in landscape view.

**Comment by PatReynolds** [comment]
Added to the bottom of help (in DRAFT help, under the live help page on test3).

**Comment by richpomfret** [comment]
To discuss in documentation meeting.

**Comment by DeniseColbert** [comment]
Done, closing
