### ISSUE TITLE
Sorting of results lost on moving to a subsequent page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#457]
Rich observed nexpected results when sorting by year across multiple pages. Initially sorts by year with oldest first, but on page 2 it then sorts by year with newest first.

I would expect the sort to remain consistent across multiple pages.

Vino and Pat confirmed that this was  not just on ipads/mobile

Denise to test with the various types of sort

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by PatReynolds** [comment]
Tested, works perfectly.  Thanks, Pat
