### ISSUE TITLE
Add link to Additional Search Options (Help) page in the box on the form

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#468]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/81ecb725-5c88-4031-9066-f426906aae46)

**Comment by DeniseColbert** [comment]
Moving to On Ice as this feature will be removed if Autocomplete is successful

**Comment by KristinaGadzhieva** [comment]
Not relevant for MVP scope now
