### ISSUE TITLE
Understand how district names should be displayed (part of #450)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#472]
Some (but not all) districts in the records pages have dupulicate data entry, e.g.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/73f39f59-87c3-4039-af94-a30cfe114d5e)
Bingham has just the name
Birkenhead (1861-1998) has name+years
Birmingham (1837-1924) has name+years
Birmingham (1932 onw) has name+years

Questions for Vino:
Can we remove the years from  thame names of singletons (e.g. Birkenhead (1861-1998) becomes Birkenhead) without problems?

Are Birmingham (1837-1924) and Birmingham (1932 onw) one data set or two?

Could we show the two Birminghams with the name simply "Birmingham", and the choice of which set means that the data for the correct Birmingham is shown?

**Comment by PatReynolds** [comment]
@PatReynolds to see what is in FreeBMD1

**Comment by PatReynolds** [comment]
This is FreeBMD1: https://www.freebmd.org.uk/district-list.html

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/eb2ad752-ca98-4b5a-8924-67840d8fe4ab)
The links should go to the UKbmd page, e.g. early Birmingham is here: https://www.ukbmd.org.uk/reg/districts/birmingham.html and later Birmingham

What is missing from this page is the information on what is in which volume:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/7be79cb7-9c9c-4e1b-a5f7-3cbe94c41b45)

**Comment by DeniseColbert** [comment]
This involves changing the table in the Records pages to incorporate the extra columns
