### ISSUE TITLE
'More about searching' — improve section there on wildcards

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#474]
The information about wildcards on 'More about searching' needs refining to account for the differences between the behaviour in First Names as opposed to Surnames — it needs some corrections and some clarifications.

**Comment by AlOneill** [comment]
Am in the process of testing and then re-writing the information.

**Comment by AlOneill** [comment]
Draft version of re-write done: https://test3.freebmd.org.uk/cms/help/draft-more-about-searching

Ready for review.

**Comment by PatReynolds** [comment]
@PatReynolds and @DeniseColbert to review

**Comment by PatReynolds** [comment]
Looks fine, thank you @AlOneill

**Comment by PatReynolds** [comment]
Do not use wildcard: use wild card or wild-card (Pat to check wit NVIDIA to see if both acceptable, but wild card is preferred).

**Comment by AlOneill** [comment]
DRAFT page updated using 'wild card' and 'G.R.O.'

Also removed instances of target="_blank" and adjusted link text accordingly.

**Comment by PatReynolds** [comment]
In NVDA wildcard, wild-card and wild card are all pronounced exactly the same.

**Comment by PatReynolds** [comment]
@AlOneill is this now ready to be deployed?

**Comment by PatReynolds** [comment]
Add in danger of searching for a surname starting with a wildcard (may well time out).

**Comment by AlOneill** [comment]
@PatReynolds  the 'danger of searching for a surname starting with a wild card' is already included.

Page is now sync-ready.

**Comment by AlOneill** [comment]
@PatReynolds the updates are not visible on beta because it has not been synced from t3. Any particular reason for the delay?

**Comment by DeniseColbert** [comment]
@vino to talk to lemon re. sync

**Comment by DeniseColbert** [comment]
Sync is done

**Comment by AlOneill** [comment]
The ["More about searching"](https://beta.freebmd.org.uk/cms/help/more-about-searching) page on beta is the old version and not the updated version as on t3 — https://test3.freebmd.org.uk/cms/help/more-about-searching

**Comment by DeniseColbert** [comment]
@Vino-S to check the sync

**Comment by DeniseColbert** [comment]
Vino to talk to lemon about images not syncing

**Comment by DeniseColbert** [comment]
Lemon has fixed so could you please check @AlOneill ?

**Comment by AlOneill** [comment]
'Help' and 'More about searching' are now both as expected. Closing.

**Comment by AlOneill** [comment]
I cannot close, but issue is now ready for closing

It turns out that I cannot change the pipeline in the drop-down box, but I can drag the card to 'Closed'. Odd.
