### ISSUE TITLE
Search form: unable to scroll options in County select

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#476]

**Comment by AlOneill** [comment]
I can scroll in the District select box but not the County box which makes it almost impossible to select more than one County.

Also, keyboard navigation with multiple selections does not seem to work. Maybe I have forgotten how to do it??

BTW, I've never tried to select multiple items from a select box using a screen-reader — I have no idea how to do that and will need to do some reading first

**Comment by PatReynolds** [comment]
@PatReynolds to test to see how it is working at the moment.

**Comment by AlOneill** [comment]
@PatReynolds 
**Update**: Chrome and Safari are fine, but the County box will not scroll on Firefox. It might be because the OS on my laptop is no longer supported and my Firefox version is an 'Extended support release' . I'll have to get a new laptop anyway (for a number of reasons), so maybe this is not an issue on a supported OS. [sigh]

**Comment by PatReynolds** [comment]
@DeniseColbert to test with firefox.

**Comment by AlOneill** [comment]
@DeniseColbert now working so closing
