### ISSUE TITLE
Footer markup mangled on t3

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#478]
The pages are being served up on t3 with this markup for the `footer` element:

`<footer clabeass="site__footer" role="contentinfo">`

where the nonsense word 'clabeass' should be `class`

**Comment by Captainkirkdawson** [comment]
corrected

**Comment by PatReynolds** [comment]
Still to be corrected on FreeBMD2

**Comment by PatReynolds** [comment]
Resolved now on FreeCEN and FreeREG, still needs addressing on FreeBMD.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by AlOneill** [comment]
Corrected on BMD t3. Thanks, @Vino-S
