### ISSUE TITLE
Bluelight issue (Review wishlist/survey feedback)

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#48]
To review what has been suggested. Initially UX requirements to be extracted and looked at - to then add to requirements/roadmap.

**Comment by PatReynolds** [comment]
Another comment was that colours containing blue will be more affected - have put the comments here: https://docs.google.com/document/d/1qwhZVwff_lyJMmsG1kWgsIFlsWYXD5UDgGmJy5BQ2bE/edit?usp=sharing
@AlOneill  can you confirm that the colours for FreeBMD are (well) inside the 4.5:1 ratio?

**Comment by AlOneill** [comment]
@PatReynolds No, I can't. The question of contrast is not simple: we have chosen not to underline links, so all 4 project colours — teal, magenta (BMD), lavender (CEN) and whatever we are calling the REG blue — have been chosen to give a contrast ratio of at least 4.5:1 versus both white (page colour) *and* the redefined default text colour, which is a little darker than the current default text. This was not easy to achieve.

As a result, the various ratios are *not* 'well inside' — that is, *not* much greater than 4.5:1 — and there is no way that they could be so.

I have not looked at the 'blue light filter issue' and have no prior knowledge of what is being discussed. I will comment again once I know some more.

**Comment by PatReynolds** [comment]
@PatReynolds to speak to @AlOneill about the issue

**Comment by PatReynolds** [comment]
We concluded that at this point the additional work involved was very large, and since users have the option of turning BlueLight off, and it is not part of the AA standard, we would not implement any changes.
