### ISSUE TITLE
Error message upon searching

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#480]
Some of the searches I'm doing are returning this error message

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/1a7d7729-e0aa-4490-941b-535696a43c40)

E.g. searching for a birth for *akinkunle in Greater London (looking for the Smith-Akinkunle in FreeBMD1)

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/e625fdb2-b264-4f8a-ada7-4720a18fd8de)

Is there an issue with wildcard searching perhaps?

**Comment by richpomfret** [comment]
Discussed changing the text or forcing user to select District in search - decided upon changing the error text. @DeniseColbert to investigate next steps/text.

**Comment by DeniseColbert** [comment]
Draft text in this document, for all projects: https://docs.google.com/document/d/1QObP5k0KrEK2IYvq4d4Od8uuy_E8jZJ9UggEJugXNWc/edit?usp=sharing

**Comment by DeniseColbert** [comment]
@Captainkirkdawson does putting in a date range on REG slow the search?

**Comment by DeniseColbert** [comment]
Actually, this seems more like a Timeout error? If so, we'll need to show the appropriate message for this type of search.

The "Too many results" issue needs a new story - will make it now.

**Comment by Captainkirkdawson** [comment]
@DeniseColbert Yes but not too much

**Comment by PatReynolds** [comment]
@AlOneill to send @Vino-S a screenshot.

@AlOneill will send a link to accessibility of error messages

**Comment by AlOneill** [comment]
@Vino-S have sent link to accessible notifications by email.

Tried to set up the screenshot, but with no success. (What on earth did I do before?)

**Comment by PatReynolds** [comment]
504 Gateway Timeout on FreeBMD1, so "error" is not with FreeBMD2.

Error message needed.

**Comment by PatReynolds** [comment]
Error message should explain use of the Surnames page to identify possible names, rather than using an asterisk.

**Comment by richardofsussex** [comment]
An "ends with" search on beta still times out, but on test3 it returns a result. (Note that the record in question has surname AKINKUNLE in test3, i.e. no "Smith-" on the front of it. So a simple search would have found it anyway. Still, this looks like another area where we could usefully update beta.)

**Comment by DeniseColbert** [comment]
Beta:
![image](https://user-images.githubusercontent.com/19173257/196429560-bf9f9a43-ed85-4a45-844d-90b784fe32f1.png)

Test3:
![image](https://user-images.githubusercontent.com/19173257/196429617-801b1141-08c9-4ded-bfca-d6eff8f13c5f.png)

Pat suggested above: Error message should explain use of the Surnames page to identify possible names, rather than using an asterisk.

**Comment by DeniseColbert** [comment]
Decision: refer to help page on name searching

**Comment by DeniseColbert** [comment]
Added text below to the error page document (https://docs.google.com/document/d/1QObP5k0KrEK2IYvq4d4Od8uuy_E8jZJ9UggEJugXNWc/edit) for timeouts:

![image](https://user-images.githubusercontent.com/19173257/196626992-b871d637-eb11-43ee-9b1e-09a5419f6237.png)

**Comment by DeniseColbert** [comment]
I've modified these to be the same, with @AlOneill 's help. So the advice is the same but the error is different:

![image](https://user-images.githubusercontent.com/19173257/196959638-69451764-2ba7-44f5-9b5d-d98a19c47f52.png)

@Vino-S please note this means a small change to the "Too many results" page

**Comment by DeniseColbert** [comment]
So Too many results page should have the same text as the new Search timed out page.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by DeniseColbert** [comment]
Ready for deployment

**Comment by DeniseColbert** [comment]
Done, closing
