### ISSUE TITLE
"Too many results" page needed.

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#483]
We need a Too Many Results page, with the FreeBMD2 text from page 2 of https://docs.google.com/document/d/1QObP5k0KrEK2IYvq4d4Od8uuy_E8jZJ9UggEJugXNWc/edit?usp=sharing

**Comment by DeniseColbert** [comment]
We are not telling users that their search has returned too many results. 
Also, users seem to hit a ceiling of just under 3000 records with no transparency as to why the subset of results are chosen to be displayed, which makes it look like the dataset could be complete (but it isn’t, and we’re not alerting them).

**Comment by PatReynolds** [comment]
I have moved your comment to a new story, Denise.
Remaining to be resolved: is it true that date range should be last in the list (see Alison's comments - do you know @Vino-S 
Do we also want to suggest restricting date range to most likely dates?

**Comment by PatReynolds** [comment]
Vino suggests on FreeBMD2 First option should be date as not everyone will be aware of District or County. 

@PatReynolds to ask @Captainkirkdawson whether the advice is relevant only for MongoDB, not the Mysql of FreeBMD.

**Comment by Captainkirkdawson** [comment]
@PatReynolds I have no idea how FreeBMD handling a max out; I know they have one of 3000 nor how you are going to capture that in FreeBMD2
![maxout](https://user-images.githubusercontent.com/2874694/159334844-015dac25-2100-4ed5-8716-e2c411e692a2.png)

**Comment by PatReynolds** [comment]
Thanks @Captainkirkdawson will ask those who know the MySQL way of handling searches.

**Comment by PatReynolds** [comment]
As adding county or district is the hardest, I've left it last, but moved date below type.

**Comment by DeniseColbert** [comment]
We need a Too Many Results page, and the FreeBMD2 text from page 2 of https://docs.google.com/document/d/1QObP5k0KrEK2IYvq4d4Od8uuy_E8jZJ9UggEJugXNWc/edit?usp=sharing

**Comment by richpomfret** [comment]
To move into test and then review/test with the limit currently commented out (via @richardofsussex)

**Comment by DeniseColbert** [comment]
@DeniseColbert to test with a large search hit to check text against document

**Comment by DeniseColbert** [comment]
It took a lot of tweaking to avoid the Search took too long message and hit the Too many results message. When does one become the other?

**Comment by DeniseColbert** [comment]
Decided to use too many results text with addition of Try to avoid wildcard searches if you are experiencing this issue (owtte) - Denise to refine and update story

**Comment by DeniseColbert** [comment]
Added a line to the text see below) on document (https://docs.google.com/document/d/1QObP5k0KrEK2IYvq4d4Od8uuy_E8jZJ9UggEJugXNWc/edit?usp=sharing)

![image](https://user-images.githubusercontent.com/19173257/196630010-e1ad6647-5880-4686-a3a3-f1dc49d11ca3.png)

**Comment by richardofsussex** [comment]
With the timeout, you get a more cryptic message:
![image](https://user-images.githubusercontent.com/2197102/196669878-11bb7293-7d0c-4856-9d3d-a03158f176e7.png)
I suggest that this is expanded to include the same suggestion about making the search more specific.

**Comment by DeniseColbert** [comment]
Relates to #480 so closing
