### ISSUE TITLE
Cannot find marriage potential partners (link from the Entry Information to the entries for the page in question broken)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#486]

**Comment by PatReynolds** [comment]
eg link to https://beta.freebmd.org.uk/62715b989c5d614a4b480ccc/689360/same_page_entries?district=Malton&locale=en&page=311&quarter=5&record=3&volume=24 

Search for Alcock marriage, North Yorkshire Jan to Mar 1838

**Comment by PatReynolds** [comment]
Same search in 1929 worked (spouse name).

**Comment by richardofsussex** [comment]
This appears to be fixed in test3. Still fails in beta.

**Comment by richardofsussex** [comment]
Now works as intended in both test3 and beta. Can be closed.
