### ISSUE TITLE
Update text on home page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#487]
Place as Message of the Day
Please be aware that this is a test development website for FreeBMD. The database is not updated. It should be used by developers and testers only. It should not be used by the public. For access to our records please visit the original FreeBMD site.

Change to two lines (beak after "testers").

Then needs deployment to beta.

**Comment by AlOneill** [comment]
Message updated on t3. Ready for sync to Beta.

**Comment by AlOneill** [comment]
@PatReynolds Beta has not been updated yet. Will this be done with a sync? Or should I update directly on beta?

**Comment by DeniseColbert** [comment]
This will be brought over in sync @AlOneill

**Comment by AlOneill** [comment]
Not synced yet

**Comment by DeniseColbert** [comment]
@Vino-S to check

**Comment by DeniseColbert** [comment]
@AlOneill to check it's there

**Comment by DeniseColbert** [comment]
Done so closing
