### ISSUE TITLE
FreeBMD1 MH Advert - via spectacles symbol - header says Entry Information Page - Page body

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#497]
- [x] Agree format with MH
 - [ ] Place on test

**Comment by PatReynolds** [comment]
@Vino-S can you give this one an estimate please? It seams easiest/least likely to cause issues, so suggest you move on to this while I am arranging testers.

**Comment by richpomfret** [comment]
Now ready for testing.

**Comment by PatReynolds** [comment]
Feedback received 9/8/2022- Pat to pass a concern on to My Heritage, Vino to look at other issues raised.

**Comment by richpomfret** [comment]
Now deployed to production.
