### ISSUE TITLE
FreeBMD1 MH Advert -  Progress page (Coverage Chart in title) 

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#499]
@Vino-S is this page suitable for a side advert?  If so, please could you estimate it - if not suitable, please let me know.

**Comment by PatReynolds** [comment]
@PatReynolds to check position wanted with MH

**Comment by DeniseColbert** [comment]
@DeniseColbert to check with MH if top/side/both adverts are desired

**Comment by DeniseColbert** [comment]
Asked MH 6/9/22

**Comment by DeniseColbert** [comment]
@DeniseColbert to send to testing group and check the agreed list

**Comment by DeniseColbert** [comment]
Done, closing
