### ISSUE TITLE
Possible Volunteer for UX

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#5]
required by #12

**Comment by DeniseColbert** [comment]
Emailed KU 26/6/18

**Comment by richpomfret** [comment]
Me to provide details for recruitment sites for potential UX summer work.

**Comment by DeniseColbert** [comment]
Kingston Uni will only facilitate recruitment for paid positions

**Comment by DeniseColbert** [comment]
Please flesh out: https://docs.google.com/document/d/1ELCVpoBYj7yoHRnNVYvhLtCFnuvmlGWC8pbkMIKhRKw/edit#

**Comment by richpomfret** [comment]
@DeniseColbert  to contact Salford uni re: internship.

**Comment by richpomfret** [comment]
@richpomfret to review spec for UX.

**Comment by richpomfret** [comment]
Added a few bits - I think it's ready to send out. Perhaps we can request that those who are interested submit a few suggestions or mock-ups for how we might update the search experience?

**Comment by richpomfret** [comment]
Spec is now live on workinstartups.
