### ISSUE TITLE
Flag/link GRO as source of certificate in appropriate places

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#506]
From a FreeBMD1 user:
"I am sure that, once upon a time, on your splendid WebSite, I saw a note - probably with a Link - explaining how, by providing the data from one of your entries, one could obtain from the GRO the relevant Certificate, that may hold more data.
But I CANNOT find that now.
Plrase would you be so kind as to add that information - in many places.  It;s only a line or two and a Limk.
Pretty please ?"

**Comment by PatReynolds** [comment]
Draft document for review (placement and text)
https://docs.google.com/document/d/1CgBs6LTiLfirkPFS2YZo9OYoiSQKaDHoPhOSI0EiWgc/edit?usp=sharing

**Comment by DeniseColbert** [comment]
@AlOneill and @DeniseColbert to review Pat's document

**Comment by AlOneill** [comment]
The Help page has the definitive details of how to order a certificate — any changes should be made there and any links should go there, unless there is another, better candidate. **NEXT**, I will check the text against Pat's document.

**Comment by AlOneill** [comment]
Have begun work on a [DRAFT Ordering a Certificate](https://test3.freebmd.org.uk/cms/help/draft-ordering-a-certificate) page. Pat has based it on the original but has made a number of changes.

**Comment by AlOneill** [comment]
@PatReynoldsFUG 
I've made now two edit requests on your document so that I can ask questions and make comments more effectively. Awaiting response.

**Comment by AlOneill** [comment]
Now that I have edit access to Pat's document I've made a number of comments & questions there and repeated them on [DRAFT Ordering a certificate](https://test3.freebmd.org.uk/cms/help/draft-ordering-a-certificate).

I suggest we respond in a documentation meeting.

**Comment by KristinaGadzhieva** [comment]
We decided to add a link to GRO source into the text under the table.
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0RiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c7730955d9f1ce32112c5f38e2472213ecc5bec/Screenshot_1.jpg" alt="Screenshot_1.jpg" />

**Comment by DeniseColbert** [comment]
Deployed to Beta. We need to discuss/decide where the scan/postem info will appear in relation to this text

**Comment by KristinaGadzhieva** [comment]
Agree on the link to GRO

**Comment by richardofsussex** [comment]
We agreed on https://www.gro.gov.uk/gro/content/certificates/login.asp. @Vino-S please add a link to this URL. Thanks

**Comment by KristinaGadzhieva** [comment]
Deployed on Beta.
