### ISSUE TITLE
Sorting of names (in "Unique" Names)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#509]
The names in originals transcribed as Upper Case are sorted ahead of those transcribed as Title Case.  Within the group, they are sorted alphabetically as expected.

For ease of reading, all should be presented as Title case, and sorted alphabetically as one group.

**Comment by richardofsussex** [comment]
The collating rules will have this effect by default. The only way around this is to feed consistent data (e.g. all upper case) to the sort engine, and then convert it to a reader-friendly format (e.g. camel case) on output/display.

**Comment by richardofsussex** [comment]
My fix for #268 may well have fixed this issue as well. Please test and report back.

**Comment by DeniseColbert** [comment]
@DeniseColbert  to check if this still happens

**Comment by DeniseColbert** [comment]
It seems not:
https://test3.freebmd.org.uk/districts/107/unique_names?locale=en&record_type=birth

![image](https://user-images.githubusercontent.com/19173257/196433552-fb901124-3b6f-45a4-a6a8-31dd34b9fa94.png)

**Comment by DeniseColbert** [comment]
@richardofsussex to review

**Comment by richardofsussex** [comment]
Well, the code which generates these sorted lists makes no efforts in the direction of case-sensitivity:
![image](https://user-images.githubusercontent.com/2197102/196534439-2108a542-07d6-4265-86ea-0d3e9daf1c1b.png)
So I'm guessing that all those '.sort' statements ought to be '.sort_by(&:downcase)'.  Would you agree, @Vino-S ?

**Comment by richardofsussex** [comment]
OK, I've gone ahead and made those changes. @Vino-S could you please push to test3, so we can see if they have the desired effect? I don't have the relevant data to test the fix on my development system.

**Comment by DeniseColbert** [comment]
@Vino-S to push to test3

**Comment by DeniseColbert** [comment]
Denise to test

**Comment by DeniseColbert** [comment]
All good on Test3. Tried Beta but district page threw an error:

![image](https://user-images.githubusercontent.com/19173257/204543813-ee2bdd65-952f-44da-bd14-4e0afb44003f.png)

**Comment by DeniseColbert** [comment]
Denise to test after migration

**Comment by DeniseColbert** [comment]
@DeniseColbert to check beta

**Comment by DeniseColbert** [comment]
I had to really search but I found some in Bala with different casing:

![image](https://user-images.githubusercontent.com/19173257/214328490-dcdcadfd-3bd2-41f5-b857-15e13ceb4d0a.png)

**Comment by DeniseColbert** [comment]
Denise/Richard to check that this is Beta rather than test3

**Comment by richardofsussex** [comment]
You get the same pattern in both test3 and beta. I can't see any examples where the _same_ surname appears twice. This suggests that 'it' (a rake task?) is correctly generating a list of unique names, but it is failing to case-fold them before sorting them.

**Comment by Vino-S** [comment]
Code deployed to production

**Comment by DeniseColbert** [comment]
Done, closing
