### ISSUE TITLE
Modify white space

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#51]
See Coordination #1077

**Comment by DeniseColbert** [comment]
Chatting to @arswright-alt-uk today about the FUG website and white space, and he has some ideas about how we may save space above the fold on all sites. He's happy to have a brainstorming session/conversation Aviel, maybe in a couple of weeks?

**Comment by avielbassalian-freeukgen** [comment]
Sounds good to me. @arswright-alt-uk will Slack @ you to arrange.
I'm not far from finishing my v1 for layout. Can always change things around/iterate.

**Comment by DeniseColbert** [comment]
I think we should leave this open until the white space issue is resolved?

**Comment by PatReynolds** [comment]
Aviel has been discussing with Gray on slack. Meeting to be arranged.

**Comment by DeniseColbert** [comment]
Aviel/Gray to let Pat know briefly what the purpose and content of the documentation will be.

**Comment by richpomfret** [comment]
Need confirmation on advert placements. @PatReynolds to provide.

**Comment by PatReynolds** [comment]
Placement of adverts confirmed.  Neslihan and Aviel to consider white space issue now header placement confirmed.

**Comment by PatReynolds** [comment]
Converting to epic as decided in scrum 9/12/2019.

Individual stories need to be written.

**Comment by KatyMawhood** [comment]
@PatReynolds @richpomfret @DeniseColbert @Daniel-silve1ra 

Is this a system-wide project or specific to FreeBMD2? I'm trying to understand how this issue applies solely to FreeBMD2 and not the other sites.

**Comment by PatReynolds** [comment]
@Denise is this complete?  Can it be closed?

**Comment by DeniseColbert** [comment]
I think so- designs have taken this into account. If it arises in feedback we can create a new story.
