### ISSUE TITLE
Add links to Help

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#513]
Add to Help: the links to NI and Scotland (and Genealogy.ie) -  https://www.gov.uk/general-register-office

**Comment by DeniseColbert** [comment]
@AlOneill to see if these links are there already

**Comment by AlOneill** [comment]
The links are not there — I was thinking of some version of the FAQ or some-such. Will create a draft page and consider where best to put them.

**Comment by AlOneill** [comment]
@PatReynoldsFUG @DeniseColbert 
Links added to [DRAFT Help](https://test3.freebmd.org.uk/cms/draft-help) together with an obvious (I hope) entry in the "On this page" menu.

I debated with myself as to where in the page to put the information — let me know if you believe there is a better place! (I might disagree and than we can have another debate.)

**Comment by AlOneill** [comment]
@DeniseColbert 
This should now be in "Needs review", but I cannot move it [sigh].

**Comment by DeniseColbert** [comment]
I think we said this is ready for deployment @AlOneill ?

**Comment by AlOneill** [comment]
Yes, page is ready for deployment.

**Comment by AlOneill** [comment]
And I can update labels, columns, etc!

**Comment by DeniseColbert** [comment]
Hurrah!

**Comment by DeniseColbert** [comment]
Completed, closing
