### ISSUE TITLE
Pat to test  advert landing page to see what one gets

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#514]
FreeBMD1 issue re people not going clicking onwards from landing page

**Comment by PatReynoldsFUG** [comment]
Testing was needed (I think) on the results page? No advert there now.  In the details page, the advert is generic, not pre-filled

@DeniseColbert can you confirm which pre-filled advert is not getting people agreeing to the trial as expected?

**Comment by PatReynoldsFUG** [comment]
@DeniseColbert I am switching this to my volunteering hat - when there is a prefilled side advert that is not performing well back on FreeBMD1 please let me know and I'll test.

**Comment by DeniseColbert** [comment]
Superseded
