### ISSUE TITLE
Schema.rb out of sync with SQL database schema

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#522]
The schema for the Districts table in schema.rb:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/c454453e-a6ed-4f52-adf1-3b76adb5a296)
doesn't include the changes which have recently been made to the underlying SQL table from which the data comes:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/d5f92bd2-334e-4def-bdcc-83d70ecfc67b)
Presumably we need to update our test databases as well?

**Comment by Vino-S** [comment]
Changes deployed in test3

**Comment by DeniseColbert** [comment]
@richardofsussex to check this is OK

**Comment by richardofsussex** [comment]
The District Information listing now includes the 1993_4 To End field in both test3 and beta, so this issue can be closed. 
Note, however, that:
- we still have 'XX' for periods where the District was not active, rather than e.g. 'N/A', and for some districts the 1993_4 To End field is completely blank
- at some point I suggested (and IIRC even implemented) making the County into a link to a [new?] county page listing all the Districts in that county. I don't see any trace of that thinking/work now (found it: it is issue #521 which should be ready for pushing to test3)

**Comment by DeniseColbert** [comment]
Closing
