### ISSUE TITLE
More proactive help with names when searching (Autocomplete)

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#523]
Rather than telling our users to go off to a separate, hard-to-find page crammed with names and use the browser's 'find' command to hack through them, why don't we provide an autocomplete function on the search page which offers forenames or surnames matching what they have typed so far? If they have selected a District for their search, only offer names associated with that District.

**Comment by richardofsussex** [comment]
After discussion, we agreed that the autocomplete should always offer a selection from _all_ the names, rather than trying to filter by e.g. event type, District or date. This is compatible with the other search criteria (County, District, date, etc.), which are also not filtered based on the user's selections (apart from Districts being filtered by County).

As an initial piece of work, it was agreed that I would attempt to implement a suitable table structure, together with routes which return all names matching a given stem as JSON.

Concern was expressed about how this facility could be provided in an accessible manner.

**Comment by richardofsussex** [comment]
Just pushed branch fb_523_rbl, which contains autocomplete code which works (for me, at least!). It needed jquery-ui.js adding, plus some support CSS files. My approach involves creating two separate tables containing all the unique forenames and surnames - I've written a couple of rake tasks to update these tables from BestGuess. Currently these tables are in the SQL database because I found that easier to work with, but there is no reason why they can't be MongoDb collections. The rake tasks are in a single .rake file: they probably need refactoring to fit in with our overall approach to code design. (I'm assuming that these tasks will form part of the BMD database update code - they could take a while on 100 million records!)

The 'unique names' tables also have each name in lower case, and a count of the number of occurrences of the name - I thought these might be useful in future.

At present autocomplete cuts in straight away, as soon as a character is typed. When operating on the complete file we probably want to wait until two or three characters have been typed before invoking it.

We could apply this autocomplete approach to other fields in the search form, and indeed to the search forms in the other two projects.

Could @Vino-S please review my work, and either comment on it, or put it into test3 so that others can try this facility out?

**Comment by DeniseColbert** [comment]
Tested, works well!

**Comment by DeniseColbert** [comment]
@Vino-S to put this into MongoDB and then run Richard's rake task and share the steps for future rake tasks.

**Comment by richardofsussex** [comment]
Looking into matching names which are not at the start of a 'unique name'. MongoDb has a 'text' index type, but it only matches/fires on _complete_ words within a string.  That doesn't meet our requirements, which are to match as the user types.

**Comment by richardofsussex** [comment]
Changed strategy to use MongoDB collections as the source of autocomplete. This needs moving to test3, the rake tasks need to be run, then we can test whether this approach scales.

**Comment by DeniseColbert** [comment]
@Vino-S could you please do the above?

**Comment by DeniseColbert** [comment]
@Vino-S to run the rake tasks

**Comment by Vino-S** [comment]
ready for testing in test3

**Comment by richardofsussex** [comment]
OK: first impressions:
- the autocorrect terms are mixed case (some all uppercase; others mixed case), and the autocorrect matching is case sensitive. (This may be where the Colberts went!) We need to implement a strategy which is effectively case-insensitive, e.g. having all the autocorrect terms in uppercase and forcing input to uppercase as it is typed. Then the input strategy will match the search strategy (which is also case-insensitive)
- the input of subsequent characters is blocked until the autocorrect returns a set of suggestions based on what has been typed so far. As more characters are typed, I would expect the response to get quicker, but this doesn't seem to be the case. This amount of delay, as it stands, won't be acceptable to users

**Comment by richardofsussex** [comment]
Colberts ahoy! :-
![image](https://user-images.githubusercontent.com/2197102/217312898-f0a961d1-3d2d-4394-b9d7-3027f6250f5b.png)

**Comment by richardofsussex** [comment]
I've tried adding an index to the forenames and surnames collections, limiting the number of responses to 10 and making the search case-insensitive.

**Comment by DeniseColbert** [comment]
Yay!

**Comment by richardofsussex** [comment]
@Vino-S could you please push the updated fb_523_rbl branch to test3, so we can see whether my changes have the desired effect (or indeed any effect)? Thanks

**Comment by richardofsussex** [comment]
OK, that is now working somewhat better on test3. Please have a look and comment. The key question is: is the response time slick enough? 
![image](https://user-images.githubusercontent.com/2197102/218469296-f18479d6-87e4-4708-9c17-66a465ee3ab3.png)

**Comment by richardofsussex** [comment]
I wasn't getting any autocomplete on forenames, but this is because Vino has only managed to load up to "Elizabeth Grigson". (I was trying "Jane".) This fragment of the possible forenames table represents 1414022 distinct names, so it would get quite big if completed. More to the point - is this actually helpful for researchers? Should we just offer single forenames?

**Comment by DeniseColbert** [comment]
@vino to clear the collection then run the rake task (and report number of distinct names) for Richard to then test.

**Comment by richardofsussex** [comment]
As regards accessibility and autocomplete, a quick search turned up these guidelines: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/. While the 'pop-up' lines obviously appear without signalling a screen refresh, the text box we are aiming to populate _is_ part of the original page as loaded, so I don't see why it can't have suitable ARIA attributes. Does @AlOneill tell us what ARIA markup is required, or is it our job to work that out?

**Comment by richardofsussex** [comment]
It looks as though the rake task has run to completion. Now get a list of possible first names. The only issue spotted is the familiar one of the same name with different case, e.g.:
![image](https://user-images.githubusercontent.com/2197102/223552733-9ed831bb-c63f-4f3f-bc0c-186c6ff3615c.png)

**Comment by AlOneill** [comment]
@richardofsussex 
I'm not going to tell you exactly _how_ to make the combo box accessible mainly because I might not be around much longer due to failing health and so someone else (you, for instance!) needs to become comfortable with looking up such patterns and implementing them. However, I'm happy to test anything you come up with using a screen reader and make suggestions for improvements, if necessary.

Finding the guidelines means you have passed step 1. For step 2 I suggest that you next look at the Example (see page contents) that fits the particular type of box that you would like to offer and take it from there. You might decide to implement a simpler accessible ComboBox initially, just to get the hang of things. Up to you. Let me know when there is something I can test and I'll fire up the screen reader (and also look at the markup).

**Before you begin,** I note that #482 has not yet been completed. It is a simpler issue (using `alert`) on the face of it but it has much in common with this one. Please see my comments there as to why the attempted implementation does not work.

One note of caution: those guidelines often favour screen reader users at the expense of other users (those who cannot use a pointing device, for instance) so please be alert to the thoughtless use of `title` attributes, for example.

If you have any questions, do ask. Good luck!

**Comment by richardofsussex** [comment]
If we're going to tidy up the list of names so that each name only appears once, we should take the opportunity to agree on a 'preferred' format for both forenames and surnames (and then implement it in our autocomplete lists). Personally I would prefer initial letter in uppercase followed by lowercase for both types of name, but I know there is a tradition of putting surnames into upper case. Do we need to consult more widely?

**Comment by richardofsussex** [comment]
@Vino-S I have pushed an update to fb_523_rbl which forces forenames to initial uppercase then lowercase. Please re-run this rake task on the full test3 data, so we can see the result.

**Comment by DeniseColbert** [comment]
@Vino-S to let @richardofsussex know when Test 3 is back up for testing

**Comment by richardofsussex** [comment]
If the rake task has run, it had no effect. This is what I get for forenames: a mix of all lower case, normal case and upper case:
![image.png](https://images.zenhubusercontent.com/5d3970212c1c7b71d87ac39e/145ecc1b-9257-439b-abb6-536083a853f0)
@Vino-S please confirm whether this rake task has actually been run.

**Comment by DeniseColbert** [comment]
@Vino-S to look into this

**Comment by DeniseColbert** [comment]
@Vino-S to update the code for the rake task to deal with casing

**Comment by richardofsussex** [comment]
Yes, these are now fine on test3 and can be moved to beta please @Vino-S

**Comment by KristinaGadzhieva** [comment]
@Vino-S please, create a script to run a rake task

**Comment by richardofsussex** [comment]
Very few first names in the autocomplete on beta. Does the rake task need running for both first names and surnames on beta?

**Comment by KristinaGadzhieva** [comment]
Agree with Richard. I see a different number of first name and surname variants on test 3 and beta.
<img width="683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--500290c6a9b73692903f9be6bde5b7f52bb81756/screen1.jpg" alt="screen1.jpg" />
<img width="1092" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72dfcbd06e1aba0d86a652bcfe999df0de465629/screen2.jpg" alt="screen2.jpg" />

**Comment by KristinaGadzhieva** [comment]
Also we have a mix of uppercase and lowercase surname variants. Should we leave this as it is?  @DeniseColbert @richardofsussex 

<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--803c8a0333f3a7574f18d09935c2b92bd3cf515f/Screenshot_2.jpg" alt="Screenshot_2.jpg" />

**Comment by DeniseColbert** [comment]
@KristinaGadzhieva this has been fixed (old snip)

**Comment by DeniseColbert** [comment]
@Vino-S to contact @lemon-ukgen about scheduling of rake task

**Comment by KristinaGadzhieva** [comment]
On test3 now:
1. Mix of lowercase and uppercase in Surnames <img width="275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48f5358591071f7e8e19eaa4c9c0eab578ab3b7a/image.png" alt="image.png" />
2. Different formats for Names and Surnames. I think the format for both should be the same. (Initial letter in uppercase followed by lowercase for both Names and Surnames).

**Comment by richardofsussex** [comment]
Hyphenated surnames require an uppercase letter after each hyphen, as well as at the start of each name.

**Comment by KristinaGadzhieva** [comment]
@Vino-S  please move a hyphen
