### ISSUE TITLE
Revise Search and New Search buttons should be on screen

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#524]
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/8254b58b-7001-4e16-b5ac-44de32d94547)

**Comment by richardofsussex** [comment]
Sorry, I don't see the problem. In the screenshot above, these buttons _are_ on screen. What am I not understanding? Thanks

**Comment by DeniseColbert** [comment]
@Vino-S to move the buttons (including saved search) to in between number of results and Tools menu, and default-hide the search criteria box

**Comment by KristinaGadzhieva** [comment]
Done, can be closed
