### ISSUE TITLE
Remove Additional Search Options

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#528]

**Comment by richardofsussex** [comment]
Please just comment out the code that generates the additional search options box.

**Comment by KristinaGadzhieva** [comment]
Ready for testing on test 3.

**Comment by richardofsussex** [comment]
Yes, that's fine: they have gone!

**Comment by KristinaGadzhieva** [comment]
Thank you Richard! @DeniseColbert  I'll close this story then.

**Comment by KristinaGadzhieva** [comment]
@Vino-S Please, transfer changes to Beta
