### ISSUE TITLE
'Message of the day' not appropriate on beta? — should be deleted there

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#530]
The message of the day (the text that appears above the search form) on t3 has been synced to live (beta) where I do not believe it is appropriate. In which case it should be deleted or modified to be appropriate for beta.

**Comment by PatReynoldsFUG** [comment]
Might be needed on Beta to highlight changes in progress (e.g. "links to images are not working  at the moment, otherwise site is working as expected") to stop people pointing out that something known to be a problem is not working, or just assuming that we don't care that there is a problem on the site

**Comment by AlOneill** [comment]
Apologies — I put that badly: what I'm saying is that _that particular_ message should not be on beta. I agree that the ability to create a message should exist, so I am proposing that we **delete the message but not the container which is the file 'Message'**.

The issue is that every time a sync is performed, the 'Message' file on beta will be updated with the contents of that same file on t3. We need a strategy to correct the contents after each sync or a way of excluding the file 'Message' from the sync process.

What happens on CEN and REG?

**Comment by richardofsussex** [comment]
@Vino-S please check this and make changes if required

**Comment by KristinaGadzhieva** [comment]
ready for testing

**Comment by richardofsussex** [comment]
OK, I can confirm that the message has gone from test3. @Vino-S could please move this version to beta so we can test it there? Thanks.

**Comment by DeniseColbert** [comment]
Done: closing
