### ISSUE TITLE
BUG: district sorting has reverted to random (was #103)

### ISSUE THREAD

**Issue by PatReynoldsFUG** [FreeUKGen/FreeBMD2#533]

**Comment by richardofsussex** [comment]
I don't think it has 'reverted': we are (I think - correct me if I'm wrong) talking about the CSV output, which has _never_ been sorted. CSV output now reflects what the user sees in the currently selected page of output - the same records, in the same order. Previously they got _all_ the records in the result set, in a fairly random order. See branch fb_533b_rbl.

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richardofsussex** [comment]
Tested and OK. The sequence and number of records in the CSV output now always matches those of the current 'page' of results. Code can be deployed and issue closed.

**Comment by DeniseColbert** [comment]
Tested: can be deployed to beta

**Comment by DeniseColbert** [comment]
Done, closing
