### ISSUE TITLE
Fix district page navigation from search results

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#535]
District pages (and Names pages) accessed via search results need a "Back to search result". Possibly others.

**Comment by Vino-S** [comment]
ready for testing in test2

**Comment by KristinaGadzhieva** [comment]
To create a "Back" button

**Comment by richardofsussex** [comment]
I have added the search ID to the forward link to the District from the Search results listing, and used that to create a "Back to search results" button on the District page. Also, in this situation the two existing 'back' buttons (which go back to the list of Districts) are suppressed.

We need to do the same thing for the District link in the Entry information page, but at present I can't access a version of the source code which will display this page. Awaiting help from @Vino-S ...

**Comment by richardofsussex** [comment]
District link with search ID added:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/f673869c-30de-43e6-838d-3c963e9ece3c)
Updated District page:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/01ecdb46-948d-40d2-b578-c2f89980a000)

**Comment by richardofsussex** [comment]
The code in the `fb_520_rbl_2` branch now includes support for links back from the District page, either to an individual entry or to the search results, when the District link in the Entry Information page is clicked on.

This work needs to be merged/blended with work that @Vino-S has also done in this area.

**Comment by Vino-S** [comment]
Ready for test in test3

**Comment by KristinaGadzhieva** [comment]
on test 3 <img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmEyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9aaca5bf0b0625e12d8f1e3e1135d341c123a60f/Screenshot_1.jpg" alt="Screenshot_1.jpg" />

**Comment by KristinaGadzhieva** [comment]
Implemented. Can be closed.
