### ISSUE TITLE
Links to UKBMD (District table) opens in same tab

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#538]
Also: remove (External link:opens in a new tab)

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/86845300-7662-4d80-8f1f-590d35dbe846)

**Comment by Vino-S** [comment]
ready for testing in test2

**Comment by richardofsussex** [comment]
Is it the intention of this issue that the links to an external site should open in the same tab? I would have thought they should open in a separate tab (but I agree with removing the wording about this, which is clumsy).

**Comment by DeniseColbert** [comment]
@richardofsussex to make link open in same tab and remove text

**Comment by richardofsussex** [comment]
See comments in #520. The District link in the search results page now behaves as we want it to in test2. It's not possible to get to the entry details view to check the link there.

**Comment by DeniseColbert** [comment]
@Vino-S to take a look and then pass to Richard

**Comment by Vino-S** [comment]
ready for testing in test2

**Comment by richardofsussex** [comment]
I have checked test2, and can confirm that the wording about separate tabs has gone, and that the link opens in the same tab unless you take action to open it in a separate tab. My understanding is that this is the behaviour we want, in which case it can be pushed on to test3/beta.

**Comment by richardofsussex** [comment]
Beta appears to be OK now. Test3 still refusing to display District pages from the list under Records, so can't check this there.

**Comment by KristinaGadzhieva** [comment]
Agree. Opens in the same tab on Beta. Can we close this story?
