### ISSUE TITLE
Permanent URL and Citation button on the Entry Information page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#546]
- [x] To create a permalink in the table after the transcriber information and add a copy button.
- [x] To create a citation button for the Entry information page at the top of the page.

**Comment by DeniseColbert** [comment]
Review other sites, develop approach that mirrors them and implement.

**Comment by richardofsussex** [comment]
A brief glance at FreeCen and FreeReg shows that a row of buttons is used both for navigation from the Entry Information page and to carry out various operations/reports from it. 
FreeCen:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/f0faf698-a2f5-4822-97b3-d20746eeeae6)
FreeReg:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/7c466fdd-c25c-4e2a-8cac-02529fd52d97)
This is significantly different from the BMD2 Entry Information page:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/59008a1f-1eb7-44b6-8979-f10365e01c40)

**Comment by richardofsussex** [comment]
Suggestion:

- implement the existing navigation controls using the same button style as Cen and Reg
- add buttons to support record export in various formats + printable format
- add Generate Citation button (include option to generate just this record's URL, for use as a browser bookmark, etc.)

**Comment by KristinaGadzhieva** [comment]
for MVP:
- [x] to create a permalink in the table after the transcriber information and add a copy button.
- [ ] to create a citation button for the Entry information page at the top of the page

**Comment by KristinaGadzhieva** [comment]
just for notice #276, #279, #286

**Comment by richardofsussex** [comment]
Initial effort, with the URL being presented as a link:
<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--240fa5a507c5cbe081409df166bcf134be4186ea/image.png" alt="image.png" />

**Comment by richardofsussex** [comment]
Same approach, but with the addition of a Copy button (code shamelessly borrowed from FreeReg citation code!):
<img width="605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJ3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5683a41e52935b02a8b2600f109a7d8d02c3d79e/image.png" alt="image.png" />

**Comment by richardofsussex** [comment]
With help from @Vino-S I have made a first attempt at the citation generator for BMD2. Here's a screenshot:

<img width="1343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3382139f7dd7c37024dda4822f025656e4d6cee/image.png" alt="image.png" />

As it stands, you can select more than one citation format and see them both/all on screen. I think this might actually be useful, but if not we can go back to the one-at-a time strategy that the other projects use.

**Comment by richardofsussex** [comment]
OK - all supported citation formats now implemented and on test3:

<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3NqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95be712bebdde9d445e33b095c54790c3e111e33/image.png" alt="image.png" />

**Comment by DeniseColbert** [comment]
Bug fixed, ready to test on Test 3.

Is it possible to have the link on the left of the cell and the copy button on the right of the cell, to separate them and improve visual alignment?

![image](https://github.com/FreeUKGen/FreeBMD2/assets/19173257/3ab9d323-6ee2-4510-8460-b0171a12a7fd)

**Comment by AlOneill** [comment]
I hesitate to say this but "Copy URL" is set up as a link — it is misleading to make it look like a button. We can either make it actually a button or change its appearance so that it looks like a link.

I dare say some of the other "buttons" on the page are also links. It matters because, for someone using only a keyboard, a link is not activated in the same way as a button. This is not only a BMD issue — both REG and CEN have links that look like buttons.

**Comment by richardofsussex** [comment]
In what sense is it 'set up as' a link? The relevant source is:

`<div class = "text--center">`
`    <button class = "btn  btn--small ", onclick = copy("wikitree_ref_citation_container") style = "cursor: pointer">Copy</button>`
`    <button class = "btn  btn--small ", onclick = this.parentElement.parentElement.style.display='none' style = "cursor: pointer">Close</button>`
`  </div>`

It's a button, with an associated onclick event handler calling a javascript function.

**Comment by AlOneill** [comment]
The "Copy URL" button has an `href` which makes it a link; real buttons do not have an `href`.

Also, I could not get it to copy the URL. I tried the Enter key, the Space key and clicking. A keyboard-only user expects a button to be activated by Enter or Space and a link to be activated by Enter.

**Comment by AlOneill** [comment]
I remind you that `href="#"` is not a valid link address. It will not cause the focus to move and so the expected behaviour on pressing Tab will be not happen.

See https://a11y-101.com/design/button-vs-link for more details

**Comment by richardofsussex** [comment]
I'm sorry, @AlOneill - I was thinking of (and quoting the source code of) the "Copy" buttons for citations. (That's what I implemented most recently.) I'll have a look at changing "Copy URL" so that it uses a similar strategy to "Copy".

**Comment by richardofsussex** [comment]
The Copy URL button now acts like a button (!), and is separated more from the URL itself. Results are on test3: please check.

**Comment by AlOneill** [comment]
@richardofsussex 
Thank you. That is much better. Copy worked and the button was activated as expected.

Could the "Copied" message remain on-screen for longer, please? I don't know if any particular time is recommended by accessibility experts, just that I had become distracted and almost almost missed it.

I tried activating the "Generate Citation" button (which is also a link as it has an `href`, albeit an invalid one) using Space and was sent first to the bottom of the page: Tab then sent me to the first of the citation buttons.

I note that "Back to results" and "Suggest a correction …" also each have an `href` and that Space does not work as expected for a button.

After selecting a citation format, I _think_ I expect the focus to move such that the next press of Tab takes me to "Copy citation". It currently takes me to the next citation format. What do you think?

**Comment by richardofsussex** [comment]
I should be able to fix "Generate citation" so that it acts as a proper button.

However, once you can see the buttons, I would expect Tab to cycle through them all:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/f23bd7f2-d5db-4213-b41a-f28e75634f1b)

As you can see, they all appear in document order _before_ the code for individual citations, so I would expect Tab to operate in the way you describe. The only way I can see to achieve the result you are after would be to hide all the citation buttons (or all but the selected one) when one was pressed. I think this would be visually disturbing for users.

**Comment by AlOneill** [comment]
@richardofsussex 
Fair enough. It remains clear which format has been selected which is important. Thank goodness there are not 20 formats to tab through before getting to the Copy button!

**Comment by richardofsussex** [comment]
Two thoughts:

- the current set of citation formats is 'copied forward' from those on Cen and Reg, where they were a product of the Google Summer of Code. Personally I'm unconvinced that we need so many alternative citation formats for purely academic writings - user testing may help us whittle the number down a bit;
- we could potentially refactor the design so that it is a drop-down rather than a set of buttons (revisiting that discussion!) followed by a Copy button which is active only when a citation format has been selected.

Maybe leave the design as it is for now? (Following user testing, we should take whatever we agree about the citation design and feed it back to the other two project sites.)

**Comment by richardofsussex** [comment]
I've now changed Generate citation from a meaningless link to a button - see test3. Good catch - it behaves much better now while tabbing. (Also increased the timeout on the Copy button so it says "Copied" for long enough to notice. This is the same as the earlier change to Copy URL.)

**Comment by DeniseColbert** [comment]
Deployed to Beta, @richardofsussex can it be closed?

**Comment by richardofsussex** [comment]
Yes it can.
