### ISSUE TITLE
Recording of Registration Districts

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeBMD2#547]
In FreeCEN Registration Districts are included in piece names. The rule is that there should be no punctuation (e.g. full stops. St not St.)
In FreeBMD full stops are permitted in the Registration district. This is stopping entry matching when the entry is keyed for a second time, despite the entries being otherwise identical.
This will cause a matching issue if, as and when one search searches all of the data held by FreeUKGen.
We therefore need a consistent set of rules for the entry of data where the systems have fields containing data that records the same thing.
This will need to be considered during future development. With the development of FreeBMD2 maybe this is a good time to consider it.
Geoff

**Comment by DeniseColbert** [comment]
@richardofsussex might be interested in this...

**Comment by richardofsussex** [comment]
If we're recording the same thing, then absolutely we should be using the same rules/authority wherever we do so. However, I'm not sure about your statement that "In FreeBMD full stops are permitted in the Registration district". This is a chunk of my local copy of the districts table, where I have searched for "St". I don't see any full stops there:
![image](https://user-images.githubusercontent.com/2197102/223695524-3ade442e-32ca-44dc-8967-124eae2ea550.png)

**Comment by geoffj-FUG** [comment]
Richard

 

I am not sure which county, but I suspect I noticed it in Cornwall.

 

I was searching FreeBMD to find a place of birth whilst validating a FreeCEN piece. I found 2 entries for the person which had not been matched during double keying. One had a full stop after St. and the other was just St    I presumed that the full stop had prevented the matching. (I am not expert with FreeBMD, just a user).

 

That made me think about matching the rules if we are to eventually be able to have a one search finds all system.

 

Geoff

**Comment by richardofsussex** [comment]
Geoff,

I think this must be a data validation issue, rather than a problem with our underlying Reg. district data. When you do a search on FreeBMD(1) the list of possible districts appears as a drop-down. If you select Cornwall as the county you'll see that none of the districts have 'St.' in their name. It's a controlled field - but clearly not controlled strictly enough! Can you recall the exact entry where you spotted the variant district name?

**Comment by richardofsussex** [comment]
One action we should take is to compare the District tables used by BMD and CEN. It they are not already identical, we should work to harmonize them.

**Comment by geoffj-FUG** [comment]
Richard

 

I cannot recall the entry. I search for a lot of them. Next time I come across an instance I will let you know.

 

Geoff
