### ISSUE TITLE
267276054 Testing ()

### ISSUE THREAD

**Issue by FreeBMDIssues** [FreeUKGen/FreeBMD2#550]
Issue reported by **** at 2023-06-21 11:20:54 UTC
Time: 2023-06-21T11:15:00+00:00
Session ID: fdcfed6f6806452ccf4c5918019a8459
Problem Page URL: [/search_queries/new?locale=en](/search_queries/new?locale=en)
Previous Page URL: [https://test3.freebmd.org.uk/manage_resources/logout?locale=en](https://test3.freebmd.org.uk/manage_resources/logout?locale=en)
Reported Issue:
Testing    

![Screenshot](https://test3.freebmd.org.uk)

**Comment by DeniseColbert** [comment]
@Vino-S can this be closed?
