### ISSUE TITLE
"Menu" button broken on iPhone

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#557]
On both iPhone 13 and iPhone SE the teal "Menu" button does not open the main menu.

I cannot test on an Android phone.

**Comment by AlOneill** [comment]
Tried several times to open the main menu without success.

Does the teal button work on an Android phone?

**Comment by richardofsussex** [comment]
No, it's totally non-operative on my Android phone. (If you turn the phone to landscape orientation, the menu button is replaced by three bars on the right of the pink bar, and clicking on that _does_ link to the menu items.)

**Comment by AlOneill** [comment]
Does not happen on iPhone: stuck on portrait

**Comment by richardofsussex** [comment]
It's easily replicated on a desktop by making the window narrow enough. This screen grab suggests that the Menu button is simply a link to Google Analytics:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/8fab7c6b-3b84-4f6b-91fa-e326e021047d)

**Comment by AlOneill** [comment]
I tried the turn it off and back on again thing. The screen is rotating and the hamburger is working!

@richardofsussex if that is the case, surely we should not even see it?

**Comment by richardofsussex** [comment]
As is often the case with Rails code, it is impossible to deduce from the source exactly what is meant to happen. I can see the logic of the hamburger being replaced by a Menu button at the smallest width, but only if it actually links to/opens said menu.

**Comment by AlOneill** [comment]
Indeed!!

**Comment by richardofsussex** [comment]
This is the code which displays the menu (in three different ways, depending on screen width):
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/9abd2c85-3c5e-4660-8b33-65edd2fd913d)
You can see that the aria-label attribute value is what is being displayed at the smallest screen width as the button text.

**Comment by AlOneill** [comment]
Sorry — cannot see that. I see `aria-label="Main menu"` Perhaps I'm looking at the wrong thing?

**Comment by richardofsussex** [comment]
That's exactly my point: the code says 
`<nav class="main-nav float--right" role="navigation" aria-label="Main menu">
           <ul class="nav hide_nav capitalize">`
and you can see from the Inspector scope that this is all that controls that whole three-level-alternate-display behaviour.

**Comment by AlOneill** [comment]
Er, "Main menu" is not the same as "Menu". What am I missing here?

**Comment by richardofsussex** [comment]
True ... let me look at the code some more ...

**Comment by richardofsussex** [comment]
Comparing with FreeReg and FreeCEN, I see that those sites misbehave in a different way when you narrow the browser width to 'palm'. The menu headings shuffle up as you narrow the window, then suddenly 'jump' to the right (off the screen) when 'palm' width is reached. There is no intermediate 'hamburger' state. The Menu button is the same as for BMD, except that it works ... but it is almost hidden by a cookie acceptance dialogue which appears and won't go away:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/3a79c779-04a1-4a48-8510-e4e484aa67f3)

**Comment by richardofsussex** [comment]
The id `trigger-offcanvas-old` is an attribute of the containing `<div>` element, not of the `<button>` with class `site__header__menu-btn`. This means that the event is associated with this `<div>` element, not the button:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/deb8dc8f-f260-4dff-95a2-463401cb13e0)

In CEN and REG, there is no containing `<div>`, and the `<button>` has both id and class (though the id is `trigger-offcanvas`, i.e. not identical). In these projects, the event _is_ associated with the `<button>`. Could this be why it works for them, but not in BMD2?

**Comment by DeniseColbert** [comment]
@richardofsussex to look at this in light of systemwide #157

**Comment by richardofsussex** [comment]
@Vino-S finds that the javascript trigger is not working

**Comment by Vino-S** [comment]
@richardofsussex Ready for testing in test3

**Comment by richardofsussex** [comment]
This now works nicely both on my desktop (with an increasingly narrow window) and on my Android phone. In both cases, as the screen narrows the menu items on the bar first become a hamburger on the bar, then at the narrowest screen width they become a separate Menu button above the bar. In both cases, and on both devices, the hamburger/menu works as it should and offers the menu items as links. Nice work.

**Comment by DeniseColbert** [comment]
@AlOneill could you test this is fixed on iPhone please? Then we can close

**Comment by AlOneill** [comment]
@DeniseColbert 
I can confirm that the "MENU" button opens the menu. And a second tap closes the menu, although part of the button is not visible, being off the screen to the left so that I see "ENU". 

The cookie acceptance works as expected. Thank you.
