### ISSUE TITLE
'Search all' option in Record type field

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#558]
Make the default 'search all' option be automatically selected so that users don't need to select it manually

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by richardofsussex** [comment]
Yes, that option is now selected:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/9e990f7e-a8ce-44b0-8753-063aa492f9ec)
However, when you click on Select All, you end up with all three options ticked as well:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/377a1540-f44e-494b-ba36-b083e36f4aed)
so I think it would be more consistent if they were all ticked initially as well. What do others think?

**Comment by DeniseColbert** [comment]
@Vino-S to tweak this so that all boxes are selected when page is loaded

**Comment by Vino-S** [comment]
Ready for testing in test3

**Comment by KristinaGadzhieva** [comment]
@Vino-S ready for deployment
