### ISSUE TITLE
Volume & Page fields

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#559]
Make Volume and Page fields appear after the Districts field only when a single district is selected to emphasize that they are 'properties' of that District

**Comment by Vino-S** [comment]
@richardofsussex Ready for testing in test3

**Comment by richardofsussex** [comment]
I'm not sure we're clear on what we are trying to achieve here. This is test3:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/cbcd570b-7bc2-4f0d-9a3f-ad002c798f81)
I can see three things wrong from my point of view - as I say we may not be clear/agreed on what the brief is:

- Volume and Page still precede County and District: I thought the intention was that they should follow them ("to emphasize that they are 'properties' of the District")
- Volume and Page should not appear unless (exactly) one District is selected
- the values for District should reflect the selected County (this is a regression - they used to)

**Comment by KristinaGadzhieva** [comment]
@richardofsussex That's exactly what we discussed.

**Comment by Vino-S** [comment]
Thanks for testing @richardofsussex 
We had a spelling error in the code which blocked the execution of JS script. Fixed it.

**Comment by richardofsussex** [comment]
Good work @Vino-S - that is now behaving correctly in test3. The only deviation from the spec is that Volume and Page remain on the screen when you select a second District. However, on reflection I think that this provides the user with a more stable interface, even if it isn't strictly logical in terms of their potential queries. Having once appeared, I suggest that Volume and Page should stay visible unless the user de-selects all Districts.

**Comment by DeniseColbert** [comment]
To be deployed on Friday 26th Jan- Vino to close once deployed.

**Comment by Vino-S** [comment]
Deployed
