### ISSUE TITLE
Remove `<h1>` tags from project logos

### ISSUE THREAD

**Issue by AlOneill** [FreeUKGen/FreeBMD2#562]
It seems that the tide has turned and that the project logos should probably be simple links and not `<h1>` headings. In other words we are returning to only one `<h1>` per page — the unique (to the website) title of the page.

"Wrapping the logo in an h1, resulting in the h1 being the site name, is not right. Because then, every single page on a site starts with the same h1 text. This is confusing for screen reader users and not informative for search engines."
Source: a11yproject.com/posts/how-to-accessible-heading-structure/ (Jan 3, 2022)

It is not yet clear to me whether the h1 elements should be replaced with something else (such as h2 elements) or whether it is better to leave the logos as simply links: there does not seem to be much agreement.

**Comment by DeniseColbert** [comment]
Done in FreeREG (FreeCEN logo didn't have `<h1>` tag). Just FreeBMD2 to do now.

**Comment by Vino-S** [comment]
Deployed
