### ISSUE TITLE
'Back' links from District detail page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#563]
Now that we can link to the District pages from search results and individual record pages, the Back links don't work in a helpful way. They are designed to take you 'back' to the alphabetical list which is used to select District pages - but that's not where you will have come from if you clicked on the District in a search results context.

I suspect (hope!) that we will improve or completely replace the current method of selecting Districts, but in the meantime we need to ensure that the Back links on the District page behave sensibly, if you are coming to that page from your search results.

**Comment by KristinaGadzhieva** [comment]
Works on beta. Links to districts don't open on test 3.

**Comment by KristinaGadzhieva** [comment]
Implemented. Can be closed.
