### ISSUE TITLE
Consistency with FreeCen and FreeReg results pages

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#565]
The BMD2 results page:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/aa19ba4b-0e6b-4a20-a2e2-c879978eb137)

**Comment by richardofsussex** [comment]
has a different design to the FreeCen and FreeReg results pages, e.g.:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/01f10420-7538-4b22-b684-b7f3e341bebf)

**Comment by richardofsussex** [comment]
This is partly explained by the fact that the BMD2 results are 'paged' (and this may happen to Cen and Reg in future). However, some functions (like Printable Format) are accessed in different ways between the two sites. Are we happy about this inconsistency, i.e. are the reasons for the differences sufficiently convincing?

**Comment by KristinaGadzhieva** [comment]
Amir is working on it

**Comment by KristinaGadzhieva** [comment]
Close, not needed for phase 3.
