### ISSUE TITLE
Improve printing of Results Page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#568]
The "Printable format" item on the Tools menu should be replaced by a simple Print command/button. This should generate the printable version of the current page, not as a page in its own right but as the content to be sent to the standard print dialogue. In other words, it should behave like every other print command on the web.

**Comment by richardofsussex** [comment]
I have worked out how to print the page directly, using a print CSS stylesheet to control what is output. This is a simpler approach conceptually than the current strategy of generating a whole 'print-friendly' page (and then leaving the user stuck on it). There is a simple 'Print' button:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/41881039-bf17-4724-be61-8c01d41f0712)

which brings up the standard print dialogue directly:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/a6b885bc-8caa-42b2-904c-9f0b4b683032)

The main challenge is in writing CSS which cleanly filters out the unwanted content, given the baroque nature of the HTML which Rails generates. (As you can see, the job is half done. I have successfully filtered out the first column of the results table, but some unwanted content remains.)

**Comment by KristinaGadzhieva** [comment]
Could we consider creating an icon for Print option instead of a button? I think it's more visual than a button.

**Comment by richardofsussex** [comment]
Two arguments against having a print icon are aesthetics (I think the row of buttons looks neat, and corresponds to what the other two projects have) and potential accessibility issues.

**Comment by richardofsussex** [comment]
As regards the CSS issue, it occurs to me that if we invent classes 'no_print' and 'print_only', and apply them to the generated HTML, it makes it very simple to crop out the page components which we don't want in the printed output (and also to declare new content which is intended _only_ for the printed version of the page). This whole approach is something of a departure from what we have done in the past, and I would welcome @Vino-S 's views on it. My own view is that it's a simplification, and that it is more in line with standard web publication practice.

**Comment by KristinaGadzhieva** [comment]
@richardofsussex I thought we agreed on the the results page wireframe where download and print icons are presented. Since this suggestion came from Amir, I think everything is fine from UX UI point. Personally, I also support icons for these two options as they are more visual. A long row of buttons doesn't seem like the most modern way to present functionality and doesn't increase appeal or simplicity. If this issue is controversial, we can discuss it again together with Amir at the next meeting.

**Comment by AlOneill** [comment]
@richardofsussex 
Why not text _and_ icon? I'm sure a button with text and an icon could be made to look neat and as it would be  _more_ accessible than either text or icon by itself, I do not see a problem.

@KristinaGadzhieva @Amir
'Modern' or 'appealing' is not always Accessible, sadly. I frequently struggle to understand an icon by itself. A _visible_ text alternative is always good (i.e. _not_ a `title` attribute which would decrease Accessibility).

**Comment by KristinaGadzhieva** [comment]
from the wireframe:
<img width="426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ed2631dc4f2a00e9a319216dc2922bb834e0c09/image.png" alt="image.png" />

**Comment by AlOneill** [comment]
@KristinaGadzhieva @Silozo17 
Sound. That looks good and Accessible. I had not seen the wireframe. Should've known you would have it covered! Apologies: I'll go back to sleep …

**Comment by richardofsussex** [comment]
Interesting. @AlOneill can clearly see your image of the wireframe, but I get "Non-Image content-type returned" when I click on the link.

**Comment by richardofsussex** [comment]
Just to say that I have managed to clear all the extraneous material from the print page:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/a758c4eb-a580-4def-bd43-8f5b05e76fab)

**Comment by richardofsussex** [comment]
Ready for testing on test3.

**Comment by KristinaGadzhieva** [comment]
@richardofsussex Thank you! Works on test3. Ready for deployment.
