### ISSUE TITLE
Improve behaviour of Filter control on Results Page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#569]
The Filter control on the Results page should be sensitive to the Event Type(s) specified in the search. If only one Event Type was searched for, the Filter is meaningless and should not be displayed at all. If two Event Types were specified, only those two types should be displayed as options in the Filter control.

**Comment by KristinaGadzhieva** [comment]
to check on test3

**Comment by KristinaGadzhieva** [comment]
Doesn't work on test 3

**Comment by DeniseColbert** [comment]
Ready to test on Test3

**Comment by richardofsussex** [comment]
I've tested it and I'm happy that it works as intended.

**Comment by DeniseColbert** [comment]
Deployed to Beta, closing
