### ISSUE TITLE
Search Criteria button on the Results page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#570]
- [x] Change the button name to ' View Search Criteria'
- [x] Add information about the query and make it available only to transcribers
- [x] Leave information about search criteria for users only and hide information about the query for users.

**Comment by DeniseColbert** [comment]
View search criteria name-change has been implemented on test 3

**Comment by richardofsussex** [comment]
Tested and OK: I think this issue can be closed.

**Comment by DeniseColbert** [comment]
Deployed to Beta, closing
