### ISSUE TITLE
Download icon on the Results page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#571]
To create an icon for download search results with a 'save as' option in CSV and GEDCOM formats.

**Comment by richardofsussex** [comment]
OK, I have had a go at both #571 and #572, and the (relevant bit of the) search results page now looks like this:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/d72430df-b1f6-4544-9003-345d8c37a429)

**Comment by richardofsussex** [comment]
... which I think is neater.

**Comment by AlOneill** [comment]
@richardofsussex 
Nice one — looking good. How does it look in a narrower window?

**Comment by richardofsussex** [comment]
The buttons realign themselves as the window gets narrower. That all seems to be well-behaved:
![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/f86fcca2-9915-4e70-acb8-568908408b0a)

**Comment by AlOneill** [comment]
@richardofsussex 
Thank you. That too looks good!

**Comment by KristinaGadzhieva** [comment]
Thank you Richard. How about making just one Download icon with the option to save in different formats?
Another point that I would like to clarify again is the icons. Do we need buttons for them? Perhaps we could make icons without buttons? 
Please have a look at the attached image.<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkIwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a694524dccbaef9289af21df8ae0b1bc6098d4d6/Screenshot_1.jpg" alt="Screenshot_1.jpg" />

**Comment by richardofsussex** [comment]
"One download icon with the option to save in different formats" implies that the icon is on a drop-down selection control like the (now defunct) Tools menu. Personally I think this would be visually messy, and operationally more complex for the user to use. It also tells the user nothing about what download options are available until/unless they click on it.

@AlOneill has already explained that icons without associated buttons (and text) are _not_ accessible.

**Comment by richardofsussex** [comment]
This is now available for testing on test3. Thank you @Vino-S for this.

**Comment by KristinaGadzhieva** [comment]
To investigate accessible options for Download feature

**Comment by KristinaGadzhieva** [comment]
We discussed that we might consider creating a drop-down menu for the download feature.

**Comment by KristinaGadzhieva** [comment]
Decision: to leave download buttons as they are now.
