### ISSUE TITLE
Filter by and Sort by fields on the Result page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#572]
- [x] Change the field text to 'Select' for Filter by and Sort by fields
- [x] Change the button name from 'Update Results' to 'Apply'

**Comment by KristinaGadzhieva** [comment]
To include in users testing and check if users need the filter option.

**Comment by richardofsussex** [comment]
Ready for testing on test3.

**Comment by KristinaGadzhieva** [comment]
<img width="1029" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60d1f77b47894d1b4605846ed77dcb654c97a939/Screenshot_6.jpg" alt="Screenshot_6.jpg" />

**Comment by DeniseColbert** [comment]
Deployed to Beta, closing
