### ISSUE TITLE
Number of results on the Results page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#575]
To display a number of results.

**Comment by KristinaGadzhieva** [comment]
To change the font size and make it bold.

**Comment by richardofsussex** [comment]
Committed code in branch `fb_581_rbl` (sorry @Vino-S - it was the closest I could manage!) with suggested more friendly wording:

![image](https://github.com/user-attachments/assets/7f276356-446f-4d37-a366-c18caf6a3ca1)

**Comment by richardofsussex** [comment]
Code (re-)added to `fb_575_rbl`. Now on test3.

**Comment by DeniseColbert** [comment]
Done, closing
