### ISSUE TITLE
Spouse Surname, Mother's Surname, Age at Death

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#576]
- [x] To check data on Spouse Surname, Mother's Surname, Age at Death in the table on the Entry information page

**Comment by Vino-S** [comment]
ready for testing in test3

**Comment by DeniseColbert** [comment]
This is great!

Bug: Spouse surname is repeated in Marriages

Just a Q, should we place NA in blank fields (where we have no data)?

**Comment by richardofsussex** [comment]
I don't see the repetition of spouse surname in test3 now. If it's still there, please quote a specific example.

Personally, I think loads of "N/A"s would clutter the display, especially for 19th century material where there will be few, if any, actual entries.

**Comment by DeniseColbert** [comment]
Deployed to Beta, closing
