### ISSUE TITLE
Scans on the Entry information page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#578]
To add a Scans icon with a preview option

**Comment by richardofsussex** [comment]
What is the requirement here? We already have a scans icon, and clicking on it (in beta) causes the scan section to appear:
![image](https://github.com/user-attachments/assets/2db0e40b-ee1c-4258-9f92-d717bfcb1779)
Clicking on the link takes the user to the BMD1 page which displays the scan.
Is the problem the placement of the scans section? Or the fact that the image doesn't appear within the page?

**Comment by AlOneill** [comment]
Do not know what main issue is but please can we have a space between "Office" and "(G.R.O.)": "General Register Office (G.R.O.)"

Also consider using full stops to prevent G.R.O. being announced (by screen reader) as 'grow' which could confuse a family history newbie.

**Comment by AlOneill** [comment]
My guess is that the appearance of the scans section is not obvious to a screen reader user: it will need to be treated as an 'alert' section.

**Comment by AlOneill** [comment]
Ah, the scan section does not appear on beta when the icon is selected (am getting "Loading" and a red problem message. Where should we be looking?

**Comment by richardofsussex** [comment]
Can you please quote the URL of the record you were accessing (or describe the search you carried out to find it)? I got the screenshot above from beta, so it clearly works for some records, and not for others.

**Comment by AlOneill** [comment]
I was seaching for Davis, births, 1905 to 1983 in Surrey North Western. URL is https://www.freebmd.org.uk/entry-information/B0BBD58QsdFVnKDwJNuTXg/hash which looks sus as it ends with 'hash' and the focus _appears_ to move but doesn't.

This _looks like_ a button but _it is_ a link  and the destination is invalid.

We also get an orphaned dagger at the foot of the table:

<img width="1234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekUyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--becad64b1657a91329ff6628449fd132d9051c7a/Record_Details___FreeBMD-06aug24.png" alt="Record_Details___FreeBMD-06aug24.png" />

**Comment by richardofsussex** [comment]
The scan preview needs to appear immediately below the Entry information table - it is currently off the bottom of the screen and so not visible.

**Comment by Vino-S** [comment]
Ready for testing in beta

**Comment by DeniseColbert** [comment]
Looks good! Closing
