### ISSUE TITLE
Buttons on the Entry information page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#579]
- [x] To change the button name to 'Give us feedback'
- [x] To change 'Previous in Page' , 'Next in Page' buttons according to the wireframe

**Comment by KristinaGadzhieva** [comment]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5723ae5b94db5741c61aec92f954108634d34108/Entry%20information%20page%20MVP.jpg" alt="Entry information page MVP.jpg" />
Wireframe

**Comment by richardofsussex** [comment]
Hi, for all your linked images I get "Non-Image content-type returned" when I try to view them.

**Comment by KristinaGadzhieva** [comment]
Change 'Previous in Page' , 'Next in Page' buttons according to the wireframe still needs to be done.

**Comment by richardofsussex** [comment]
So is the requirement to change 'Previous in Page' to 'Previous', and 'Next in Page' to 'Next'? (If so, maybe that wasn't clear.)

**Comment by richardofsussex** [comment]
Change made: see branch `fb_579_rbl`.

**Comment by richardofsussex** [comment]
@Vino-S please merge this into beta so we can sign this one off.

**Comment by richardofsussex** [comment]
OK on test3 - can we sign this off?

**Comment by Vino-S** [comment]
REady for testing in beta 
<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzFJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0de21d59ca3d919464f8da139678db7260344b1/image.png" alt="image.png" />

**Comment by DeniseColbert** [comment]
Done, thanks: closing
