### ISSUE TITLE
Print button with icon on the Entry information page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#580]
- [ ] To create a Print button

**Comment by KristinaGadzhieva** [comment]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0dac5b4610f4529fef5b97dbe54aae0514ec854d/Entry%20information%20page%20MVP.jpg" alt="Entry information page MVP.jpg" />
Wireframe

**Comment by DeniseColbert** [comment]
Vino to shift to the left to avoid links going beyond the horizontal rule

**Comment by DeniseColbert** [comment]
Looks good! Closing
