### ISSUE TITLE
Register number on the Results page and Entry information page

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#581]
To put a register number on the Results page and Entry information page.

**Comment by richardofsussex** [comment]
First we need to discover where the register number is actually held in the data. There is no obvious place for it in the database structure used by the testing databases to which we have access, and searches on the beta database do not find the records which include register numbers, e.g.:

<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3NoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65100638e9322951c5ffd04f78fdff0df53d0b1c/image.png" alt="image.png" />

We are trying to get a copy of the live database schema so we can establish what needs to be done.

**Comment by richardofsussex** [comment]
Implemented. Should work whether or not the RegistrationNumber field has been declared in the Submission table schema:
<img width="599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7e3f47fc66d948b145568aa7f1a1c2851379ed5/image.png" alt="image.png" />

**Comment by richardofsussex** [comment]
See branch `fb_581_rbl`

**Comment by richardofsussex** [comment]
Now also fixed (thanks to @Vino-S) in the results listing, although she reports that it slows performance down. See the beta site.

**Comment by KristinaGadzhieva** [comment]
I can't see it on Beta for Josephine Smith's records, for example.

**Comment by KristinaGadzhieva** [comment]
to complete story #586 first

**Comment by Vino-S** [comment]
<img width="922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9be86c1ef03153480e321febacdcff4ee6e4d09c/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
Can't see changes in Josephine Smith's record on test 3 and beta. <img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEN4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5f39cb915ca9634c9c1a8c6d2c3916c3d48b832/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
To transfer register number on the Results page

**Comment by KristinaGadzhieva** [comment]
Register number on the Entry inf page is ready for testing on Beta.

**Comment by Vino-S** [comment]
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2332120686520d65c440858909dc8797e707108/image.png" alt="image.png" />

**Comment by Vino-S** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--810e78d0e498e123076186823fbf6aea2ce37554/image.png" alt="image.png" />

**Comment by richardofsussex** [comment]
Need to change District code to Register Number in the results listing - wrong data is currently displayed.

**Comment by KristinaGadzhieva** [comment]
Register number is now only on the Entry information page. We were going to make it on the Result page as well.

**Comment by Vino-S** [comment]
Updated the results page in Beta:
<img width="1751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1FXQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e801be625a9157a014d09e24cf0a46b6dcb7229/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
@Vino-S please add labels 'Register No.' , 'Entry No.'  in the 'Registration District Reference'.

**Comment by Vino-S** [comment]
Beta updated:
<img width="1750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjh0Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c7aaf5821058d00ff308e973cff60503409fcb4/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
Implemented on Beta. Closing
