### ISSUE TITLE
Suggest a correction button

### ISSUE THREAD

**Issue by KristinaGadzhieva** [FreeUKGen/FreeBMD2#584]
To change the button name from ‘Report an error’ to ‘Suggest a correction’ on the Entry information page.

**Comment by richardofsussex** [comment]
Done (in the `cite` branch). Edit is in the file views\best_guess\show.html.erb.

Now on test3

**Comment by DeniseColbert** [comment]
Looks great, thanks!

**Comment by KristinaGadzhieva** [comment]
<img width="723" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGI4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eeee7780ac82bde2a5c66963934c643f0257bfd3/image.png" alt="image.png" />

The same name 'Report an Error' on test 3 and Beta.

**Comment by richardofsussex** [comment]
@Vino-S can you sort this out please? There must have been a reversion when merging in development branches. It's a pretty trivial change.

**Comment by Vino-S** [comment]
DEployed.
