### ISSUE TITLE
Change Volume to District Number for post-1992 records

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#586]
In records from 1993 onwards, GRO stopped using Volume and Page, replacing them by Register Number (and SubNumber) and Entry Number, and started recording (GRO) District Number (and SubNumber). With splendid pragmatism, we therefore started recording District Number in the Volume field. This field consists of a three-digit District Number, optionally followed by one or more characters representing a SubNumber.

This means, inter alia, that we should change the Volume heading in the Entry Information page to District Number/SubNumber, and display that field so it is clear which is the Number and which the SubNumber.

**Comment by KristinaGadzhieva** [comment]
to investigate more

**Comment by KristinaGadzhieva** [comment]
to investigate more

**Comment by richardofsussex** [comment]
On further investigation, I would say that we should _not_ display the Volume field at all when the date is 1993 or later. The GRO District Number is a property of the District (and is distinct from our own District Number). We don't display it for older material - so I see no need to display it for post-1992 material either.

What we _do_ need is the Registration Number. This isn't in BestGuess: it is stored in the Submissions table. It should appear where Volume would normally appear in the Entry Information view, since it plays the role which Volume played.

The other change we should make is that for post-1992 material, the Page is actually called the Entry Number:
![image](https://github.com/user-attachments/assets/28b84a59-799a-4b43-a739-bb1517fdee71)
so we should call it that too in Entry Information.

**Comment by richardofsussex** [comment]
Also, I suspect that the 'previous [in page]' and 'next [in page]' navigation will be meaningless for Entry Numbers, and so should be suppressed.

**Comment by richardofsussex** [comment]
I also found that the Date wasn't being output for recent years, and the DOR entry code needed to allow for entries of the form 'MMYY' as well as 'MM.YY' (not least because that's what is actually in the source data!).

**Comment by richardofsussex** [comment]
The Search results page in beta now displays different information from the Entry information page as regards 'volume' and 'page'. For example:

![image](https://github.com/user-attachments/assets/ef084a73-3da0-436b-bab5-6ff1bee8161f)

and:

![image](https://github.com/user-attachments/assets/6bcbf4c7-9045-4b83-8d0c-9dec1ff4841e)

This implies that we _must_ accept the overhead of looking up Register number and Entry number, since we will otherwise be displaying incorrect information.

**Comment by richardofsussex** [comment]
In fact, further fixing is required. The FreeBMD site has this as the detail for this record:

![image](https://github.com/user-attachments/assets/4d04688b-87fa-4f9d-b702-f71bc6f57da8)

So the BMD2 beta Entry number is actually the Date of Registration (DoR).

**Comment by richardofsussex** [comment]
Now fixed:
![image](https://github.com/user-attachments/assets/605bffa9-b05b-4ee4-88b9-1e8ca62b4613)

**Comment by DeniseColbert** [comment]
Where is this? Does it need testing?

**Comment by KristinaGadzhieva** [comment]
To change Event type to Record type

**Comment by KristinaGadzhieva** [comment]
Implemented in # 582
