### ISSUE TITLE
Information architecture

### ISSUE THREAD

**Issue by avielbassalian-freeukgen** [FreeUKGen/FreeBMD2#59]
Decide how content will be changed (added/edited/removed) and how it will be organised (into pages, sections). Will probably need a card sorting session.
Note: do not yet need to organise the order/structure of each page, just what content they should contain.

requires #53
requires #60

**Comment by PatReynolds** [comment]
@Daniel-silve1ra @KatyMawhood ids this still a live issue?

**Comment by KatyMawhood** [comment]
@PatReynolds This seems to describe the FreeBMD2 website as a whole, which is beyond the current [search experience](#227) project. The AI research specific to search experience precedes me and Daniel. 

Could this be linked a single "website" epic?

**Comment by PatReynolds** [comment]
I think this can be closed

**Comment by richpomfret** [comment]
Closing.
