### ISSUE TITLE
Grid and grid__item in Entry information page

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#594]
There are layout issues on the Details page. All children of .grid need a .grid__item and that all .grid__items need a parent .grid. This is not currently the case.

**Comment by richardofsussex** [comment]
See branch `fb_594_rbl` which attempts to remedy the problem (and remove duplicate rows).

**Comment by KristinaGadzhieva** [comment]
To check on Beta
