### ISSUE TITLE
Create a sitemap for FreeBMD1

### ISSUE THREAD

**Issue by avielbassalian-freeukgen** [FreeUKGen/FreeBMD2#60]
Document page structure of FreeBMD1. What pages are there? How to they relate to each other?
Example: https://drive.google.com/open?id=1bBV1SbHz0vXKYCAoZRITh5mfHUaeU3pO
Example: https://drive.google.com/open?id=17H32y8SQ2mfzBA7bqE4ZneWujUBMRBMe

**Comment by avielbassalian-freeukgen** [comment]
Sitemap: https://drive.google.com/open?id=1dZdqSQijx_XazPkGJi7bGVK_vy4m1ieCBVd6nkqWvtM

**Comment by smrr723** [comment]
This looks fine to me if it's just a sitemap recording the current pages on BMD1.

I will also create an actual `/sitemap.txt` or `/sitemap.xml` file which bots can crawl, for SEO purposes, and submit it to Google (for both BMD1 & 2).
