### ISSUE TITLE
Records Page - Date to read Registration Date 

### ISSUE THREAD

**Issue by nurifreembd** [FreeUKGen/FreeBMD2#603]
'Date' to read 'Registration Date' on Records page. 

example here:
(https://beta.freebmd.org.uk/6745f16f9c5d61485c081bdc/entry-information/194240963/janet-a-louth-birth-anglesey-to-mar1974-anglesey-w-v8a-p25?locale=en&search_entry=194251249)

**Comment by KristinaGadzhieva** [comment]
Already mentioned in story #595.  Can we close this one?

**Comment by nurifreembd** [comment]
Duplicate issue and will be addressed in 595. I do not have permission to close.

**Comment by richardofsussex** [comment]
Closed
