### ISSUE TITLE
Results page: Registration Date values not inline with search from to quarters 

### ISSUE THREAD

**Issue by nurifreembd** [FreeUKGen/FreeBMD2#607]
Search to and from quarter dates not inline with the values shown on Registration date on results page, for example search March 1947 to Sept 1947 shows other quarters like Jan to March 1947.

**Comment by KristinaGadzhieva** [comment]
I have checked. Search March 1947 to Sept 1947 includes three quarterts (January, February, March; April, May, June; July, August, September), and the results also include information from three quarters.  So, the results and search are correct. 
Mar, Jun, Sep, Dec means quarters, not months. <img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFCQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0f8958735f41eb045c393c876e382722d7cf414/image.png" alt="image.png" />

**Comment by KristinaGadzhieva** [comment]
@richardofsussex do you agree with my comment? I think the story can be closed.

**Comment by nurifreembd** [comment]
retested it works when I ask for dates between March and March, it picks up
the first quarter.

thank you


unless i missed something I want to see records between March 19

**Comment by richardofsussex** [comment]
Yes I think this story can be closed. The system is working as intended.
