### ISSUE TITLE
Use Ideas doc to to inform layout design

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#62]
As per discussion in meeting after looking at BMD2 mock-up site e.g. where we put the social media buttons, getting rid of Google + and Github, how we recruit volunteers, better bridge project with our other projects etc.

**Comment by DeniseColbert** [comment]
At some point we need to decide which ideas we will use in the testing process. This will depend upon the priorities for development and the timeframe. Please advise @richpomfret

**Comment by PatReynolds** [comment]
Ideas doc and designs (with feedback) now being used iteratively, and will continue to be, until design is finalised.
