### ISSUE TITLE
Feedback Interviews

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#63]
Qualitative research feedback - interviews with long-term users of the site.

**Comment by avielbassalian-freeukgen** [comment]
Folder with interview write ups: https://drive.google.com/drive/folders/1-WYZccE-BCgB5q4ib_fn4x1DoaRe8VhN?usp=sharing

**Comment by DeniseColbert** [comment]
@avielbassalian-freeukgen to do round 2 of these and look for some deeper level info.

**Comment by PatReynolds** [comment]
@avielbassalian-freeukgen  to interview two inexperienced users recruited by @PatReynolds 29/4/2019

**Comment by richpomfret** [comment]
@avielbassalian-freeukgen has spoken to Anne, Shirlea and hopes to interview Lori soon.

**Comment by richpomfret** [comment]
Also discussed interviewing Graham H too. @richpomfret to introduce.

**Comment by richpomfret** [comment]
Have emailed Graham, so will put this 'on ice' until Aviel returns and it can move forward.
