### ISSUE TITLE
Work on Personas

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#64]

**Comment by PatReynolds** [comment]
Create personas (document). 4 currently - best practice is 3-5.

**Comment by PatReynolds** [comment]
Looking good!  I have made suggestions for jobs.

I can 'get' all the personas quite easily, except Stephania.  What is her motivation for use of FreeBMD?  I've given her a career that may have made her aware of FreeBMD.  
Maybe she is a village or buildings historian, and trying to find out who the 'Wilsons' were who she has on an old photograph? Or who the 'Jones' are who owned Jones' Fish and Chips?

**Comment by richpomfret** [comment]
@avielbassalian-freeukgen to review and look at Pat's changes.

**Comment by richpomfret** [comment]
To have a review - @PatReynolds and @avielbassalian-freeukgen

**Comment by richpomfret** [comment]
To discuss next steps - including updating user journeys to help guide UX designs.
