### ISSUE TITLE
Update UI elements and create a UI Guide.

### ISSUE THREAD

**Issue by neslihanu** [FreeUKGen/FreeBMD2#68]
Decide on UI elements and create a doc for UI kit. That will help us to create quicker mockups and take control of our UI design process.

**Comment by richpomfret** [comment]
Agreed (for now) the elements and UI guide. This will now turn into an update story as we move forward.

**Comment by Daniel-silve1ra** [comment]
@KatyMawhood essentially this is for the design system work once we get to it.

**Comment by KatyMawhood** [comment]
@Daniel-silve1ra Agreed. We should also keep the [Design for Access](https://drive.google.com/drive/folders/0BwVHfubVQz16eGV5enJZM2dEZkE) folder available for our design system.

@richpomfret Is it ok for us to rename stories to clarify our work?

**Comment by PatReynolds** [comment]
@Daniel-silve1ra and @KatyMawhood we think this has been done in Figma - shall I close it?  Thanks, Pat

**Comment by richpomfret** [comment]
@Daniel-silve1ra is there any final work required here? If not, we will close.
