### ISSUE TITLE
Link to cookie consent/policy

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#71]
Place in footer
Required by #69
Required by #66

**Comment by richpomfret** [comment]
Link is there in the current wireframe. Separate story for actual cookie policy page creation.

**Comment by richpomfret** [comment]
I think we could and should move this over into the Backlog.

**Comment by PatReynolds** [comment]
Done - consents for Europe, California and Ad blockers n ow all in place.

**Comment by PatReynolds** [comment]
Need to add script for FreeBMD2

@PatReynolds to check if new script is needed, or whether it can use the FreeBMD script.

**Comment by PatReynolds** [comment]
Now in footer.

**Comment by Vino-S** [comment]
Deployed to test3. So Closing it
