### ISSUE TITLE
Create wireframe for Vino to build

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#73]
Full search version

needed by #61

**Comment by PatReynolds** [comment]
@avielbassalian-freeukgen  to send Vino link to Figma

**Comment by richpomfret** [comment]
Shall nudge Allan/Barrie for their input.

**Comment by richpomfret** [comment]
Barrie has provided feedback over on the FreeBMD2 channel on Slack.

**Comment by richpomfret** [comment]
Following those discussions, I would like us to lockdown a current wireframe and proceed with it for this iteration. We will not be using any dynamic updating of the form initially (Barrie doesn't seem to be a big fan in terms of some users finding such things confusing).

**Comment by richpomfret** [comment]
@avielbassalian-freeukgen any final changes/updates before passing over to @Vino-S?

**Comment by avielbassalian-freeukgen** [comment]
@richpomfret @Vino-S 
No, I think we should go ahead with option 4 (I believe this was the option we decided on). I've also updated according to some of @PatReynolds feedback.
https://drive.google.com/open?id=1omxtCfNVypHN9wL0QXgZb2JjChOyWKjS
