### ISSUE TITLE
Create Refinery Database for FreeBMD2

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#75]

**Comment by Captainkirkdawson** [comment]
Have asked @lemon-ukgen to create the initial databases

**Comment by lemon-ukgen** [comment]
Done previously.

**Comment by Captainkirkdawson** [comment]
Thand @lemon-ukgen   There remains work to be done in setting the database  up so it is usable

**Comment by Captainkirkdawson** [comment]
The RefineryCMS for test2 is now available.
Login in possible although MOST Actions are inactive
However access is there to refinery pages and editing can commence whenever it is required

**Comment by richpomfret** [comment]
Looks good - closing.
