### ISSUE TITLE
Hyperlink from District name

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#78]
Currently, the link to details of district goes from the search results page (but not the detailed search results page) to the district information page (e.g. https://www.freebmd.org.uk/cgi/districts.pl?r=462222:6287&d=bmd_1557134722) and there is a link from the District Information page to the ukbmd page.

Is there potential here to use the Pelagios data?

**Comment by richpomfret** [comment]
@PatReynolds to review in terms of 'place' features on other projects.

**Comment by PatReynolds** [comment]
There is indeed a potential to use the Pelagios data.  However, that is not for MVP, which will need to link through to either the FreeBMD1 page, or (a nicer to have) a page that presents the data as per the FreeBMD1 page.

For decision: simple link, or presentation of data (at this stage)?

**Comment by PatReynolds** [comment]
Currently clicking on district on search results takes you to a generated interim page: e.g.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/de74b08c-d69e-4d18-b4fb-0de235d33d6e), which has the link "here" to UKBMD static page (https://www.ukbmd.org.uk/reg/districts/kettering.html in this case).  

I can't see what value the interim page adds. Happy to be enlightened.

**Comment by PatReynolds** [comment]
Currently clicking on district on search results takes you to a generated interim page: e.g.
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/de74b08c-d69e-4d18-b4fb-0de235d33d6e), which has the link "here" to UKBMD static page (https://www.ukbmd.org.uk/reg/districts/kettering.html in this case).  

I can't see what value the interim page adds. Happy to be enlightened.

**Comment by richpomfret** [comment]
@PatReynolds in which case, what are the next steps for this?

**Comment by PatReynolds** [comment]
MVP: I suggest simply a direct link to UKBMD, no interim page (will need a warning on leaving FreeBMD, though, as with FreeREG>Genuki.  Proposal needs feedback from currrent FreeBMD experts.

**Comment by PatReynolds** [comment]
Asked Allan about expert group 7/10

**Comment by PatReynolds** [comment]
@Barrie is there a reason why the district link needs to go via an interim page, rather than direct to ukbmd?

**Comment by PatReynolds** [comment]
Asked documentation volunteers 16/2/2020

**Comment by PatReynolds** [comment]
Page can include useful information - e.g. 
https://www.freebmd.org.uk/cgi/districts.pl?r=229960860:0111&d=bmd_1581352778

Therefore need to keep the interim page, or include this information on detailed results page.

**Comment by PatReynolds** [comment]
Decision: put the information onto the page with other details relevant to the record.

**Comment by PatReynolds** [comment]
With information on the page, we can also link through to GENUKI.

**Comment by PatReynolds** [comment]
@KatyMawhood @Daniel-silve1ra  content for the Detailed Results page for you to take into consideration

**Comment by KatyMawhood** [comment]
@PatReynolds I'm not 100% sure that I understand. Is this a link that is available to the user on the detailed results (e.g. [Forehoe](#))? Or if not, would this be considered a "help" functionality?

**Comment by PatReynolds** [comment]
Link now there and working

**Comment by richpomfret** [comment]
Working. Closing.
