### ISSUE TITLE
Finialise colours

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#8]

**Comment by PatReynolds** [comment]
based on final colours - to be tested on cloud9

**Comment by PatReynolds** [comment]
Pat to contact Allan re colours.

**Comment by richpomfret** [comment]
@AlOneill any plans to chang the colours at all for a revised FreeBMD? We are planning ahead for what will be used on FreeBMD2.

**Comment by AlOneill** [comment]
The SCSS/CSS/images are being edited together for all 3 projects. Through the magic of Rails, and using its own project-colour, each will get its own version of the styling. FreeBMD will have the revised magenta as its project-colour, plus access to all the accessible colour combos that CEN and REG will have.
