### ISSUE TITLE
Decide on mobile layout 

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#81]
Are we going with the design in the drive?

Decisions needed/made (see also #111 for decisions made that I have recorded here:
- [ ] 1 logo and advert at top (order to be decided)
- [ ] 2 logo/bar format to follow desktop design
- [x] 3 cookie consent at top, below logo (or ???)
- [ ] 4 background green until cookie consent is accepted
- [x] 5 menu indicated by a "menu" button
- [x] 6 menu button displays menu (i.e. the tab headings appropriate to location)
- [ ] 7 red banner text to be as desktop
- [ ] 8 reduction in non text space in red banner to be reduced (see #111)
- [ ] 9 space between other project logos and dark grey footer to be minimised
- [x] 10 dark grey footer layout as chosen for search page  (see #111)

**Comment by Captainkirkdawson** [comment]
We also need to define what is to be displayed from clicking the menu. Currently the apps display a vertical list of the actions contained in the Nav Bar

**Comment by PatReynolds** [comment]
@Denise is anything else needing a decision on the mobile layout?

**Comment by DeniseColbert** [comment]
Have _any_ decisions been made? I think we need to review it in Scrum, or the team comment offline, as no discussion on the design has been logged in the story.

**Comment by PatReynolds** [comment]
I will make some tickyboxes for the elements, to check what needs to be decided - please could all edit for what I've missed / got wrong?

**Comment by PatReynolds** [comment]
What I'm currently seeing on a Pixel 2 xl (Android 10)
![image](https://user-images.githubusercontent.com/6338822/73446501-cb93db00-4354-11ea-857a-b677f5a106c1.png)

**Comment by richpomfret** [comment]
@DeniseColbert shall we move this out of the Sprint Backlog? Close or change to make it a more tangible story/epic?

**Comment by richpomfret** [comment]
Closing - story now redundant.
