### ISSUE TITLE
Design Search Results page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#83]

**Comment by richpomfret** [comment]
2 weeks for first iteration would be fantastic - then we can implement once Vino has worked on the backend/setting up the DB

**Comment by richpomfret** [comment]
Discussion on whether to include additional information on the search results page in terms of a general newsletter sign-up or suggesting use of other sites (FC or FR) to further their research.

**Comment by PatReynolds** [comment]
Newsletter sign-up - in the footer?

Expand text above sister projects?

Put explanatory text below the sister projects (and/or build into icons, see Coordinaton #1070)

**Comment by neslihanu** [comment]
Aviel and I created the wireframes for search results page.

a general layout for search results page;
![00.00_Search Results Page.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/ccd6a69d-b3dc-4465-9bb8-fc71c2b3b72c)

a second option for general layout; we changed the layout of the call to action / CTA buttons including Feedback, Donate and Volunteer.

![00.00_Search Results Page.v2.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/1232a1d4-136e-42d1-b497-bc62a7d62782)

explanation of icons:
![FreeBMD results icons.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/fab1571c-f0c1-4cc6-b6d2-9a2616e320ae)

the realistic searches and search results page mockups:

![00.00_Search Results Page_Marriages.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/043542e4-45cb-449d-a95b-9b0d57f75617)
![00.00_Search Results_Births.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/26c9e428-81fd-4a31-9f3c-201e33b21dc1)
![00.00_Search Results Page_Deaths.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/ef905c73-5b99-40c7-bc5d-81f56f91e46a)

**Comment by Captainkirkdawson** [comment]
With FreeREG we replaced  the View with a row number ie We had Row 1; Row 2 etc so that the links were not all identical  thus help people with disabilities who used  screen-readers and or voice activation.

**Comment by PatReynolds** [comment]
See https://docs.google.com/document/d/18ZvMPbsmeYsrRcjnOI-NQ6MKdH3GpmFHEQH3ExZNuxQ/edit?usp=sharing for suggested changes to text.

**Comment by neslihanu** [comment]
To sum up, wireframes need below updates:
- For how to handle viewed results, see https://app.zenhub.com/workspaces/system-wide-code-changes-5ccc857f10a32d7d637c8f48/issues/freeukgen/systemwide/41

needing a final decision on this issue.

- Changes to text, see  https://docs.google.com/document/d/18ZvMPbsmeYsrRcjnOI-NQ6MKdH3GpmFHEQH3ExZNuxQ/edit?usp=sharing

**Comment by richpomfret** [comment]
Both above issues are currently being discussed on Slack. Second one has been decided, but first issue still outstanding.

**Comment by neslihanu** [comment]
Below updates has done:

1.) Text has updated, please check the final text on the wireframe.
2.) (Viewed) function has added, please check the design for details. We may consider a different design, I am not very happy with it.
3.) Also, I`ve added a "Printable Format" button. We do not have this function on FreeBMD1 but we have it on FreeReg & FreeCen. I believe this is a very useful feature for the user.  

Note: At the moment, I do not have time to update all "the realistic searches and search results page mockups". It is better to update them after we have a final decision on (Viewed) function design. 

![00.00_Search Results Page.v3.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/607fda09-3b24-41e7-8108-163b36a952e6)

**Comment by neslihanu** [comment]
There are some icons from Flat Icon website on the above mockups. You can download icons free of charge from Flat icon website but for commercial use you need to credit the author by including the attribution line. 
As agreed on Slack, I`ll change those icons and will use the icons from fontawesome website, licence and attribution should also be considered for fontawesome icons during deployment. 

I`m changing the status from Needs Review to In Progress and will share the updated mockup ASAP.

**Comment by neslihanu** [comment]
I`ve updated all the icons and also the logo on the footer, please find the updated mockup and icon list for comments/scan/entry info below. Also I`m attaching a txt doc for icons source. 

Also, please have a look into the icons for donate, give feedback and volunteer. Those are the only icons I`ve found on fontawesome website for free. For more attractive ones, maybe we need to pay for them. Or if you want to deploy the ones that are on the previous version of the mockup (which is attached above), those icons are from Flat icon website, you need to credit the author by including the attribution line or pay for the licence for commercial use. 
![FreeBMD results icons.v3.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/79b26edb-96da-4682-b46f-a4afa1e1edff)[https://app.zenhub.com/files/30762438/52ed1fa3-3a28-4b04-a84b-51d32018fcdf/download](https://app.zenhub.com/files/30762438/52ed1fa3-3a28-4b04-a84b-51d32018fcdf/download)![00.00_Search Results Page.v4.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/e8be251a-44b0-4a75-ab29-112cebced53d)

**Comment by PatReynolds** [comment]
All looking good, thank you @neslihanu

**Comment by richpomfret** [comment]
This looks great. Let's get further input in terms of review/feedback before final sign-off.

**Comment by neslihanu** [comment]
@richpomfret  @PatReynolds 

there is an ongoing discussion on #41  (View detail search result link and wording ) which affect the final design. 

Here is the updated wireframe for review:

![00.00_Search Results Page.v5.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/da5001ec-6359-4adf-b14f-b0f47ab036d1)

**Comment by PatReynolds** [comment]
Volunteer and Feedback icons are fine.

**Comment by PatReynolds** [comment]
@PatReynolds  to check with @Barrie what the 'new' icon means (last update or relating to a re-run search).

**Comment by PatReynolds** [comment]
Info icon to show content of m/s/a/d

**Comment by Captainkirkdawson** [comment]
@neslihanu In reviewing the results page again and looking at the line striping. All displays of mockups have been based on a search of all record types. What is the design expectation for the results page when there is a single record type search? Will all lines now be the same colour? Does that make sense? Take for example a search of deaths. All rows would be dark. Is this desirable?

**Comment by neslihanu** [comment]
@Captainkirkdawson 
Currently, there is a change in shade indicating non-contiguous entries on FreeBMD search results page, and this feature was discussed on Slack and we didn't change anything. 
Few months ago, I shared some mockups for realistic search results on Slack, as seen there, there should be a change in shade indicating non-contiguous entries. So it would depend on the search result records. 
![Screenshot_20191115_223513](https://user-images.githubusercontent.com/46780491/68980461-75ed6f00-07f8-11ea-8450-4ecf624962c2.jpg)

**Comment by Captainkirkdawson** [comment]
@neslihanu my question had nothing to do be contiguous records. 
It is much simpler than that. If one does a search for burials. All of the results will be burials ie every row will be stripped the same colour black. The same if you search for a birth all the results will be striped green. The mock up looks good because there is a variety of colours ie all record types. I am asking have you considered how the page will look if they all have the same colour. I suggest it may not look as good

**Comment by neslihanu** [comment]
@Captainkirkdawson 
Yes, of course we did. 
Please have look below designs ( realistic searchs and results) which we shared on Slack ux channel few months ago. 
***Old version of the search result page mockups*** but I hope they will give you an idea. 
Personally, I think if they all have the same color, the page will still look good. (have a look at the marriages-dark green first 5 results). 
@PatReynolds what do you think? 


![00 00_search_results_births](https://user-images.githubusercontent.com/46780491/68982354-8dc7f180-07fe-11ea-872b-5ab562f7411a.png)
![00 00_search_results_page_deaths](https://user-images.githubusercontent.com/46780491/68982358-915b7880-07fe-11ea-9803-4cf911bdc28a.png)
![00 00_search_results_page_marriages](https://user-images.githubusercontent.com/46780491/68982362-95879600-07fe-11ea-9e38-befff84aed1e.png)

**Comment by Captainkirkdawson** [comment]
Excellent That is what I needed to see.  
I just don't like the black one; I suspect it will fail accessibility contrast tests. Have you run such tests?

**Comment by neslihanu** [comment]
During wireframing, as far as I remember we've checked the colors and the accessibility of them. This is the original color code which is on FreeBMD. We can use a lighter grey and check it again.

**Comment by neslihanu** [comment]
Just made the updates, please have a look. Also checked the color contrast for accessibility. Please use below color codes during coding to meet web accessibility requirements. 
I`ve used https://webaim.org/resources/contrastchecker/ to check the requirements.  

**Note: I`m not sure that the color contrast of the "Search Page" search form background and text & buttons (foreground) has checked. If it hasn't, @Vino-S can you please check the color contrast ratio of the colors in the html&css code ? If it has been checked and confirmed before, you can use the same background color code for  the background color of the "You searched for" Table on the search results page. 

Search Results Table
-----------------------

Marriages
              Background Color        Foreground Color 
Dark       99CC99                         #000000
Light      #CCFFCC

Births
             Background Color      Foreground Color 
Dark     CC9999                       #000000
Light    #FFCCCC

Deaths
               Background Color      Foreground Color 
Dark        999999                        #000000
Light       #CCCCCC


"You searched for" Table
-------------------------

Background color of "You searched for" table:#EBFAFA
Buttons: #A1185A
Text:#000000


![00.00_Search Results Page.v6.png](https://images.zenhubusercontent.com/5cd985d5d341f7297326ca0e/59bd84b4-aa8f-4113-b4ff-c0a7d413c59c)

**Comment by Captainkirkdawson** [comment]
I presume we will adopt the ability to sort the results by column

I do not like the paging, other other sites rejected it. Scrollable is much better

Concerned that the top half of the page is now taken up with "extraneous" information such as the caution whih elsewhere is in the first part of the footer

**Comment by Captainkirkdawson** [comment]
Detailed comments on the design as implemented are given in #169 and expand on the last comments above

**Comment by PatReynolds** [comment]
Other notes from meeting 13/1/2020
About this query page needed - new story #192
Arrow is not needed.  
We discussed the merits of having a button (as in FreeREG and FreeCEN2) rather than simple text. Buttons look nicer, but are responsible for making the page longer / more white space.  More thought/input needed.
The elipsis indicating record type is very much liked.
Solution still needed to indicating non-contiguous records - new story - #191

**Comment by richpomfret** [comment]
@neslihanu have you had an opportunity to take a look at this?

**Comment by neslihanu** [comment]
Still working on it, here is the link for latest version of the prototype.
https://www.figma.com/proto/VjJhKU9ayU62rwczFyaUX0mt/FreeBMD-search-form-prototype?node-id=924%3A0&scaling=scale-down-width

Updates I’ve done so far:
1.	Removed the pagination.
2.	Removed the arrow- I think “a button” will not fit existing layout, it seems we do not have too much space after implementing side ads.
3.	Removed the percentage information next to the date.
4.	Re-designed the page and tried to redesign the content so it can fit 900px width as the ad starts at 900px in the container. I’ve put some details on the layout, you can see the sizes. Additional note: I did not want to change the screen resolution of the design files. I just played with the previous files. 
5.	I’ve changed the styling of the table, I think it would be good to use “Hoverable tables” or “Striped tables”, please have a look below link and let me know what you think. 
https://www.w3schools.com/css/css_table.asp
6.	I’ve used different colours for indicating different record types, please check the record type text and let me know your thoughts. I’ve changed the color codes as using green and red together is not good for accessibility.
7.	About displaying “non-contiguous records”, we have discussed many solutions so far including stripping and ellipse but unfortunately all of them did not work. To be honest, I don’t have any ideas about how we can do it. I believe we shouldn’t rely on color alone to convey a message as that can be a problem for accessibility. The best approach is to use both colors and symbols where users’ attention is required. But it seems we don’t have too much space to do it after implementing side-ads.

**Comment by PatReynolds** [comment]
2. Single side ad may give us more room.  May still not be room for buttons. : mock ups needed of two options (button and non-button).
5. Use hoverable tables (as on FreeCEN and FreeREG).
6. Blue is going to be 'pink for a link'.  Therefore decided: Marriages to be Blue ("something borrowed, somethng blue".death to be purple (a colour of mourning).
7. Possible solutions: colour the background of a contiguous record, or put a symbol on a contiguous record.  Symbols can by hyperlinked, so decided to go with a symbol.  Symbol - an asterisk (@Denise to find one - svg). @Vino-S to send to Denise (awesome icons).  @Vino-S to use https://www.freebmd.org.uk/search-faq.html#gap to implement

**Comment by Captainkirkdawson** [comment]
I would recommend that we place the continuous nature on the detail page; we are just trying to convey too much on the results page

**Comment by PatReynolds** [comment]
I think you meant "we are just trying to convey too much on the results page".  If so, the contiguous nature (or not) is only meaningful as part of the results (i.e.is this rresult/record contiguous, or not, with the one before or the one after).

**Comment by Captainkirkdawson** [comment]
Yes you were right about my error, corrected. 
I totally fail to understand what contiguous means. How can one result be contiguous with one result before or one result after.

**Comment by PatReynolds** [comment]
FreeBMD says:
What does "entries are not contiguous" mean?
On the search page the legend says a "Change of shade means entries are not contiguous". What does this mean and what causes it?
Where there are other entries in the index between consecutive entries in the search results there is a change of shade. This can arise for the following reasons:

The search criteria themselves produce non-contiguous entries, e.g. all the entries registered in a particular district
The data between the entries has not yet been transcribed
It has not been possible to automatically determine that transcribed pages are consecutive; we manually correct these where we find them

--------------
Clarified by Barrie in the UX channel in July 2019. 
Rather than talk of 'non-contiguous data' I find it easier to understand as 'contiguous data: - no change in shade indicates contiguous data, as might be observed with multiple births, or siblings who married (different people!) at the same time/place, or multiple deaths such as might occur with an accident or epidemic. You can only see that two people with the same surname were born, married or died at the same time if you search by surnames and see the records in the results page. [hoping Barrie will clarify if I have that).

**Comment by PatReynolds** [comment]
@Pat to talk to @Barrie about proposed soloution to information on contiguity.

example, for reference

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/cbcdec50-6bed-43ce-b04b-99449d96cdc4)

**Comment by PatReynolds** [comment]
See slack discussion.

**Comment by PatReynolds** [comment]
Revised text of document about contiguity 7/4/2020
