### ISSUE TITLE
Persistent urls

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#87]
Needs to use the same generated hash as FreeBMD1 does.

Previously:
Need to decide how to do this
a) as on FreeBMD1 - an url to copy
b) as current on multi-modal codebase (albeit as a prettified url) - what you see in the page url
c) as planned on multi-modal codebase (alongside citation buttons, a click-to-copy button).

**Comment by Captainkirkdawson** [comment]
Why would you deviate from MyopicVicar? If that is incorrect change it there!!!

**Comment by PatReynolds** [comment]
As FreeREG - plus add wikipedia citation.

Perhaps ask eveloper working on FreeREG citations to take a look once specified.

**Comment by PatReynolds** [comment]
Kirk's comment seems to have taken me off-track here - Citations is #113 

Example on freeBMD2 : https://test3.freebmd.org.uk/60100e3fe93790be1188000a

https://www.freebmd.org.uk/60100e3fe93790be1188000a does not find - freeBMD1 url is 
https://www.freebmd.org.uk/cgi/information.pl?cite=qg6KENmPu%2BhEy5taYKZFYg&scan=1

**Comment by PatReynolds** [comment]
Pat to test again with ENTRY INFORMATION page - and full text.

**Comment by PatReynolds** [comment]
Tested with:
https://test3.freebmd.org.uk/6061af02bd30f26b2b7d1687/entry-information/129774611/may-alcock-birth-derbyshire-chesterfield-v7b-p1492?locale=en

Neither
https://www.freebmd.org.uk/6061af02bd30f26b2b7d168
nor
https://www.freebmd.org.uk/6061af02bd30f26b2b7d1687/entry-information/129774611/may-alcock-birth-derbyshire-chesterfield-v7b-p1492?locale=en
works

Should be:
https://www.freebmd.org.uk/cgi/information.pl?cite=swwyulJ3aVTTNB%2BV3YMhCg&scan=1

HOWEVER: 
https://test3.freebmd.org.uk/swwyulJ3aVTTNB%2BV3YMhCg/entry-information/129774611/may-alcock-birth-derbyshire-chesterfield-v7b-p1492?locale=en
works but https://test3.freebmd.org.uk/cgi/information.pl?cite=swwyulJ3aVTTNB%2BV3YMhCg&scan=1 (i.e. the format that people will have saved the url in does not work).

So what is needed is something that will transform https://test3.freebmd.org.uk/cgi/information.pl?cite=swwyulJ3aVTTNB%2BV3YMhCg&scan=1 behind the scenes to https://test3.freebmd.org.uk/cgi/information.pl?cite=swwyulJ3aVTTNB%2BV3YMhCg

**Comment by richpomfret** [comment]
@lemon-ukgen @Vino-S how might we do this?

**Comment by lemon-ukgen** [comment]
I find the examples above unclear.

Are we talking about

1/ Redirecting bookmarked FreeBMD1 URLs (ie: those that contain `/cgi/` in them) to FreeBMD2 URLs (ones with long numbers and Rails-ish paths in them)

or 

2/ Making FreeBMD1 know what to do with FreeBMD2 URLs (eg: making https://www.freebmd.org.uk/6061af02bd30f26b2b7d168 -- the FreeBMD1 site with a FreeBMD2 search result path -- work correctly)

?

The first is doable in Apache if there's a static list of URLs to map from one to another. This is something we've done for a handful of informational URLs on FreeREG2, eg: redirecting `/tips-for-searching-the-database` (a FreeREG1 static page) to the home page, but it's an awkward proposition for an unbounded list of URLs unless there's a simple text manipulation mapping from one to the other.

I'd suggest it's better do it in the RoR app, where there is more information to perform the mapping (I hope!)

I'm not sure what to say about the second option. Feels like modifying the "legacy" app to understand the replacement app's URL scheme is going in an odd direction and the implementation is heavily constrained by the application deployment - the FreeBMD1 app has no concept of RoR-like routes, so even handling `/6061af02bd30f26b2b7d168` would need some non-small work on the server setup.

**Comment by richpomfret** [comment]
@lemon-ukgen thank you. @PatReynolds is asking what we might do in the case of number 1 - redirecting bmd1 urls (cgi).

**Comment by lemon-ukgen** [comment]
Thanks. One for the RoR developers I think, unless it's a small (under 100, say) set of fixed URLs that we want mapped.

**Comment by PatReynolds** [comment]
I think the original plan was that freebmd2 would create its urls using the same software as FreeBMD1.  But it isn't.  Ideally https://test3.freebmd.org.uk/cgi/information.pl?cite=oXUmag45RDm0SNeK9wLMqQ&scan=1 should reach what is currently https://test3.freebmd.org.uk/60c88e22bd30f2914f6a837a/entry-information/92948892/william-alcock-marriage-staffordshire-w-bromwich-v6b-p826?locale=en

If it doesn't work until the URL switch, that is fine.

Or if FreeBMD2 continues to have different URLS, but anyone entering the FreeBMD1 URL is taken to the FreeBMD2 page, that is also fine.

**Comment by PatReynolds** [comment]
The task is:
a) FreeBMD1 urls redirect to FreeBMD2 record detail urls (when FreeBMD2 has the form www.freebmd.org.uk

b) FreeBMD2 generates citations that direct to the same record detail urls (assuming that a FreeBMD2 url will not be identical to the corresponding FreeBMD1 url, then either via the FreeBMD1 reroute, or the genuine FreeBMD2 url can be used in citations, although genuine FreeBMD is to be preferred, if possible).

Suggest closing this story and making two new tasks, (b) dependent on (a).

**Comment by PatReynolds** [comment]
Stories made
