### ISSUE TITLE
Prettified URLs

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#88]
Multi-modal codebase has prettified urls.  Given how little data there is in FreeBMD is this desirable? 

Example:
https://www.freebmd.org.uk/cgi/information.pl?cite=WQQMeFAhfTjKxcbddFaYCg&scan=1/richard-alcock-northallerton-1840-birth

**Comment by PatReynolds** [comment]
Already implemented

**Comment by richpomfret** [comment]
Hurray! Closing.
