### ISSUE TITLE
Consider and Decide initial phase implementation of the Volunteering pages/pathway

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#89]
We need to document the current process - perhaps @mburnham-1 has already done this?

Some elements will replicate the current common code.  Others may need to change.

Minimum would be the common codebase initial page (i.e. page which had a link for those wishing to transcriber and a link for those wishing to volunteer as a developer or designer.  
For discussion: the former could link to https://www.freebmd.org.uk/Signup.html or more of the process (some, or all) could be handled in FreeBMD2.
The latter, as with th other projects, would link to the FreeUKgenealogy.org.uk website.

**Comment by mburnham-1** [comment]
Hi Pat,I don't know if Rich has told you but I am unavailable until August.I have completed the Primary & Secondary Links between pages, but not yet completed the tertiary links.
I have done no work on Process at all.
Until later,Best regardsMike
    On Friday, 28 June 2019, 11:12:11 BST, PatReynolds <notifications@github.com> wrote:  
 
 
We need to document the current process - perhaps @mburnham-1 has already done this?

Some elements will replicate the current common code. Others may need to change.

**Comment by PatReynolds** [comment]
Two options for https://test2.freebmd.org.uk/userid_details/transcriber_registration? 
a) replace with a Refinery page including a link to FreeBMD1 could include the text and other links from https://www.freebmd.org.uk/Signup.html
b) retain the MyopicVicar page, adding the 'syndicates available' from FreeBMD1 as the choices. See https://www.freebmd.org.uk/cgi/list-synd.pl?reader=0

advantages of (a). It's easier. there would be no need to interface with the systems and databases of FreeBMD1.
advantages of (b). Would mean we could begin the Open Data signup for new transcribers in just one place, rather than possibly in two.

For discussion and decision

**Comment by richpomfret** [comment]
With BMD2 initially being Researcher focused, we can link back to BMD1 for anything related to volunteering/transcribing etc.

**Comment by PatReynolds** [comment]
Context: MVP is about researchers, not transcribers.

However, having first stage volunteer sign up on FreeBMD2 will ensure all new volunteers get the link to the privacy policy, which is not on FreeBMD1 (yet - trac issue #638 still waiting for implementation after a year).

DRAFT MVP implementation on FreeBMD would be 
https://freebmd2.freebmd.org.uk/cms/opportunities-to-volunteer-with-freebmd with links as normal for other volunteering, but link  "Proceed for Registration" (to * https://www.freebmd.org.uk/Signup.html)
* Text "To register as a transcriber, please press the button below." to be amended to "To register as a transcriber, please press the button below (takes you from FreeBMD2 to FreeBMD1".

DRAFT Preferred implementation on FreeBMD would be:
https://freebmd2.freebmd.org.uk/cms/opportunities-to-volunteer-with-freebmd with links as for FreeREG and FreeCEN.
https://freebmd2.freebmd.org.uk/userid_details/transcriber_registration 
* excluding the syndicates list 
* including information from https://www.freebmd.org.uk/Signup.html moved to FreeBMD2 
* adding an instruction to keep a note of the User ID chosen, as it will be needed in the next step, which will take you out of FreeBMD2 and onto FreeBMD1
* Link the 'sign up as a transcriber button'  to https://www.freebmd.org.uk/cgi/list-synd.pl?reader=0  changed to 'continue sign up' 

I can't see an easy way of presenting the syndicate choices and then transferring to FreeBMD1 for completion.

Thought of developers on practicality of these, any alternatives, and implementation costs for the two (following refinement) needed.

**Comment by Captainkirkdawson** [comment]
1. Note you are using freebmd2.freebmd.org.uk in the previous text. We are currently using test2.freebmd.org.uk. See #105
WRT this story. The following links are active
2. https://test2.freebmd.org.uk/cms/opportunities-to-volunteer-with-freebmd currently exists. Wording changes in the text can be done in RefineryCMS no programmer input is required
Changing the link to a freebmd1 page is  minor . A size 2
3. It would be just as easy to leave the Proceed to Registration as is This takes you to
https://test2.freebmd.org.uk/userid_details/transcriber_registration?. Text changes can be made. Size 2-3. Rather than the form for registering the Register as a Transcriber this could be replace with the link to the FreeBMD1 registration page
Total size no more than 5. Benefits are access to policies and any updates and ease of transition to active registration. Downside is that volunteering this way is 3 click process.

**Comment by archerbarrie** [comment]
This is something of a side issue, but I don't know where else to record it. The text of https://test2.freebmd.org.uk/cms/opportunities-to-volunteer-with-freebmd is almost entirely wrong and does not reflect how FreeBMD transcribing works. Maybe it is WIP but I see no indication of that.

**Comment by richpomfret** [comment]
Thanks @archerbarrie, have created story #110 to cover finalising text for the volunteer page (it is placeholder, as you say, although that isn't clear and needs to be be tracked). The same applies to other pages that have been carried over/easily generated from FR (about/cookie page etc).

**Comment by PatReynolds** [comment]
@PatReynolds  to contact Barrie and Allan re the implementation proposal

**Comment by PatReynolds** [comment]
Proposed solution: text change as in FreeUKGen/FreeBMD2#110

Remove syndicate choice for MVP release.

Text for auto email as in FreeUKGen/FreeBMD2#110

**Comment by mburnham-1** [comment]
Hi Pat,Very sorry that I have not been around for a long time.Hopefully back in action in the near future.RegardsMike
    On Monday, 7 October 2019, 12:30:44 BST, PatReynolds <notifications@github.com> wrote:  
 
 
Proposed solution: text change as in #110

Remove syndicate choice for MVP release.

Text for auto email as in #110

**Comment by richpomfret** [comment]
We can now close this - we have stories that cover what is now needed.
