### ISSUE TITLE
Decide Placement of News Link

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#90]
Free BMD is the only project, currently, with a news link, although this is a planned feature for all projects, perhaps utilising the FreeUKGenealogy news which has been tagged with the project name.

For decision: where to place the link to the news on the search page.  

For what it's worth, putting it on the banner above the footer (following the database update stats) would seem a good space not currently utilised.

**Comment by Captainkirkdawson** [comment]
The header, footer story zen #66  includes the news link in the footer in the second column of links.

**Comment by PatReynolds** [comment]
Decided place as "history of FreeBMD" within 'About'

**Comment by PatReynolds** [comment]
@PatReynolds to speak to Allan re this position.

**Comment by PatReynolds** [comment]
Asked Allan 14/10

**Comment by richpomfret** [comment]
@PatReynolds to create mock-up page in suggested location to show Allan. Vino has sent through refinery login link.

**Comment by richpomfret** [comment]
Go ahead and implement.
