### ISSUE TITLE
Implement solution to News

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#92]
For feedback:
Three possible solutions nb, passim, 'blog' is  sometimes used as a term to facilitate discussion here, but will be 'news' as far as the readers are concerned.
a) The existing and future news for FreeBMD is placed in a FreeBMD2 blog (might use https://github.com/refinery/refinerycms-blog)
b) The FreeBMD2 blog displays news posts from FreeUKGenealogy.org.uk which are tagged 'freeBMD' (i.e. creating the FreeBMD news from contributions to the FreeUK Genealogy blog, both the kind of stories that already exist there, and new stories which cover ground currently on FreeBMD1 news) 
c) Both! The news for FreeBMD is placed in a FreeBMD2 blog, AND the blog displays news posts from FreeUKGenealogy.org.uk which are tagged 'freeBMD'

Advantages 
a) would improve the current process
b) would be easily implemented in FreeCEN and FreeREG, too and might be easier for users (as WP rather than Refinery)
c) would be implemented in FreeCEN and FreeREG, too (the FreeUKgenealogy>searchsite part)

Disadvantages
a) would mean writing / reviewing news in Refinery (harder than wordpress)
b) would mean creating a FreeUKGenealogy post that just contained the old FreeBMD2 news, which would therefore appear out of sequence. also might not fit tone/style of other FreeUKGenealogy news posts without revision (revision is not necessarily a Good Thing)
c) would probably take significantly more developer time

**Comment by PatReynolds** [comment]
Suggest that only (a) if that is MVP.

**Comment by PatReynolds** [comment]
Using https://github.com/refinery/refinerycms-blog appears to be quite complicated (to my eyes) and therefore a post-MVP task. I will create a story for that.

News and History now begun on test2 - News done, History to be done.

**Comment by DeniseColbert** [comment]
Since (a) is now not MVP, we still need a decision on (a), (b) or (c)

**Comment by richpomfret** [comment]
@DeniseColbert to test 'new' 'news' page.

**Comment by DeniseColbert** [comment]
I can't see this page in Refinery test3- am I looking in the right place?

**Comment by richpomfret** [comment]
Should be in 'About' according to @PatReynolds and a link would be appreciated.

**Comment by DeniseColbert** [comment]
There is a random PayPal donate button in here, and there is not the full extent of the news on https://www.freebmd.org.uk/news.html

**Comment by DeniseColbert** [comment]
There seems to be a random donate button (PayPal) and it doesn't contain the full extent of the news on https://www.freebmd.org.uk/news.html (if that was the intent)

**Comment by PatReynolds** [comment]
@PatReynolds to take a look

**Comment by PatReynolds** [comment]
@PatReynolds to ask Allan to review and update

**Comment by richpomfret** [comment]
We will close this story shortly, as the solution has been completed, it is now a case of 'bring it up to date' with recent-ish news.

**Comment by richpomfret** [comment]
Closing - should have a separate story (or one will be created for updating news).
