### ISSUE TITLE
Use 'Regular' version of Source Sans Pro font

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#93]

**Comment by PatReynolds** [comment]
Emailed trustees 22/7/2019

**Comment by Captainkirkdawson** [comment]
This is a the same story as systemwide #40 where there had been prior comments and review. There was concern over this possibly breaking tables in the current apps

**Comment by richpomfret** [comment]
Duplicate so closing.

**Comment by PatReynolds** [comment]
Can basic font be set by application in multimodal?

**Comment by richpomfret** [comment]
We will need to do this sooner rather than later and lead on BMD2.

**Comment by Captainkirkdawson** [comment]
This was completed as part of systenwide #40
