### ISSUE TITLE
Decide and create text/features for the magenta and dark grey panels at bottom of page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#94]
See FreeREG for what full content looks like there, and FreeCEN for the place-holding text.  

For decision: do we go with FreeCEN-style placeholding as MVP, or a FreeREG-style which has summary statistics on latest update, i.e.
X searches were performed on Y records (Z births, A marriages and B deaths)
C records (D births, E marriages and F deaths) were added in the latest update.

Do we want to add in 'latest year being transcribed' for these? Anything else?

Suggest link to a refinery page called statistics which has links as in https://www.freebmd.org.uk/iindex.shtml 

Text on copyright on story #66

**Tasks remaining 15/2/2020**
Magenta panel
- [ ] Add link to help on errors (see comment 15/2/2020 below).
White panel
Covered by Systemwide#91 and Systemwide#98
Dark grey panel
Covered by FreeBMD2#199 and Systemwide#98

-

**Comment by PatReynolds** [comment]
Statistics to go on black panel.

**Comment by PatReynolds** [comment]
Add "latest year to black panel"

**Comment by PatReynolds** [comment]
Remaining issue in this story is adding this link:
<li><a href="#Accuracy">Accuracy of FreeBMD</a> </li> @AlOneill is this the correct href, or does it also need the page (Help) before #Accuracy?

Please add to the footer as a ink from 'accuracy or completeness of the data' in: - We make no warranty whatsoever as to the accuracy or completeness of the data.

**Comment by AlOneill** [comment]
A hash-sign-prefixed `href` points to a part of the same page, so yes the address should be: `/cms/help#Accuracy` (although "accuracy" would be more consistent with the style of capitalisation we usually employ for an `id`, I see that "Accuracy" is the id on test 3).

**Comment by PatReynolds** [comment]
thanks, @AlOneill   I have made the id lower case on test3, for accuracy.

@Vino-S  this is now ready to be added to the black panel (from the words " accuracy or completeness of the data".

Thank you both, Pat.

**Comment by Vino-S** [comment]
Ready for testing

**Comment by PatReynolds** [comment]
Thank you, @Vino, that works perfectly

**Comment by PatReynolds** [comment]
Only remaining task (statistics) is covered by #190, so closing this.
