### ISSUE TITLE
Reconsider adding side adverts to Beta search page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#95]
See wireframe - there are spaces for two adverts that slightly overlap the footer, on either side of the main area of the page

Page as designed does not have space - reconsider at a later phase..

**Comment by richpomfret** [comment]
@PatReynolds a question came up in the meeting in relation to our advert placement. For MVP I would presume we mirror exactly the advert position/set-up we have on both FC and FR?

**Comment by richpomfret** [comment]
Ready for testing on Test2.

**Comment by richpomfret** [comment]
Issue of what to do when an Adblocker is used. Handle it as we do on FR/FC but with new assets or our own ads?

**Comment by richpomfret** [comment]
@PatReynolds. Are we fine to sign this off? We will need a separate story for creating specific ads for when an adblocker is used.

**Comment by PatReynolds** [comment]
Yes this is fine.

**Comment by PatReynolds** [comment]
This doesn't seem to  have been implemented.

There is a conflict between the story name (place advert to the right on the search page) and the assumpton that FreeBMD2 should mirror what is done on FreeREG and FreeCEN2 - i.e. no advert to the side on the search page.

We have agreed a sponsorship advertising slot for FreeBMD1, and that should be factored into advert design (either for the search page or somewhere.

**Comment by PatReynolds** [comment]
Search page now takes full width of screen, so closing.
