### ISSUE TITLE
Decide MVP of Transcriber registration

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#98]
Two options for https://test2.freebmd.org.uk/userid_details/transcriber_registration? 
a) replace with a Refinery page including a link to FreeBMD1  could include the text  and other links from https://www.freebmd.org.uk/Signup.html
b) retain the MyopicVicar page, adding the 'syndicates available' from FreeBMD1 as the choices.  See https://www.freebmd.org.uk/cgi/list-synd.pl?reader=0

advantages of (a).  It's easier.  there would be no need to interface with the systems and databases of FreeBMD1.
advantages of (b). Would mean we could begin the Open Data signup for new transcribers in just one place, rather than possibly in two. 

For discussion and decision

**Comment by richpomfret** [comment]
I would keep the MVP free of anything transcriber related - it should be purely Researcher orientated in my opinion. Post MVP, we could include option A initially (as it is quickest) and then iterate towards option B. I recall a question being asked about exactly how much transcription remains on FreeBMD and I do wonder where we are with this, particularly in light of any possible new data coming in..

**Comment by richpomfret** [comment]
@PatReynolds we need to lock this down for MVP during this sprint (in terms of design).

**Comment by PatReynolds** [comment]
In order to prevent new volunteers from choosing an existing user ID, the existing IDs will need to be loaded into FreeBMD2

**Comment by richpomfret** [comment]
We can consider this done - can be closed with additional, specific stories added for implementation phase.
