### ISSUE TITLE
Review FreeBMD1 pages and decide which are to be moved to Refinery, and which not, as MVP

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#99]
There are a huge number of pages, and not all can be moved into Refinery as part of the MVP (cf time being taken on FreeCEN to get their pages over). I would suggest that we discuss the content of https://www.freebmd.org.uk/iindex.shtml and Audit of second level pages (https://docs.google.com/document/d/1EeLOwV9qalZEEWPZi8P8h7adnAfiZg1C0QQ313D4j2c/edit?usp=sharing) and decide which are MVP either as the 'help' page or elsewhere and which are 'later' (i.e. accessed on FreeBMD1).

To include looking at General Information and Statistics links on https://www.freebmd.org.uk/iindex.shtml and deciding which to implement on About, which on Help, and which not to implement as MVP.

Listing of pages to be transferred, and when: https://docs.google.com/document/d/1BPPLm2ROJmfAuIMJUUH4fd3tH5Y1XhuyrC53_erm57w/edit?usp=sharing

**Comment by richpomfret** [comment]
As we are discussing the MVP, only the basic help pages for researchers should be included. First step, as you say, is to ascertain which ones we include and secondly, which may need to be reviewed and updated (or rewritten). The MVP really should be very basic - we iterate and improve incrementally from there.

**Comment by richpomfret** [comment]
@PatReynolds @DeniseColbert we have arrived at the time where we now need to make this decision. We might need a separate, specific meeting to go over this and discuss it once we think we know what we would like to see.

**Comment by PatReynolds** [comment]
@PatReynolds  and @richpomfret to look at Mike's audit and indicate which pages are to be part of MVP

**Comment by PatReynolds** [comment]
@Rich can you review my first cut, please.  Also, if you can identify the pages I couldn't, can you let me have links?

**Comment by PhilipClarke712** [comment]
Most, if not  all, the pages listed in the Audit at 2ary level are being worked on, including the text of https://www.freebmd.org.uk/iindex.shtml. There were one or two I could not identify. About 40 pages are sitting in the shared Documents (in progress) folder at 1st-stage-html-mark-up, awaiting decisions on what the BMD2 pages should "look" it (including any icons, which are not in place on test3). Some of those page listed in the spreadsheet appear to be regarded in the audit itself as 3ary so were not audited for hyperlinks; they are also done to 1st-pass-html-mark-up. Other than these, no 3ary pages to my knowledge have been worked on, but they may well be need.
It would be useful have a "ranking of important" in respect of the order they need to go through Refinery.

**Comment by PatReynolds** [comment]
Is there anything else which needs to be decided, or can this be closed?

**Comment by PhilipClarke712** [comment]
Hi Pat,

You can close it. 

The time frame available would help. At present, nothing has gone on.

At one extreme we can put everything on now that needs doing, but that means for some pages using the old BMD(1)  images, icons and figures. Then we could go back and change images, etc., once the relevant bits are operational on test3. 

The other extreme is only to put through Refinery only what is not likely to change. 

A half-way house  would be to go via Comfort to the design people and get wire-frame designs and to use them to change in advance what is likely to need changing.

Sent from Mail for Windows 10
